package com.creditease.rc.app.smp;



import com.creditease.core.orm.Entity;

public class CityDTO extends Entity{
	private static final long serialVersionUID = 1L;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SELLMANAGER.TM_CITY.CITY_ID
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    private Integer cityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SELLMANAGER.TM_CITY.CITY_NAME
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    private String cityName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SELLMANAGER.TM_CITY.CITY_CODE
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    private String cityCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SELLMANAGER.TM_CITY.ONLINE_FLAG
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    private String onlineFlag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SELLMANAGER.TM_CITY.CITY_ID
     *
     * @return the value of SELLMANAGER.TM_CITY.CITY_ID
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SELLMANAGER.TM_CITY.CITY_ID
     *
     * @param cityId the value for SELLMANAGER.TM_CITY.CITY_ID
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SELLMANAGER.TM_CITY.CITY_NAME
     *
     * @return the value of SELLMANAGER.TM_CITY.CITY_NAME
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SELLMANAGER.TM_CITY.CITY_NAME
     *
     * @param cityName the value for SELLMANAGER.TM_CITY.CITY_NAME
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SELLMANAGER.TM_CITY.CITY_CODE
     *
     * @return the value of SELLMANAGER.TM_CITY.CITY_CODE
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SELLMANAGER.TM_CITY.CITY_CODE
     *
     * @param cityCode the value for SELLMANAGER.TM_CITY.CITY_CODE
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SELLMANAGER.TM_CITY.ONLINE_FLAG
     *
     * @return the value of SELLMANAGER.TM_CITY.ONLINE_FLAG
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public String getOnlineFlag() {
        return onlineFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SELLMANAGER.TM_CITY.ONLINE_FLAG
     *
     * @param onlineFlag the value for SELLMANAGER.TM_CITY.ONLINE_FLAG
     *
     * @ibatorgenerated Wed Jun 30 17:05:01 CST 2010
     */
    public void setOnlineFlag(String onlineFlag) {
        this.onlineFlag = onlineFlag;
    }
}