package com.creditease.rc.app.cm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CreditCMClientWSService service = new CreditCMClientWSService();
 * CreditCMClientWS portType = service.getCreditCMClientWSPort();
 * portType.getImgAmount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CreditCMClientWSService", targetNamespace = "http://service.creditease/", wsdlLocation = "http://10.100.30.54:8080/CreditCMClient/WebService/CreditCMClientWS?wsdl")
public class CreditCMClientWSService extends Service {

	private final static URL CREDITCMCLIENTWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.creditease.rc.app.cm.CreditCMClientWSService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.creditease.rc.app.cm.CreditCMClientWSService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.100.30.54:8080/CreditCMClient/WebService/CreditCMClientWS?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.100.30.54:8080/CreditCMClient/WebService/CreditCMClientWS?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CREDITCMCLIENTWSSERVICE_WSDL_LOCATION = url;
	}

	public CreditCMClientWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CreditCMClientWSService() {
		super(CREDITCMCLIENTWSSERVICE_WSDL_LOCATION, new QName(
				"http://service.creditease/", "CreditCMClientWSService"));
	}

	/**
	 * 
	 * @return returns CreditCMClientWS
	 */
	@WebEndpoint(name = "CreditCMClientWSPort")
	public CreditCMClientWS getCreditCMClientWSPort() {
		return super.getPort(new QName("http://service.creditease/",
				"CreditCMClientWSPort"), CreditCMClientWS.class);
	}

}
