package com.creditease.rc.app.cm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CreditCMClientWS", targetNamespace = "http://service.creditease/")
public interface CreditCMClientWS {

	/**
	 * 
	 * @param bussTableName
	 * @param clientId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImgAmount", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgAmount")
	@ResponseWrapper(localName = "getImgAmountResponse", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgAmountResponse")
	public String getImgAmount(
			@WebParam(name = "clientId", targetNamespace = "") String clientId,
			@WebParam(name = "bussTableName", targetNamespace = "") String bussTableName);

	/**
	 * 
	 * @param bussTableName
	 * @param clientId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIsExistClientID", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetIsExistClientID")
	@ResponseWrapper(localName = "getIsExistClientIDResponse", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetIsExistClientIDResponse")
	public String getIsExistClientID(
			@WebParam(name = "clientId", targetNamespace = "") String clientId,
			@WebParam(name = "bussTableName", targetNamespace = "") String bussTableName);

	/**
	 * 
	 * @param filetypes
	 * @param bussTableName
	 * @param batchId
	 * @param clientId
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "achieveIntegrityTypeFilesPath", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.AchieveIntegrityTypeFilesPath")
	@ResponseWrapper(localName = "achieveIntegrityTypeFilesPathResponse", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.AchieveIntegrityTypeFilesPathResponse")
	public List<String> achieveIntegrityTypeFilesPath(
			@WebParam(name = "bussTableName", targetNamespace = "") String bussTableName,
			@WebParam(name = "clientId", targetNamespace = "") String clientId,
			@WebParam(name = "batchId", targetNamespace = "") String batchId,
			@WebParam(name = "filetypes", targetNamespace = "") String filetypes);

	/**
	 * 
	 * @param bussTableName
	 * @param clientId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImgLenderAmount", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgLenderAmount")
	@ResponseWrapper(localName = "getImgLenderAmountResponse", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgLenderAmountResponse")
	public String getImgLenderAmount(
			@WebParam(name = "clientId", targetNamespace = "") String clientId,
			@WebParam(name = "bussTableName", targetNamespace = "") String bussTableName);

	/**
	 * 
	 * @param bussTableName
	 * @param batchId
	 * @param clientId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImgBorrowAmount", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgBorrowAmount")
	@ResponseWrapper(localName = "getImgBorrowAmountResponse", targetNamespace = "http://service.creditease/", className = "com.creditease.rc.app.cm.GetImgBorrowAmountResponse")
	public String getImgBorrowAmount(
			@WebParam(name = "clientId", targetNamespace = "") String clientId,
			@WebParam(name = "batchId", targetNamespace = "") String batchId,
			@WebParam(name = "bussTableName", targetNamespace = "") String bussTableName);

}
