package com.creditease.rc.vo;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.creditease.rc.common.JsonYMDDateSerializer;

public class ApplicationInfo {
	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APPLICATION_INFO_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long applicationInfoId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long applicationId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.BORROWER_TYPE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Short borrowerType;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.COMMON_BORROWER_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Date commonBorrowerDate;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String appInfoName;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.BEFOR_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String beforName;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.IDENTITY_CARD
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String identityCard;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO_AGE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long appInfoAge;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO_SEX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String appInfoSex;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.REGISTERED_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long registeredProvince;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.REGISTERED_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long registeredCity;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.REGISTERED_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long registeredArea;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.REGISTERED_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String registeredDetail;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.EFFECTIVE_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String effectiveDate;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.EFFECTIVE_END_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Date effectiveEndDate;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long presentAddressProvince;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long presentAddressCity;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Long presentAddressArea;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String presentAddressDetail;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO_FAX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String appInfoFax;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.LOCAL_LIVE_YEAR
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String localLiveYear;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.LOCAL_LIVE_MONTH
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String localLiveMonth;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO__MOBILE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String appInfoMobile;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APP_INFO__TELEPHONE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String appInfoTelephone;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.MARITAL_STATUS
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String maritalStatus;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.MARITAL_STATUS_EXPLAIN
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String maritalStatusExplain;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.LIVE_QUATITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String liveQuatity;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.FAMILY_REVENUE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private BigDecimal familyRevenue;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.AVG_MONTH_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private BigDecimal avgMonthPay;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.OTHER_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private BigDecimal otherPay;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.REPAYMENT
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private BigDecimal repayment;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.APPLICATION_WORK_HISTORY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private String applicationWorkHistory;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_APPLICATION_INFO.HISTORYFLAG
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	private Short historyflag;

	private String comBorrowerStatus;

	public String getComBorrowerStatus() {
		return comBorrowerStatus;
	}

	public void setComBorrowerStatus(String comBorrowerStatus) {
		this.comBorrowerStatus = comBorrowerStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APPLICATION_INFO_ID
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APPLICATION_INFO_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getApplicationInfoId() {
		return applicationInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APPLICATION_INFO_ID
	 * 
	 * @param applicationInfoId the value for MFC_APPLICATION_INFO.APPLICATION_INFO_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setApplicationInfoId(Long applicationInfoId) {
		this.applicationInfoId = applicationInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APPLICATION_ID
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APPLICATION_ID
	 * 
	 * @param applicationId the value for MFC_APPLICATION_INFO.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setApplicationId(Long applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.BORROWER_TYPE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.BORROWER_TYPE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Short getBorrowerType() {
		return borrowerType;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.BORROWER_TYPE
	 * 
	 * @param borrowerType the value for MFC_APPLICATION_INFO.BORROWER_TYPE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setBorrowerType(Short borrowerType) {
		this.borrowerType = borrowerType;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.COMMON_BORROWER_DATE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.COMMON_BORROWER_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getCommonBorrowerDate() {
		return commonBorrowerDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.COMMON_BORROWER_DATE
	 * 
	 * @param commonBorrowerDate the value for MFC_APPLICATION_INFO.COMMON_BORROWER_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setCommonBorrowerDate(Date commonBorrowerDate) {
		this.commonBorrowerDate = commonBorrowerDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO_NAME
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getAppInfoName() {
		return appInfoName;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO_NAME
	 * 
	 * @param appInfoName the value for MFC_APPLICATION_INFO.APP_INFO_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoName(String appInfoName) {
		this.appInfoName = appInfoName == null ? null : appInfoName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.BEFOR_NAME
	 * 
	 * @return the value of MFC_APPLICATION_INFO.BEFOR_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getBeforName() {
		return beforName;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.BEFOR_NAME
	 * 
	 * @param beforName the value for MFC_APPLICATION_INFO.BEFOR_NAME
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setBeforName(String beforName) {
		this.beforName = beforName == null ? null : beforName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.IDENTITY_CARD
	 * 
	 * @return the value of MFC_APPLICATION_INFO.IDENTITY_CARD
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getIdentityCard() {
		return identityCard;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.IDENTITY_CARD
	 * 
	 * @param identityCard the value for MFC_APPLICATION_INFO.IDENTITY_CARD
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard == null ? null : identityCard.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO_AGE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO_AGE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getAppInfoAge() {
		return appInfoAge;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO_AGE
	 * 
	 * @param appInfoAge the value for MFC_APPLICATION_INFO.APP_INFO_AGE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoAge(Long appInfoAge) {
		this.appInfoAge = appInfoAge;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO_SEX
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO_SEX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getAppInfoSex() {
		return appInfoSex;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO_SEX
	 * 
	 * @param appInfoSex the value for MFC_APPLICATION_INFO.APP_INFO_SEX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoSex(String appInfoSex) {
		this.appInfoSex = appInfoSex == null ? null : appInfoSex.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.REGISTERED_PROVINCE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.REGISTERED_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getRegisteredProvince() {
		return registeredProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.REGISTERED_PROVINCE
	 * 
	 * @param registeredProvince the value for MFC_APPLICATION_INFO.REGISTERED_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setRegisteredProvince(Long registeredProvince) {
		this.registeredProvince = registeredProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.REGISTERED_CITY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.REGISTERED_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getRegisteredCity() {
		return registeredCity;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.REGISTERED_CITY
	 * 
	 * @param registeredCity the value for MFC_APPLICATION_INFO.REGISTERED_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setRegisteredCity(Long registeredCity) {
		this.registeredCity = registeredCity;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.REGISTERED_AREA
	 * 
	 * @return the value of MFC_APPLICATION_INFO.REGISTERED_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getRegisteredArea() {
		return registeredArea;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.REGISTERED_AREA
	 * 
	 * @param registeredArea the value for MFC_APPLICATION_INFO.REGISTERED_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setRegisteredArea(Long registeredArea) {
		this.registeredArea = registeredArea;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.REGISTERED_DETAIL
	 * 
	 * @return the value of MFC_APPLICATION_INFO.REGISTERED_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getRegisteredDetail() {
		return registeredDetail;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.REGISTERED_DETAIL
	 * 
	 * @param registeredDetail the value for MFC_APPLICATION_INFO.REGISTERED_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setRegisteredDetail(String registeredDetail) {
		this.registeredDetail = registeredDetail == null ? null : registeredDetail.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.EFFECTIVE_DATE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.EFFECTIVE_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getEffectiveDate() {
		return effectiveDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.EFFECTIVE_DATE
	 * 
	 * @param effectiveDate the value for MFC_APPLICATION_INFO.EFFECTIVE_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.EFFECTIVE_END_DATE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.EFFECTIVE_END_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getEffectiveEndDate() {
		return effectiveEndDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.EFFECTIVE_END_DATE
	 * 
	 * @param effectiveEndDate the value for MFC_APPLICATION_INFO.EFFECTIVE_END_DATE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setEffectiveEndDate(Date effectiveEndDate) {
		this.effectiveEndDate = effectiveEndDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_PROVINCE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.PRESENT_ADDRESS_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getPresentAddressProvince() {
		return presentAddressProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_PROVINCE
	 * 
	 * @param presentAddressProvince the value for MFC_APPLICATION_INFO.PRESENT_ADDRESS_PROVINCE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setPresentAddressProvince(Long presentAddressProvince) {
		this.presentAddressProvince = presentAddressProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_CITY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.PRESENT_ADDRESS_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getPresentAddressCity() {
		return presentAddressCity;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_CITY
	 * 
	 * @param presentAddressCity the value for MFC_APPLICATION_INFO.PRESENT_ADDRESS_CITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setPresentAddressCity(Long presentAddressCity) {
		this.presentAddressCity = presentAddressCity;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_AREA
	 * 
	 * @return the value of MFC_APPLICATION_INFO.PRESENT_ADDRESS_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Long getPresentAddressArea() {
		return presentAddressArea;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_AREA
	 * 
	 * @param presentAddressArea the value for MFC_APPLICATION_INFO.PRESENT_ADDRESS_AREA
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setPresentAddressArea(Long presentAddressArea) {
		this.presentAddressArea = presentAddressArea;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_DETAIL
	 * 
	 * @return the value of MFC_APPLICATION_INFO.PRESENT_ADDRESS_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getPresentAddressDetail() {
		return presentAddressDetail;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.PRESENT_ADDRESS_DETAIL
	 * 
	 * @param presentAddressDetail the value for MFC_APPLICATION_INFO.PRESENT_ADDRESS_DETAIL
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setPresentAddressDetail(String presentAddressDetail) {
		this.presentAddressDetail = presentAddressDetail == null ? null : presentAddressDetail.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO_FAX
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO_FAX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getAppInfoFax() {
		return appInfoFax;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO_FAX
	 * 
	 * @param appInfoFax the value for MFC_APPLICATION_INFO.APP_INFO_FAX
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoFax(String appInfoFax) {
		this.appInfoFax = appInfoFax == null ? null : appInfoFax.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.LOCAL_LIVE_YEAR
	 * 
	 * @return the value of MFC_APPLICATION_INFO.LOCAL_LIVE_YEAR
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getLocalLiveYear() {
		return localLiveYear;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.LOCAL_LIVE_YEAR
	 * 
	 * @param localLiveYear the value for MFC_APPLICATION_INFO.LOCAL_LIVE_YEAR
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setLocalLiveYear(String localLiveYear) {
		this.localLiveYear = localLiveYear == null ? null : localLiveYear.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.LOCAL_LIVE_MONTH
	 * 
	 * @return the value of MFC_APPLICATION_INFO.LOCAL_LIVE_MONTH
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getLocalLiveMonth() {
		return localLiveMonth;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.LOCAL_LIVE_MONTH
	 * 
	 * @param localLiveMonth the value for MFC_APPLICATION_INFO.LOCAL_LIVE_MONTH
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setLocalLiveMonth(String localLiveMonth) {
		this.localLiveMonth = localLiveMonth == null ? null : localLiveMonth.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO__MOBILE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO__MOBILE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getAppInfoMobile() {
		return appInfoMobile;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO__MOBILE
	 * 
	 * @param appInfoMobile the value for MFC_APPLICATION_INFO.APP_INFO__MOBILE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoMobile(String appInfoMobile) {
		this.appInfoMobile = appInfoMobile == null ? null : appInfoMobile.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APP_INFO__TELEPHONE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APP_INFO__TELEPHONE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getAppInfoTelephone() {
		return appInfoTelephone;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APP_INFO__TELEPHONE
	 * 
	 * @param appInfoTelephone the value for MFC_APPLICATION_INFO.APP_INFO__TELEPHONE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAppInfoTelephone(String appInfoTelephone) {
		this.appInfoTelephone = appInfoTelephone == null ? null : appInfoTelephone.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.MARITAL_STATUS
	 * 
	 * @return the value of MFC_APPLICATION_INFO.MARITAL_STATUS
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getMaritalStatus() {
		return maritalStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.MARITAL_STATUS
	 * 
	 * @param maritalStatus the value for MFC_APPLICATION_INFO.MARITAL_STATUS
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.MARITAL_STATUS_EXPLAIN
	 * 
	 * @return the value of MFC_APPLICATION_INFO.MARITAL_STATUS_EXPLAIN
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getMaritalStatusExplain() {
		return maritalStatusExplain;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.MARITAL_STATUS_EXPLAIN
	 * 
	 * @param maritalStatusExplain the value for MFC_APPLICATION_INFO.MARITAL_STATUS_EXPLAIN
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setMaritalStatusExplain(String maritalStatusExplain) {
		this.maritalStatusExplain = maritalStatusExplain == null ? null : maritalStatusExplain.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.LIVE_QUATITY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.LIVE_QUATITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getLiveQuatity() {
		return liveQuatity;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.LIVE_QUATITY
	 * 
	 * @param liveQuatity the value for MFC_APPLICATION_INFO.LIVE_QUATITY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setLiveQuatity(String liveQuatity) {
		this.liveQuatity = liveQuatity == null ? null : liveQuatity.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.FAMILY_REVENUE
	 * 
	 * @return the value of MFC_APPLICATION_INFO.FAMILY_REVENUE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public BigDecimal getFamilyRevenue() {
		return familyRevenue;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.FAMILY_REVENUE
	 * 
	 * @param familyRevenue the value for MFC_APPLICATION_INFO.FAMILY_REVENUE
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setFamilyRevenue(BigDecimal familyRevenue) {
		this.familyRevenue = familyRevenue;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.AVG_MONTH_PAY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.AVG_MONTH_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public BigDecimal getAvgMonthPay() {
		return avgMonthPay;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.AVG_MONTH_PAY
	 * 
	 * @param avgMonthPay the value for MFC_APPLICATION_INFO.AVG_MONTH_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setAvgMonthPay(BigDecimal avgMonthPay) {
		this.avgMonthPay = avgMonthPay;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.OTHER_PAY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.OTHER_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public BigDecimal getOtherPay() {
		return otherPay;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.OTHER_PAY
	 * 
	 * @param otherPay the value for MFC_APPLICATION_INFO.OTHER_PAY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setOtherPay(BigDecimal otherPay) {
		this.otherPay = otherPay;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.REPAYMENT
	 * 
	 * @return the value of MFC_APPLICATION_INFO.REPAYMENT
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public BigDecimal getRepayment() {
		return repayment;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.REPAYMENT
	 * 
	 * @param repayment the value for MFC_APPLICATION_INFO.REPAYMENT
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setRepayment(BigDecimal repayment) {
		this.repayment = repayment;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.APPLICATION_WORK_HISTORY
	 * 
	 * @return the value of MFC_APPLICATION_INFO.APPLICATION_WORK_HISTORY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public String getApplicationWorkHistory() {
		return applicationWorkHistory;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.APPLICATION_WORK_HISTORY
	 * 
	 * @param applicationWorkHistory the value for MFC_APPLICATION_INFO.APPLICATION_WORK_HISTORY
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setApplicationWorkHistory(String applicationWorkHistory) {
		this.applicationWorkHistory = applicationWorkHistory == null ? null : applicationWorkHistory.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_APPLICATION_INFO.HISTORYFLAG
	 * 
	 * @return the value of MFC_APPLICATION_INFO.HISTORYFLAG
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public Short getHistoryflag() {
		return historyflag;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_APPLICATION_INFO.HISTORYFLAG
	 * 
	 * @param historyflag the value for MFC_APPLICATION_INFO.HISTORYFLAG
	 * 
	 * @abatorgenerated Tue Jul 09 14:35:17 CST 2013
	 */
	public void setHistoryflag(Short historyflag) {
		this.historyflag = historyflag;
	}

	private String shopName;
	private String sort;
	private String order;
	private int appCount;
	private Long applyLimit;
	private String projectName;
	private String applicationStatus;
	private Date applicationDate;
	private String teamDepartmentName;
	private String receptionistName;

	private String comName;
	private String sqlSid;
	
	//业务状态
	private String auditStatusShow;
	
	

	public String getAuditStatusShow() {
		return auditStatusShow;
	}

	public void setAuditStatusShow(String auditStatusShow) {
		this.auditStatusShow = auditStatusShow;
	}

	public String getSqlSid() {
		return sqlSid;
	}

	public void setSqlSid(String sqlSid) {
		this.sqlSid = sqlSid;
	}

	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getApplicationDate() {
		return applicationDate;
	}

	public void setApplicationDate(Date applicationDate) {
		this.applicationDate = applicationDate;
	}

	public String getTeamDepartmentName() {
		return teamDepartmentName;
	}

	public void setTeamDepartmentName(String teamDepartmentName) {
		this.teamDepartmentName = teamDepartmentName;
	}

	public String getReceptionistName() {
		return receptionistName;
	}

	public void setReceptionistName(String receptionistName) {
		this.receptionistName = receptionistName;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getApplicationStatus() {
		return applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	public Long getApplyLimit() {
		return applyLimit;
	}

	public void setApplyLimit(Long applyLimit) {
		this.applyLimit = applyLimit;
	}

	public int getAppCount() {
		return appCount;
	}

	public void setAppCount(int appCount) {
		this.appCount = appCount;
	}

	public String getSort() {
		return sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	public String getOrder() {
		return order;
	}

	public void setOrder(String order) {
		this.order = order;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	private String applyProductName;

	public String getApplyProductName() {
		return applyProductName;
	}

	public void setApplyProductName(String applyProductName) {
		this.applyProductName = applyProductName;
	}

	private String isRegular;

	public String getIsRegular() {
		return isRegular;
	}

	public void setIsRegular(String isRegular) {
		this.isRegular = isRegular;
	}

	private String proceedName;

	public String getProceedName() {
		return proceedName;
	}

	public void setProceedName(String proceedName) {
		this.proceedName = proceedName;
	}

	private Date optDate;

	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getOptDate() {
		return optDate;
	}

	public void setOptDate(Date optDate) {
		this.optDate = optDate;
	}

}