package com.creditease.rc.vo;

import java.util.Date;

public class PersonArrested {
	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.PERSON_ARRESTED_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private Long personArrestedId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private Long applicationId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.NAME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String name;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.CODE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String code;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.COURT
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String court;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String time;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.CASE_NUMBER
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String caseNumber;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.MONEY
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String money;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.STATE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String state;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.TIMES
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private String times;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column MFC_PERSON_ARRESTED.CREATE_TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	private Date createTime;

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.PERSON_ARRESTED_ID
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.PERSON_ARRESTED_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public Long getPersonArrestedId() {
		return personArrestedId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.PERSON_ARRESTED_ID
	 * 
	 * @param personArrestedId the value for MFC_PERSON_ARRESTED.PERSON_ARRESTED_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setPersonArrestedId(Long personArrestedId) {
		this.personArrestedId = personArrestedId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.APPLICATION_ID
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public Long getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.APPLICATION_ID
	 * 
	 * @param applicationId the value for MFC_PERSON_ARRESTED.APPLICATION_ID
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setApplicationId(Long applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.NAME
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.NAME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.NAME
	 * 
	 * @param name the value for MFC_PERSON_ARRESTED.NAME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.CODE
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.CODE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.CODE
	 * 
	 * @param code the value for MFC_PERSON_ARRESTED.CODE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.COURT
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.COURT
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getCourt() {
		return court;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.COURT
	 * 
	 * @param court the value for MFC_PERSON_ARRESTED.COURT
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setCourt(String court) {
		this.court = court == null ? null : court.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.TIME
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.TIME
	 * 
	 * @param time the value for MFC_PERSON_ARRESTED.TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setTime(String time) {
		this.time = time == null ? null : time.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.CASE_NUMBER
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.CASE_NUMBER
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getCaseNumber() {
		return caseNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.CASE_NUMBER
	 * 
	 * @param caseNumber the value for MFC_PERSON_ARRESTED.CASE_NUMBER
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setCaseNumber(String caseNumber) {
		this.caseNumber = caseNumber == null ? null : caseNumber.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.MONEY
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.MONEY
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.MONEY
	 * 
	 * @param money the value for MFC_PERSON_ARRESTED.MONEY
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setMoney(String money) {
		this.money = money == null ? null : money.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.STATE
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.STATE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.STATE
	 * 
	 * @param state the value for MFC_PERSON_ARRESTED.STATE
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.TIMES
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.TIMES
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public String getTimes() {
		return times;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.TIMES
	 * 
	 * @param times the value for MFC_PERSON_ARRESTED.TIMES
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setTimes(String times) {
		this.times = times == null ? null : times.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column MFC_PERSON_ARRESTED.CREATE_TIME
	 * 
	 * @return the value of MFC_PERSON_ARRESTED.CREATE_TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column MFC_PERSON_ARRESTED.CREATE_TIME
	 * 
	 * @param createTime the value for MFC_PERSON_ARRESTED.CREATE_TIME
	 * 
	 * @abatorgenerated Tue Jul 09 19:02:34 CST 2013
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	private String isManual;

	public String getIsManual() {
		return isManual;
	}

	public void setIsManual(String isManual) {
		this.isManual = isManual;
	}
}