package com.creditease.rc.app.sia.vo;

import java.math.BigDecimal;
import java.util.Date;

public class BorrowerCompany extends BorrowerCompanyKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_NAME
	 * @abatorgenerated
	 */
	private String registerName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_CAPITAL
	 * @abatorgenerated
	 */
	private BigDecimal registerCapital;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_DATE
	 * @abatorgenerated
	 */
	private Date registerDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.ESTABLISH_DATE
	 * @abatorgenerated
	 */
	private Date establishDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.STAFF_NUM
	 * @abatorgenerated
	 */
	private Integer staffNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.CUSTOMER_IDENT_TYPE
	 * @abatorgenerated
	 */
	private String customerIdentType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REMARK
	 * @abatorgenerated
	 */
	private String remark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.LEGAL_REPRESENTATIVE
	 * @abatorgenerated
	 */
	private String legalRepresentative;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.ANNUAL_SURVEIED
	 * @abatorgenerated
	 */
	private String annualSurveied;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.CONTENT_TYPE
	 * @abatorgenerated
	 */
	private String contentType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.PORTION
	 * @abatorgenerated
	 */
	private BigDecimal portion;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.RELATIONSHIP
	 * @abatorgenerated
	 */
	private String relationship;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TRADE
	 * @abatorgenerated
	 */
	private String trade;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TRADE2
	 * @abatorgenerated
	 */
	private String trade2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_PROVINCE
	 * @abatorgenerated
	 */
	private String registerProvince;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_CITY
	 * @abatorgenerated
	 */
	private String registerCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_AREA
	 * @abatorgenerated
	 */
	private String registerArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.REGISTER_ADDRESS
	 * @abatorgenerated
	 */
	private String registerAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.ORGANIZATION_CODE
	 * @abatorgenerated
	 */
	private String organizationCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.COMPANY_HOUSE_TYPE
	 * @abatorgenerated
	 */
	private String companyHouseType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.MAIN_BUSINESS
	 * @abatorgenerated
	 */
	private String mainBusiness;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS_TYPE
	 * @abatorgenerated
	 */
	private String operateAddressType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.OPERATE_PLACE_AREA
	 * @abatorgenerated
	 */
	private BigDecimal operatePlaceArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.ALREADY_USE_YEARS
	 * @abatorgenerated
	 */
	private BigDecimal alreadyUseYears;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.PROVINCE
	 * @abatorgenerated
	 */
	private String province;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.CITY
	 * @abatorgenerated
	 */
	private String city;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.AREA
	 * @abatorgenerated
	 */
	private String area;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS
	 * @abatorgenerated
	 */
	private String operateAddress;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.WORK_TYPE
	 * @abatorgenerated
	 */
	private String workType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.WORK_NATURE
	 * @abatorgenerated
	 */
	private String workNature;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_TRADE
	 * @abatorgenerated
	 */
	private String businessTrade;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.WORK_PHONE
	 * @abatorgenerated
	 */
	private String workPhone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT1
	 * @abatorgenerated
	 */
	private String businessContent1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT2
	 * @abatorgenerated
	 */
	private String businessContent2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT3
	 * @abatorgenerated
	 */
	private String businessContent3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT_DETAIL
	 * @abatorgenerated
	 */
	private String businessContentDetail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.START_YEAR
	 * @abatorgenerated
	 */
	private Short startYear;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_YEAR
	 * @abatorgenerated
	 */
	private BigDecimal businessYear;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.MONTH_INCOME
	 * @abatorgenerated
	 */
	private BigDecimal monthIncome;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.MONTH_NET_INCOME
	 * @abatorgenerated
	 */
	private BigDecimal monthNetIncome;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.LICENCE_TYPE
	 * @abatorgenerated
	 */
	private String licenceType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_START_TIME
	 * @abatorgenerated
	 */
	private Date businessStartTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TAX_REGISTER_NO
	 * @abatorgenerated
	 */
	private String taxRegisterNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.BUSINESS_STATE
	 * @abatorgenerated
	 */
	private String businessState;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.SHOP_NAME
	 * @abatorgenerated
	 */
	private String shopName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TENANTRY
	 * @abatorgenerated
	 */
	private String tenantry;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.LANDLORD
	 * @abatorgenerated
	 */
	private String landlord;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.RENT_TERM
	 * @abatorgenerated
	 */
	private BigDecimal rentTerm;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.YEAR_RENT
	 * @abatorgenerated
	 */
	private BigDecimal yearRent;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.AVERAGE_SALE_AMOUNT
	 * @abatorgenerated
	 */
	private BigDecimal averageSaleAmount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.YEAR_NET_PROFIT
	 * @abatorgenerated
	 */
	private BigDecimal yearNetProfit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TURNOVER_CAPITAL
	 * @abatorgenerated
	 */
	private BigDecimal turnoverCapital;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.INVENTORY
	 * @abatorgenerated
	 */
	private BigDecimal inventory;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.TRAFICC
	 * @abatorgenerated
	 */
	private String traficc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.RECIEVE_AMOUNT
	 * @abatorgenerated
	 */
	private BigDecimal recieveAmount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.PAYABLE_AMOUNT
	 * @abatorgenerated
	 */
	private BigDecimal payableAmount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.NOPAY_SALARY
	 * @abatorgenerated
	 */
	private BigDecimal nopaySalary;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.LOAN_BALANCE
	 * @abatorgenerated
	 */
	private BigDecimal loanBalance;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.OTHER_DEBIT
	 * @abatorgenerated
	 */
	private BigDecimal otherDebit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.ASSET_TOTAL_BALANCE
	 * @abatorgenerated
	 */
	private BigDecimal assetTotalBalance;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.CREATER
	 * @abatorgenerated
	 */
	private Long creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	private Long updaterPeople;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.UPDATE_DATE
	 * @abatorgenerated
	 */
	private Date updateDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_COMPANY.CREATE_DATE
	 * @abatorgenerated
	 */
	private Date createDate;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_NAME
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_NAME
	 * @abatorgenerated
	 */
	public String getRegisterName() {
		return registerName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_NAME
	 * @param registerName  the value for ICP_BORROWER_COMPANY.REGISTER_NAME
	 * @abatorgenerated
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName == null ? null : registerName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_CAPITAL
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_CAPITAL
	 * @abatorgenerated
	 */
	public BigDecimal getRegisterCapital() {
		return registerCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_CAPITAL
	 * @param registerCapital  the value for ICP_BORROWER_COMPANY.REGISTER_CAPITAL
	 * @abatorgenerated
	 */
	public void setRegisterCapital(BigDecimal registerCapital) {
		this.registerCapital = registerCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_DATE
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_DATE
	 * @abatorgenerated
	 */
	public Date getRegisterDate() {
		return registerDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_DATE
	 * @param registerDate  the value for ICP_BORROWER_COMPANY.REGISTER_DATE
	 * @abatorgenerated
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.ESTABLISH_DATE
	 * @return  the value of ICP_BORROWER_COMPANY.ESTABLISH_DATE
	 * @abatorgenerated
	 */
	public Date getEstablishDate() {
		return establishDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.ESTABLISH_DATE
	 * @param establishDate  the value for ICP_BORROWER_COMPANY.ESTABLISH_DATE
	 * @abatorgenerated
	 */
	public void setEstablishDate(Date establishDate) {
		this.establishDate = establishDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.STAFF_NUM
	 * @return  the value of ICP_BORROWER_COMPANY.STAFF_NUM
	 * @abatorgenerated
	 */
	public Integer getStaffNum() {
		return staffNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.STAFF_NUM
	 * @param staffNum  the value for ICP_BORROWER_COMPANY.STAFF_NUM
	 * @abatorgenerated
	 */
	public void setStaffNum(Integer staffNum) {
		this.staffNum = staffNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.CUSTOMER_IDENT_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.CUSTOMER_IDENT_TYPE
	 * @abatorgenerated
	 */
	public String getCustomerIdentType() {
		return customerIdentType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.CUSTOMER_IDENT_TYPE
	 * @param customerIdentType  the value for ICP_BORROWER_COMPANY.CUSTOMER_IDENT_TYPE
	 * @abatorgenerated
	 */
	public void setCustomerIdentType(String customerIdentType) {
		this.customerIdentType = customerIdentType == null ? null
				: customerIdentType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REMARK
	 * @return  the value of ICP_BORROWER_COMPANY.REMARK
	 * @abatorgenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REMARK
	 * @param remark  the value for ICP_BORROWER_COMPANY.REMARK
	 * @abatorgenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.LEGAL_REPRESENTATIVE
	 * @return  the value of ICP_BORROWER_COMPANY.LEGAL_REPRESENTATIVE
	 * @abatorgenerated
	 */
	public String getLegalRepresentative() {
		return legalRepresentative;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.LEGAL_REPRESENTATIVE
	 * @param legalRepresentative  the value for ICP_BORROWER_COMPANY.LEGAL_REPRESENTATIVE
	 * @abatorgenerated
	 */
	public void setLegalRepresentative(String legalRepresentative) {
		this.legalRepresentative = legalRepresentative == null ? null
				: legalRepresentative.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.ANNUAL_SURVEIED
	 * @return  the value of ICP_BORROWER_COMPANY.ANNUAL_SURVEIED
	 * @abatorgenerated
	 */
	public String getAnnualSurveied() {
		return annualSurveied;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.ANNUAL_SURVEIED
	 * @param annualSurveied  the value for ICP_BORROWER_COMPANY.ANNUAL_SURVEIED
	 * @abatorgenerated
	 */
	public void setAnnualSurveied(String annualSurveied) {
		this.annualSurveied = annualSurveied == null ? null : annualSurveied
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.CONTENT_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.CONTENT_TYPE
	 * @abatorgenerated
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.CONTENT_TYPE
	 * @param contentType  the value for ICP_BORROWER_COMPANY.CONTENT_TYPE
	 * @abatorgenerated
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType == null ? null : contentType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.PORTION
	 * @return  the value of ICP_BORROWER_COMPANY.PORTION
	 * @abatorgenerated
	 */
	public BigDecimal getPortion() {
		return portion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.PORTION
	 * @param portion  the value for ICP_BORROWER_COMPANY.PORTION
	 * @abatorgenerated
	 */
	public void setPortion(BigDecimal portion) {
		this.portion = portion;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.RELATIONSHIP
	 * @return  the value of ICP_BORROWER_COMPANY.RELATIONSHIP
	 * @abatorgenerated
	 */
	public String getRelationship() {
		return relationship;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.RELATIONSHIP
	 * @param relationship  the value for ICP_BORROWER_COMPANY.RELATIONSHIP
	 * @abatorgenerated
	 */
	public void setRelationship(String relationship) {
		this.relationship = relationship == null ? null : relationship.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TRADE
	 * @return  the value of ICP_BORROWER_COMPANY.TRADE
	 * @abatorgenerated
	 */
	public String getTrade() {
		return trade;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TRADE
	 * @param trade  the value for ICP_BORROWER_COMPANY.TRADE
	 * @abatorgenerated
	 */
	public void setTrade(String trade) {
		this.trade = trade == null ? null : trade.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TRADE2
	 * @return  the value of ICP_BORROWER_COMPANY.TRADE2
	 * @abatorgenerated
	 */
	public String getTrade2() {
		return trade2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TRADE2
	 * @param trade2  the value for ICP_BORROWER_COMPANY.TRADE2
	 * @abatorgenerated
	 */
	public void setTrade2(String trade2) {
		this.trade2 = trade2 == null ? null : trade2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_PROVINCE
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_PROVINCE
	 * @abatorgenerated
	 */
	public String getRegisterProvince() {
		return registerProvince;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_PROVINCE
	 * @param registerProvince  the value for ICP_BORROWER_COMPANY.REGISTER_PROVINCE
	 * @abatorgenerated
	 */
	public void setRegisterProvince(String registerProvince) {
		this.registerProvince = registerProvince == null ? null
				: registerProvince.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_CITY
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_CITY
	 * @abatorgenerated
	 */
	public String getRegisterCity() {
		return registerCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_CITY
	 * @param registerCity  the value for ICP_BORROWER_COMPANY.REGISTER_CITY
	 * @abatorgenerated
	 */
	public void setRegisterCity(String registerCity) {
		this.registerCity = registerCity == null ? null : registerCity.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_AREA
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_AREA
	 * @abatorgenerated
	 */
	public String getRegisterArea() {
		return registerArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_AREA
	 * @param registerArea  the value for ICP_BORROWER_COMPANY.REGISTER_AREA
	 * @abatorgenerated
	 */
	public void setRegisterArea(String registerArea) {
		this.registerArea = registerArea == null ? null : registerArea.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.REGISTER_ADDRESS
	 * @return  the value of ICP_BORROWER_COMPANY.REGISTER_ADDRESS
	 * @abatorgenerated
	 */
	public String getRegisterAddress() {
		return registerAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.REGISTER_ADDRESS
	 * @param registerAddress  the value for ICP_BORROWER_COMPANY.REGISTER_ADDRESS
	 * @abatorgenerated
	 */
	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress == null ? null : registerAddress
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.ORGANIZATION_CODE
	 * @return  the value of ICP_BORROWER_COMPANY.ORGANIZATION_CODE
	 * @abatorgenerated
	 */
	public String getOrganizationCode() {
		return organizationCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.ORGANIZATION_CODE
	 * @param organizationCode  the value for ICP_BORROWER_COMPANY.ORGANIZATION_CODE
	 * @abatorgenerated
	 */
	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode == null ? null
				: organizationCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.COMPANY_HOUSE_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.COMPANY_HOUSE_TYPE
	 * @abatorgenerated
	 */
	public String getCompanyHouseType() {
		return companyHouseType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.COMPANY_HOUSE_TYPE
	 * @param companyHouseType  the value for ICP_BORROWER_COMPANY.COMPANY_HOUSE_TYPE
	 * @abatorgenerated
	 */
	public void setCompanyHouseType(String companyHouseType) {
		this.companyHouseType = companyHouseType == null ? null
				: companyHouseType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.MAIN_BUSINESS
	 * @return  the value of ICP_BORROWER_COMPANY.MAIN_BUSINESS
	 * @abatorgenerated
	 */
	public String getMainBusiness() {
		return mainBusiness;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.MAIN_BUSINESS
	 * @param mainBusiness  the value for ICP_BORROWER_COMPANY.MAIN_BUSINESS
	 * @abatorgenerated
	 */
	public void setMainBusiness(String mainBusiness) {
		this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.OPERATE_ADDRESS_TYPE
	 * @abatorgenerated
	 */
	public String getOperateAddressType() {
		return operateAddressType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS_TYPE
	 * @param operateAddressType  the value for ICP_BORROWER_COMPANY.OPERATE_ADDRESS_TYPE
	 * @abatorgenerated
	 */
	public void setOperateAddressType(String operateAddressType) {
		this.operateAddressType = operateAddressType == null ? null
				: operateAddressType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.OPERATE_PLACE_AREA
	 * @return  the value of ICP_BORROWER_COMPANY.OPERATE_PLACE_AREA
	 * @abatorgenerated
	 */
	public BigDecimal getOperatePlaceArea() {
		return operatePlaceArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.OPERATE_PLACE_AREA
	 * @param operatePlaceArea  the value for ICP_BORROWER_COMPANY.OPERATE_PLACE_AREA
	 * @abatorgenerated
	 */
	public void setOperatePlaceArea(BigDecimal operatePlaceArea) {
		this.operatePlaceArea = operatePlaceArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.ALREADY_USE_YEARS
	 * @return  the value of ICP_BORROWER_COMPANY.ALREADY_USE_YEARS
	 * @abatorgenerated
	 */
	public BigDecimal getAlreadyUseYears() {
		return alreadyUseYears;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.ALREADY_USE_YEARS
	 * @param alreadyUseYears  the value for ICP_BORROWER_COMPANY.ALREADY_USE_YEARS
	 * @abatorgenerated
	 */
	public void setAlreadyUseYears(BigDecimal alreadyUseYears) {
		this.alreadyUseYears = alreadyUseYears;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.PROVINCE
	 * @return  the value of ICP_BORROWER_COMPANY.PROVINCE
	 * @abatorgenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.PROVINCE
	 * @param province  the value for ICP_BORROWER_COMPANY.PROVINCE
	 * @abatorgenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.CITY
	 * @return  the value of ICP_BORROWER_COMPANY.CITY
	 * @abatorgenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.CITY
	 * @param city  the value for ICP_BORROWER_COMPANY.CITY
	 * @abatorgenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.AREA
	 * @return  the value of ICP_BORROWER_COMPANY.AREA
	 * @abatorgenerated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.AREA
	 * @param area  the value for ICP_BORROWER_COMPANY.AREA
	 * @abatorgenerated
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS
	 * @return  the value of ICP_BORROWER_COMPANY.OPERATE_ADDRESS
	 * @abatorgenerated
	 */
	public String getOperateAddress() {
		return operateAddress;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.OPERATE_ADDRESS
	 * @param operateAddress  the value for ICP_BORROWER_COMPANY.OPERATE_ADDRESS
	 * @abatorgenerated
	 */
	public void setOperateAddress(String operateAddress) {
		this.operateAddress = operateAddress == null ? null : operateAddress
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.WORK_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.WORK_TYPE
	 * @abatorgenerated
	 */
	public String getWorkType() {
		return workType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.WORK_TYPE
	 * @param workType  the value for ICP_BORROWER_COMPANY.WORK_TYPE
	 * @abatorgenerated
	 */
	public void setWorkType(String workType) {
		this.workType = workType == null ? null : workType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.WORK_NATURE
	 * @return  the value of ICP_BORROWER_COMPANY.WORK_NATURE
	 * @abatorgenerated
	 */
	public String getWorkNature() {
		return workNature;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.WORK_NATURE
	 * @param workNature  the value for ICP_BORROWER_COMPANY.WORK_NATURE
	 * @abatorgenerated
	 */
	public void setWorkNature(String workNature) {
		this.workNature = workNature == null ? null : workNature.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_TRADE
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_TRADE
	 * @abatorgenerated
	 */
	public String getBusinessTrade() {
		return businessTrade;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_TRADE
	 * @param businessTrade  the value for ICP_BORROWER_COMPANY.BUSINESS_TRADE
	 * @abatorgenerated
	 */
	public void setBusinessTrade(String businessTrade) {
		this.businessTrade = businessTrade == null ? null : businessTrade
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.WORK_PHONE
	 * @return  the value of ICP_BORROWER_COMPANY.WORK_PHONE
	 * @abatorgenerated
	 */
	public String getWorkPhone() {
		return workPhone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.WORK_PHONE
	 * @param workPhone  the value for ICP_BORROWER_COMPANY.WORK_PHONE
	 * @abatorgenerated
	 */
	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone == null ? null : workPhone.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT1
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_CONTENT1
	 * @abatorgenerated
	 */
	public String getBusinessContent1() {
		return businessContent1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT1
	 * @param businessContent1  the value for ICP_BORROWER_COMPANY.BUSINESS_CONTENT1
	 * @abatorgenerated
	 */
	public void setBusinessContent1(String businessContent1) {
		this.businessContent1 = businessContent1 == null ? null
				: businessContent1.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT2
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_CONTENT2
	 * @abatorgenerated
	 */
	public String getBusinessContent2() {
		return businessContent2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT2
	 * @param businessContent2  the value for ICP_BORROWER_COMPANY.BUSINESS_CONTENT2
	 * @abatorgenerated
	 */
	public void setBusinessContent2(String businessContent2) {
		this.businessContent2 = businessContent2 == null ? null
				: businessContent2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT3
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_CONTENT3
	 * @abatorgenerated
	 */
	public String getBusinessContent3() {
		return businessContent3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT3
	 * @param businessContent3  the value for ICP_BORROWER_COMPANY.BUSINESS_CONTENT3
	 * @abatorgenerated
	 */
	public void setBusinessContent3(String businessContent3) {
		this.businessContent3 = businessContent3 == null ? null
				: businessContent3.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT_DETAIL
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_CONTENT_DETAIL
	 * @abatorgenerated
	 */
	public String getBusinessContentDetail() {
		return businessContentDetail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_CONTENT_DETAIL
	 * @param businessContentDetail  the value for ICP_BORROWER_COMPANY.BUSINESS_CONTENT_DETAIL
	 * @abatorgenerated
	 */
	public void setBusinessContentDetail(String businessContentDetail) {
		this.businessContentDetail = businessContentDetail == null ? null
				: businessContentDetail.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.START_YEAR
	 * @return  the value of ICP_BORROWER_COMPANY.START_YEAR
	 * @abatorgenerated
	 */
	public Short getStartYear() {
		return startYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.START_YEAR
	 * @param startYear  the value for ICP_BORROWER_COMPANY.START_YEAR
	 * @abatorgenerated
	 */
	public void setStartYear(Short startYear) {
		this.startYear = startYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_YEAR
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_YEAR
	 * @abatorgenerated
	 */
	public BigDecimal getBusinessYear() {
		return businessYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_YEAR
	 * @param businessYear  the value for ICP_BORROWER_COMPANY.BUSINESS_YEAR
	 * @abatorgenerated
	 */
	public void setBusinessYear(BigDecimal businessYear) {
		this.businessYear = businessYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.MONTH_INCOME
	 * @return  the value of ICP_BORROWER_COMPANY.MONTH_INCOME
	 * @abatorgenerated
	 */
	public BigDecimal getMonthIncome() {
		return monthIncome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.MONTH_INCOME
	 * @param monthIncome  the value for ICP_BORROWER_COMPANY.MONTH_INCOME
	 * @abatorgenerated
	 */
	public void setMonthIncome(BigDecimal monthIncome) {
		this.monthIncome = monthIncome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.MONTH_NET_INCOME
	 * @return  the value of ICP_BORROWER_COMPANY.MONTH_NET_INCOME
	 * @abatorgenerated
	 */
	public BigDecimal getMonthNetIncome() {
		return monthNetIncome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.MONTH_NET_INCOME
	 * @param monthNetIncome  the value for ICP_BORROWER_COMPANY.MONTH_NET_INCOME
	 * @abatorgenerated
	 */
	public void setMonthNetIncome(BigDecimal monthNetIncome) {
		this.monthNetIncome = monthNetIncome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.LICENCE_TYPE
	 * @return  the value of ICP_BORROWER_COMPANY.LICENCE_TYPE
	 * @abatorgenerated
	 */
	public String getLicenceType() {
		return licenceType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.LICENCE_TYPE
	 * @param licenceType  the value for ICP_BORROWER_COMPANY.LICENCE_TYPE
	 * @abatorgenerated
	 */
	public void setLicenceType(String licenceType) {
		this.licenceType = licenceType == null ? null : licenceType.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_START_TIME
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_START_TIME
	 * @abatorgenerated
	 */
	public Date getBusinessStartTime() {
		return businessStartTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_START_TIME
	 * @param businessStartTime  the value for ICP_BORROWER_COMPANY.BUSINESS_START_TIME
	 * @abatorgenerated
	 */
	public void setBusinessStartTime(Date businessStartTime) {
		this.businessStartTime = businessStartTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TAX_REGISTER_NO
	 * @return  the value of ICP_BORROWER_COMPANY.TAX_REGISTER_NO
	 * @abatorgenerated
	 */
	public String getTaxRegisterNo() {
		return taxRegisterNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TAX_REGISTER_NO
	 * @param taxRegisterNo  the value for ICP_BORROWER_COMPANY.TAX_REGISTER_NO
	 * @abatorgenerated
	 */
	public void setTaxRegisterNo(String taxRegisterNo) {
		this.taxRegisterNo = taxRegisterNo == null ? null : taxRegisterNo
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.BUSINESS_STATE
	 * @return  the value of ICP_BORROWER_COMPANY.BUSINESS_STATE
	 * @abatorgenerated
	 */
	public String getBusinessState() {
		return businessState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.BUSINESS_STATE
	 * @param businessState  the value for ICP_BORROWER_COMPANY.BUSINESS_STATE
	 * @abatorgenerated
	 */
	public void setBusinessState(String businessState) {
		this.businessState = businessState == null ? null : businessState
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.SHOP_NAME
	 * @return  the value of ICP_BORROWER_COMPANY.SHOP_NAME
	 * @abatorgenerated
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.SHOP_NAME
	 * @param shopName  the value for ICP_BORROWER_COMPANY.SHOP_NAME
	 * @abatorgenerated
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TENANTRY
	 * @return  the value of ICP_BORROWER_COMPANY.TENANTRY
	 * @abatorgenerated
	 */
	public String getTenantry() {
		return tenantry;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TENANTRY
	 * @param tenantry  the value for ICP_BORROWER_COMPANY.TENANTRY
	 * @abatorgenerated
	 */
	public void setTenantry(String tenantry) {
		this.tenantry = tenantry == null ? null : tenantry.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.LANDLORD
	 * @return  the value of ICP_BORROWER_COMPANY.LANDLORD
	 * @abatorgenerated
	 */
	public String getLandlord() {
		return landlord;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.LANDLORD
	 * @param landlord  the value for ICP_BORROWER_COMPANY.LANDLORD
	 * @abatorgenerated
	 */
	public void setLandlord(String landlord) {
		this.landlord = landlord == null ? null : landlord.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.RENT_TERM
	 * @return  the value of ICP_BORROWER_COMPANY.RENT_TERM
	 * @abatorgenerated
	 */
	public BigDecimal getRentTerm() {
		return rentTerm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.RENT_TERM
	 * @param rentTerm  the value for ICP_BORROWER_COMPANY.RENT_TERM
	 * @abatorgenerated
	 */
	public void setRentTerm(BigDecimal rentTerm) {
		this.rentTerm = rentTerm;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.YEAR_RENT
	 * @return  the value of ICP_BORROWER_COMPANY.YEAR_RENT
	 * @abatorgenerated
	 */
	public BigDecimal getYearRent() {
		return yearRent;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.YEAR_RENT
	 * @param yearRent  the value for ICP_BORROWER_COMPANY.YEAR_RENT
	 * @abatorgenerated
	 */
	public void setYearRent(BigDecimal yearRent) {
		this.yearRent = yearRent;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.AVERAGE_SALE_AMOUNT
	 * @return  the value of ICP_BORROWER_COMPANY.AVERAGE_SALE_AMOUNT
	 * @abatorgenerated
	 */
	public BigDecimal getAverageSaleAmount() {
		return averageSaleAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.AVERAGE_SALE_AMOUNT
	 * @param averageSaleAmount  the value for ICP_BORROWER_COMPANY.AVERAGE_SALE_AMOUNT
	 * @abatorgenerated
	 */
	public void setAverageSaleAmount(BigDecimal averageSaleAmount) {
		this.averageSaleAmount = averageSaleAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.YEAR_NET_PROFIT
	 * @return  the value of ICP_BORROWER_COMPANY.YEAR_NET_PROFIT
	 * @abatorgenerated
	 */
	public BigDecimal getYearNetProfit() {
		return yearNetProfit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.YEAR_NET_PROFIT
	 * @param yearNetProfit  the value for ICP_BORROWER_COMPANY.YEAR_NET_PROFIT
	 * @abatorgenerated
	 */
	public void setYearNetProfit(BigDecimal yearNetProfit) {
		this.yearNetProfit = yearNetProfit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TURNOVER_CAPITAL
	 * @return  the value of ICP_BORROWER_COMPANY.TURNOVER_CAPITAL
	 * @abatorgenerated
	 */
	public BigDecimal getTurnoverCapital() {
		return turnoverCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TURNOVER_CAPITAL
	 * @param turnoverCapital  the value for ICP_BORROWER_COMPANY.TURNOVER_CAPITAL
	 * @abatorgenerated
	 */
	public void setTurnoverCapital(BigDecimal turnoverCapital) {
		this.turnoverCapital = turnoverCapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.INVENTORY
	 * @return  the value of ICP_BORROWER_COMPANY.INVENTORY
	 * @abatorgenerated
	 */
	public BigDecimal getInventory() {
		return inventory;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.INVENTORY
	 * @param inventory  the value for ICP_BORROWER_COMPANY.INVENTORY
	 * @abatorgenerated
	 */
	public void setInventory(BigDecimal inventory) {
		this.inventory = inventory;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.TRAFICC
	 * @return  the value of ICP_BORROWER_COMPANY.TRAFICC
	 * @abatorgenerated
	 */
	public String getTraficc() {
		return traficc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.TRAFICC
	 * @param traficc  the value for ICP_BORROWER_COMPANY.TRAFICC
	 * @abatorgenerated
	 */
	public void setTraficc(String traficc) {
		this.traficc = traficc == null ? null : traficc.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.RECIEVE_AMOUNT
	 * @return  the value of ICP_BORROWER_COMPANY.RECIEVE_AMOUNT
	 * @abatorgenerated
	 */
	public BigDecimal getRecieveAmount() {
		return recieveAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.RECIEVE_AMOUNT
	 * @param recieveAmount  the value for ICP_BORROWER_COMPANY.RECIEVE_AMOUNT
	 * @abatorgenerated
	 */
	public void setRecieveAmount(BigDecimal recieveAmount) {
		this.recieveAmount = recieveAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.PAYABLE_AMOUNT
	 * @return  the value of ICP_BORROWER_COMPANY.PAYABLE_AMOUNT
	 * @abatorgenerated
	 */
	public BigDecimal getPayableAmount() {
		return payableAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.PAYABLE_AMOUNT
	 * @param payableAmount  the value for ICP_BORROWER_COMPANY.PAYABLE_AMOUNT
	 * @abatorgenerated
	 */
	public void setPayableAmount(BigDecimal payableAmount) {
		this.payableAmount = payableAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.NOPAY_SALARY
	 * @return  the value of ICP_BORROWER_COMPANY.NOPAY_SALARY
	 * @abatorgenerated
	 */
	public BigDecimal getNopaySalary() {
		return nopaySalary;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.NOPAY_SALARY
	 * @param nopaySalary  the value for ICP_BORROWER_COMPANY.NOPAY_SALARY
	 * @abatorgenerated
	 */
	public void setNopaySalary(BigDecimal nopaySalary) {
		this.nopaySalary = nopaySalary;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.LOAN_BALANCE
	 * @return  the value of ICP_BORROWER_COMPANY.LOAN_BALANCE
	 * @abatorgenerated
	 */
	public BigDecimal getLoanBalance() {
		return loanBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.LOAN_BALANCE
	 * @param loanBalance  the value for ICP_BORROWER_COMPANY.LOAN_BALANCE
	 * @abatorgenerated
	 */
	public void setLoanBalance(BigDecimal loanBalance) {
		this.loanBalance = loanBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.OTHER_DEBIT
	 * @return  the value of ICP_BORROWER_COMPANY.OTHER_DEBIT
	 * @abatorgenerated
	 */
	public BigDecimal getOtherDebit() {
		return otherDebit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.OTHER_DEBIT
	 * @param otherDebit  the value for ICP_BORROWER_COMPANY.OTHER_DEBIT
	 * @abatorgenerated
	 */
	public void setOtherDebit(BigDecimal otherDebit) {
		this.otherDebit = otherDebit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.ASSET_TOTAL_BALANCE
	 * @return  the value of ICP_BORROWER_COMPANY.ASSET_TOTAL_BALANCE
	 * @abatorgenerated
	 */
	public BigDecimal getAssetTotalBalance() {
		return assetTotalBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.ASSET_TOTAL_BALANCE
	 * @param assetTotalBalance  the value for ICP_BORROWER_COMPANY.ASSET_TOTAL_BALANCE
	 * @abatorgenerated
	 */
	public void setAssetTotalBalance(BigDecimal assetTotalBalance) {
		this.assetTotalBalance = assetTotalBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.CREATER
	 * @return  the value of ICP_BORROWER_COMPANY.CREATER
	 * @abatorgenerated
	 */
	public Long getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.CREATER
	 * @param creater  the value for ICP_BORROWER_COMPANY.CREATER
	 * @abatorgenerated
	 */
	public void setCreater(Long creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.UPDATER_PEOPLE
	 * @return  the value of ICP_BORROWER_COMPANY.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	public Long getUpdaterPeople() {
		return updaterPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.UPDATER_PEOPLE
	 * @param updaterPeople  the value for ICP_BORROWER_COMPANY.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	public void setUpdaterPeople(Long updaterPeople) {
		this.updaterPeople = updaterPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.UPDATE_DATE
	 * @return  the value of ICP_BORROWER_COMPANY.UPDATE_DATE
	 * @abatorgenerated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.UPDATE_DATE
	 * @param updateDate  the value for ICP_BORROWER_COMPANY.UPDATE_DATE
	 * @abatorgenerated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_COMPANY.CREATE_DATE
	 * @return  the value of ICP_BORROWER_COMPANY.CREATE_DATE
	 * @abatorgenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_COMPANY.CREATE_DATE
	 * @param createDate  the value for ICP_BORROWER_COMPANY.CREATE_DATE
	 * @abatorgenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}