package com.creditease.rc.app.sia.vo;

public class BorrowerMachineKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_MACHINE.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	private Long borrowerInfoId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_MACHINE.MACHINE_ID
	 * @abatorgenerated
	 */
	private Long machineId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_MACHINE.BORROWER_INFO_ID
	 * @return  the value of ICP_BORROWER_MACHINE.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	public Long getBorrowerInfoId() {
		return borrowerInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_MACHINE.BORROWER_INFO_ID
	 * @param borrowerInfoId  the value for ICP_BORROWER_MACHINE.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	public void setBorrowerInfoId(Long borrowerInfoId) {
		this.borrowerInfoId = borrowerInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_MACHINE.MACHINE_ID
	 * @return  the value of ICP_BORROWER_MACHINE.MACHINE_ID
	 * @abatorgenerated
	 */
	public Long getMachineId() {
		return machineId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_MACHINE.MACHINE_ID
	 * @param machineId  the value for ICP_BORROWER_MACHINE.MACHINE_ID
	 * @abatorgenerated
	 */
	public void setMachineId(Long machineId) {
		this.machineId = machineId;
	}
}