package com.creditease.rc.app.sia.vo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BorrowerMachineExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public BorrowerMachineExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	protected BorrowerMachineExample(BorrowerMachineExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ICP_BORROWER_MACHINE
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andBorrowerInfoIdIsNull() {
			addCriterion("BORROWER_INFO_ID is null");
			return this;
		}

		public Criteria andBorrowerInfoIdIsNotNull() {
			addCriterion("BORROWER_INFO_ID is not null");
			return this;
		}

		public Criteria andBorrowerInfoIdEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID =", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <>", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThan(Long value) {
			addCriterion("BORROWER_INFO_ID >", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID >=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThan(Long value) {
			addCriterion("BORROWER_INFO_ID <", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdIn(List values) {
			addCriterion("BORROWER_INFO_ID in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotIn(List values) {
			addCriterion("BORROWER_INFO_ID not in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID not between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andMachineIdIsNull() {
			addCriterion("MACHINE_ID is null");
			return this;
		}

		public Criteria andMachineIdIsNotNull() {
			addCriterion("MACHINE_ID is not null");
			return this;
		}

		public Criteria andMachineIdEqualTo(Long value) {
			addCriterion("MACHINE_ID =", value, "machineId");
			return this;
		}

		public Criteria andMachineIdNotEqualTo(Long value) {
			addCriterion("MACHINE_ID <>", value, "machineId");
			return this;
		}

		public Criteria andMachineIdGreaterThan(Long value) {
			addCriterion("MACHINE_ID >", value, "machineId");
			return this;
		}

		public Criteria andMachineIdGreaterThanOrEqualTo(Long value) {
			addCriterion("MACHINE_ID >=", value, "machineId");
			return this;
		}

		public Criteria andMachineIdLessThan(Long value) {
			addCriterion("MACHINE_ID <", value, "machineId");
			return this;
		}

		public Criteria andMachineIdLessThanOrEqualTo(Long value) {
			addCriterion("MACHINE_ID <=", value, "machineId");
			return this;
		}

		public Criteria andMachineIdIn(List values) {
			addCriterion("MACHINE_ID in", values, "machineId");
			return this;
		}

		public Criteria andMachineIdNotIn(List values) {
			addCriterion("MACHINE_ID not in", values, "machineId");
			return this;
		}

		public Criteria andMachineIdBetween(Long value1, Long value2) {
			addCriterion("MACHINE_ID between", value1, value2, "machineId");
			return this;
		}

		public Criteria andMachineIdNotBetween(Long value1, Long value2) {
			addCriterion("MACHINE_ID not between", value1, value2, "machineId");
			return this;
		}

		public Criteria andMachineTypeIsNull() {
			addCriterion("MACHINE_TYPE is null");
			return this;
		}

		public Criteria andMachineTypeIsNotNull() {
			addCriterion("MACHINE_TYPE is not null");
			return this;
		}

		public Criteria andMachineTypeEqualTo(String value) {
			addCriterion("MACHINE_TYPE =", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeNotEqualTo(String value) {
			addCriterion("MACHINE_TYPE <>", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeGreaterThan(String value) {
			addCriterion("MACHINE_TYPE >", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeGreaterThanOrEqualTo(String value) {
			addCriterion("MACHINE_TYPE >=", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeLessThan(String value) {
			addCriterion("MACHINE_TYPE <", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeLessThanOrEqualTo(String value) {
			addCriterion("MACHINE_TYPE <=", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeLike(String value) {
			addCriterion("MACHINE_TYPE like", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeNotLike(String value) {
			addCriterion("MACHINE_TYPE not like", value, "machineType");
			return this;
		}

		public Criteria andMachineTypeIn(List values) {
			addCriterion("MACHINE_TYPE in", values, "machineType");
			return this;
		}

		public Criteria andMachineTypeNotIn(List values) {
			addCriterion("MACHINE_TYPE not in", values, "machineType");
			return this;
		}

		public Criteria andMachineTypeBetween(String value1, String value2) {
			addCriterion("MACHINE_TYPE between", value1, value2, "machineType");
			return this;
		}

		public Criteria andMachineTypeNotBetween(String value1, String value2) {
			addCriterion("MACHINE_TYPE not between", value1, value2,
					"machineType");
			return this;
		}

		public Criteria andBrandIsNull() {
			addCriterion("BRAND is null");
			return this;
		}

		public Criteria andBrandIsNotNull() {
			addCriterion("BRAND is not null");
			return this;
		}

		public Criteria andBrandEqualTo(String value) {
			addCriterion("BRAND =", value, "brand");
			return this;
		}

		public Criteria andBrandNotEqualTo(String value) {
			addCriterion("BRAND <>", value, "brand");
			return this;
		}

		public Criteria andBrandGreaterThan(String value) {
			addCriterion("BRAND >", value, "brand");
			return this;
		}

		public Criteria andBrandGreaterThanOrEqualTo(String value) {
			addCriterion("BRAND >=", value, "brand");
			return this;
		}

		public Criteria andBrandLessThan(String value) {
			addCriterion("BRAND <", value, "brand");
			return this;
		}

		public Criteria andBrandLessThanOrEqualTo(String value) {
			addCriterion("BRAND <=", value, "brand");
			return this;
		}

		public Criteria andBrandLike(String value) {
			addCriterion("BRAND like", value, "brand");
			return this;
		}

		public Criteria andBrandNotLike(String value) {
			addCriterion("BRAND not like", value, "brand");
			return this;
		}

		public Criteria andBrandIn(List values) {
			addCriterion("BRAND in", values, "brand");
			return this;
		}

		public Criteria andBrandNotIn(List values) {
			addCriterion("BRAND not in", values, "brand");
			return this;
		}

		public Criteria andBrandBetween(String value1, String value2) {
			addCriterion("BRAND between", value1, value2, "brand");
			return this;
		}

		public Criteria andBrandNotBetween(String value1, String value2) {
			addCriterion("BRAND not between", value1, value2, "brand");
			return this;
		}

		public Criteria andModelIsNull() {
			addCriterion("MODEL is null");
			return this;
		}

		public Criteria andModelIsNotNull() {
			addCriterion("MODEL is not null");
			return this;
		}

		public Criteria andModelEqualTo(String value) {
			addCriterion("MODEL =", value, "model");
			return this;
		}

		public Criteria andModelNotEqualTo(String value) {
			addCriterion("MODEL <>", value, "model");
			return this;
		}

		public Criteria andModelGreaterThan(String value) {
			addCriterion("MODEL >", value, "model");
			return this;
		}

		public Criteria andModelGreaterThanOrEqualTo(String value) {
			addCriterion("MODEL >=", value, "model");
			return this;
		}

		public Criteria andModelLessThan(String value) {
			addCriterion("MODEL <", value, "model");
			return this;
		}

		public Criteria andModelLessThanOrEqualTo(String value) {
			addCriterion("MODEL <=", value, "model");
			return this;
		}

		public Criteria andModelLike(String value) {
			addCriterion("MODEL like", value, "model");
			return this;
		}

		public Criteria andModelNotLike(String value) {
			addCriterion("MODEL not like", value, "model");
			return this;
		}

		public Criteria andModelIn(List values) {
			addCriterion("MODEL in", values, "model");
			return this;
		}

		public Criteria andModelNotIn(List values) {
			addCriterion("MODEL not in", values, "model");
			return this;
		}

		public Criteria andModelBetween(String value1, String value2) {
			addCriterion("MODEL between", value1, value2, "model");
			return this;
		}

		public Criteria andModelNotBetween(String value1, String value2) {
			addCriterion("MODEL not between", value1, value2, "model");
			return this;
		}

		public Criteria andIsMatachToolIsNull() {
			addCriterion("IS_MATACH_TOOL is null");
			return this;
		}

		public Criteria andIsMatachToolIsNotNull() {
			addCriterion("IS_MATACH_TOOL is not null");
			return this;
		}

		public Criteria andIsMatachToolEqualTo(String value) {
			addCriterion("IS_MATACH_TOOL =", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolNotEqualTo(String value) {
			addCriterion("IS_MATACH_TOOL <>", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolGreaterThan(String value) {
			addCriterion("IS_MATACH_TOOL >", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolGreaterThanOrEqualTo(String value) {
			addCriterion("IS_MATACH_TOOL >=", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolLessThan(String value) {
			addCriterion("IS_MATACH_TOOL <", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolLessThanOrEqualTo(String value) {
			addCriterion("IS_MATACH_TOOL <=", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolLike(String value) {
			addCriterion("IS_MATACH_TOOL like", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolNotLike(String value) {
			addCriterion("IS_MATACH_TOOL not like", value, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolIn(List values) {
			addCriterion("IS_MATACH_TOOL in", values, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolNotIn(List values) {
			addCriterion("IS_MATACH_TOOL not in", values, "isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolBetween(String value1, String value2) {
			addCriterion("IS_MATACH_TOOL between", value1, value2,
					"isMatachTool");
			return this;
		}

		public Criteria andIsMatachToolNotBetween(String value1, String value2) {
			addCriterion("IS_MATACH_TOOL not between", value1, value2,
					"isMatachTool");
			return this;
		}

		public Criteria andBuyWayIsNull() {
			addCriterion("BUY_WAY is null");
			return this;
		}

		public Criteria andBuyWayIsNotNull() {
			addCriterion("BUY_WAY is not null");
			return this;
		}

		public Criteria andBuyWayEqualTo(String value) {
			addCriterion("BUY_WAY =", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayNotEqualTo(String value) {
			addCriterion("BUY_WAY <>", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayGreaterThan(String value) {
			addCriterion("BUY_WAY >", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayGreaterThanOrEqualTo(String value) {
			addCriterion("BUY_WAY >=", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayLessThan(String value) {
			addCriterion("BUY_WAY <", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayLessThanOrEqualTo(String value) {
			addCriterion("BUY_WAY <=", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayLike(String value) {
			addCriterion("BUY_WAY like", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayNotLike(String value) {
			addCriterion("BUY_WAY not like", value, "buyWay");
			return this;
		}

		public Criteria andBuyWayIn(List values) {
			addCriterion("BUY_WAY in", values, "buyWay");
			return this;
		}

		public Criteria andBuyWayNotIn(List values) {
			addCriterion("BUY_WAY not in", values, "buyWay");
			return this;
		}

		public Criteria andBuyWayBetween(String value1, String value2) {
			addCriterion("BUY_WAY between", value1, value2, "buyWay");
			return this;
		}

		public Criteria andBuyWayNotBetween(String value1, String value2) {
			addCriterion("BUY_WAY not between", value1, value2, "buyWay");
			return this;
		}

		public Criteria andRentTypeIsNull() {
			addCriterion("RENT_TYPE is null");
			return this;
		}

		public Criteria andRentTypeIsNotNull() {
			addCriterion("RENT_TYPE is not null");
			return this;
		}

		public Criteria andRentTypeEqualTo(String value) {
			addCriterion("RENT_TYPE =", value, "rentType");
			return this;
		}

		public Criteria andRentTypeNotEqualTo(String value) {
			addCriterion("RENT_TYPE <>", value, "rentType");
			return this;
		}

		public Criteria andRentTypeGreaterThan(String value) {
			addCriterion("RENT_TYPE >", value, "rentType");
			return this;
		}

		public Criteria andRentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("RENT_TYPE >=", value, "rentType");
			return this;
		}

		public Criteria andRentTypeLessThan(String value) {
			addCriterion("RENT_TYPE <", value, "rentType");
			return this;
		}

		public Criteria andRentTypeLessThanOrEqualTo(String value) {
			addCriterion("RENT_TYPE <=", value, "rentType");
			return this;
		}

		public Criteria andRentTypeLike(String value) {
			addCriterion("RENT_TYPE like", value, "rentType");
			return this;
		}

		public Criteria andRentTypeNotLike(String value) {
			addCriterion("RENT_TYPE not like", value, "rentType");
			return this;
		}

		public Criteria andRentTypeIn(List values) {
			addCriterion("RENT_TYPE in", values, "rentType");
			return this;
		}

		public Criteria andRentTypeNotIn(List values) {
			addCriterion("RENT_TYPE not in", values, "rentType");
			return this;
		}

		public Criteria andRentTypeBetween(String value1, String value2) {
			addCriterion("RENT_TYPE between", value1, value2, "rentType");
			return this;
		}

		public Criteria andRentTypeNotBetween(String value1, String value2) {
			addCriterion("RENT_TYPE not between", value1, value2, "rentType");
			return this;
		}

		public Criteria andNumIsNull() {
			addCriterion("NUM is null");
			return this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("NUM is not null");
			return this;
		}

		public Criteria andNumEqualTo(Long value) {
			addCriterion("NUM =", value, "num");
			return this;
		}

		public Criteria andNumNotEqualTo(Long value) {
			addCriterion("NUM <>", value, "num");
			return this;
		}

		public Criteria andNumGreaterThan(Long value) {
			addCriterion("NUM >", value, "num");
			return this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Long value) {
			addCriterion("NUM >=", value, "num");
			return this;
		}

		public Criteria andNumLessThan(Long value) {
			addCriterion("NUM <", value, "num");
			return this;
		}

		public Criteria andNumLessThanOrEqualTo(Long value) {
			addCriterion("NUM <=", value, "num");
			return this;
		}

		public Criteria andNumIn(List values) {
			addCriterion("NUM in", values, "num");
			return this;
		}

		public Criteria andNumNotIn(List values) {
			addCriterion("NUM not in", values, "num");
			return this;
		}

		public Criteria andNumBetween(Long value1, Long value2) {
			addCriterion("NUM between", value1, value2, "num");
			return this;
		}

		public Criteria andNumNotBetween(Long value1, Long value2) {
			addCriterion("NUM not between", value1, value2, "num");
			return this;
		}

		public Criteria andMachinePriceIsNull() {
			addCriterion("MACHINE_PRICE is null");
			return this;
		}

		public Criteria andMachinePriceIsNotNull() {
			addCriterion("MACHINE_PRICE is not null");
			return this;
		}

		public Criteria andMachinePriceEqualTo(BigDecimal value) {
			addCriterion("MACHINE_PRICE =", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceNotEqualTo(BigDecimal value) {
			addCriterion("MACHINE_PRICE <>", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceGreaterThan(BigDecimal value) {
			addCriterion("MACHINE_PRICE >", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MACHINE_PRICE >=", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceLessThan(BigDecimal value) {
			addCriterion("MACHINE_PRICE <", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MACHINE_PRICE <=", value, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceIn(List values) {
			addCriterion("MACHINE_PRICE in", values, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceNotIn(List values) {
			addCriterion("MACHINE_PRICE not in", values, "machinePrice");
			return this;
		}

		public Criteria andMachinePriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MACHINE_PRICE between", value1, value2,
					"machinePrice");
			return this;
		}

		public Criteria andMachinePriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MACHINE_PRICE not between", value1, value2,
					"machinePrice");
			return this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("CREATER is null");
			return this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("CREATER is not null");
			return this;
		}

		public Criteria andCreaterEqualTo(Long value) {
			addCriterion("CREATER =", value, "creater");
			return this;
		}

		public Criteria andCreaterNotEqualTo(Long value) {
			addCriterion("CREATER <>", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThan(Long value) {
			addCriterion("CREATER >", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(Long value) {
			addCriterion("CREATER >=", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThan(Long value) {
			addCriterion("CREATER <", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThanOrEqualTo(Long value) {
			addCriterion("CREATER <=", value, "creater");
			return this;
		}

		public Criteria andCreaterIn(List values) {
			addCriterion("CREATER in", values, "creater");
			return this;
		}

		public Criteria andCreaterNotIn(List values) {
			addCriterion("CREATER not in", values, "creater");
			return this;
		}

		public Criteria andCreaterBetween(Long value1, Long value2) {
			addCriterion("CREATER between", value1, value2, "creater");
			return this;
		}

		public Criteria andCreaterNotBetween(Long value1, Long value2) {
			addCriterion("CREATER not between", value1, value2, "creater");
			return this;
		}

		public Criteria andUpdaterPeopleIsNull() {
			addCriterion("UPDATER_PEOPLE is null");
			return this;
		}

		public Criteria andUpdaterPeopleIsNotNull() {
			addCriterion("UPDATER_PEOPLE is not null");
			return this;
		}

		public Criteria andUpdaterPeopleEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE =", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <>", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThan(Long value) {
			addCriterion("UPDATER_PEOPLE >", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE >=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThan(Long value) {
			addCriterion("UPDATER_PEOPLE <", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleIn(List values) {
			addCriterion("UPDATER_PEOPLE in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotIn(List values) {
			addCriterion("UPDATER_PEOPLE not in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE between", value1, value2,
					"updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE not between", value1, value2,
					"updaterPeople");
			return this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateIn(List values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotIn(List values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2,
					"updateDate");
			return this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateIn(List values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateNotIn(List values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2,
					"createDate");
			return this;
		}
	}
}