package com.creditease.rc.app.sia.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BorrowerBasicInfoExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public BorrowerBasicInfoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	protected BorrowerBasicInfoExample(BorrowerBasicInfoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ICP_BORROWER_BASIC_INFO
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andBorrowerInfoIdIsNull() {
			addCriterion("BORROWER_INFO_ID is null");
			return this;
		}

		public Criteria andBorrowerInfoIdIsNotNull() {
			addCriterion("BORROWER_INFO_ID is not null");
			return this;
		}

		public Criteria andBorrowerInfoIdEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID =", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <>", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThan(Long value) {
			addCriterion("BORROWER_INFO_ID >", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID >=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThan(Long value) {
			addCriterion("BORROWER_INFO_ID <", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdIn(List values) {
			addCriterion("BORROWER_INFO_ID in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotIn(List values) {
			addCriterion("BORROWER_INFO_ID not in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID not between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andTransactionIdIsNull() {
			addCriterion("TRANSACTION_ID is null");
			return this;
		}

		public Criteria andTransactionIdIsNotNull() {
			addCriterion("TRANSACTION_ID is not null");
			return this;
		}

		public Criteria andTransactionIdEqualTo(Long value) {
			addCriterion("TRANSACTION_ID =", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdNotEqualTo(Long value) {
			addCriterion("TRANSACTION_ID <>", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdGreaterThan(Long value) {
			addCriterion("TRANSACTION_ID >", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("TRANSACTION_ID >=", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdLessThan(Long value) {
			addCriterion("TRANSACTION_ID <", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdLessThanOrEqualTo(Long value) {
			addCriterion("TRANSACTION_ID <=", value, "transactionId");
			return this;
		}

		public Criteria andTransactionIdIn(List values) {
			addCriterion("TRANSACTION_ID in", values, "transactionId");
			return this;
		}

		public Criteria andTransactionIdNotIn(List values) {
			addCriterion("TRANSACTION_ID not in", values, "transactionId");
			return this;
		}

		public Criteria andTransactionIdBetween(Long value1, Long value2) {
			addCriterion("TRANSACTION_ID between", value1, value2,
					"transactionId");
			return this;
		}

		public Criteria andTransactionIdNotBetween(Long value1, Long value2) {
			addCriterion("TRANSACTION_ID not between", value1, value2,
					"transactionId");
			return this;
		}

		public Criteria andBusinessBorrowerIdIsNull() {
			addCriterion("BUSINESS_BORROWER_ID is null");
			return this;
		}

		public Criteria andBusinessBorrowerIdIsNotNull() {
			addCriterion("BUSINESS_BORROWER_ID is not null");
			return this;
		}

		public Criteria andBusinessBorrowerIdEqualTo(Long value) {
			addCriterion("BUSINESS_BORROWER_ID =", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdNotEqualTo(Long value) {
			addCriterion("BUSINESS_BORROWER_ID <>", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdGreaterThan(Long value) {
			addCriterion("BUSINESS_BORROWER_ID >", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BUSINESS_BORROWER_ID >=", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdLessThan(Long value) {
			addCriterion("BUSINESS_BORROWER_ID <", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdLessThanOrEqualTo(Long value) {
			addCriterion("BUSINESS_BORROWER_ID <=", value, "businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdIn(List values) {
			addCriterion("BUSINESS_BORROWER_ID in", values,
					"businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdNotIn(List values) {
			addCriterion("BUSINESS_BORROWER_ID not in", values,
					"businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdBetween(Long value1, Long value2) {
			addCriterion("BUSINESS_BORROWER_ID between", value1, value2,
					"businessBorrowerId");
			return this;
		}

		public Criteria andBusinessBorrowerIdNotBetween(Long value1, Long value2) {
			addCriterion("BUSINESS_BORROWER_ID not between", value1, value2,
					"businessBorrowerId");
			return this;
		}

		public Criteria andSystemSourceIsNull() {
			addCriterion("SYSTEM_SOURCE is null");
			return this;
		}

		public Criteria andSystemSourceIsNotNull() {
			addCriterion("SYSTEM_SOURCE is not null");
			return this;
		}

		public Criteria andSystemSourceEqualTo(String value) {
			addCriterion("SYSTEM_SOURCE =", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceNotEqualTo(String value) {
			addCriterion("SYSTEM_SOURCE <>", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceGreaterThan(String value) {
			addCriterion("SYSTEM_SOURCE >", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceGreaterThanOrEqualTo(String value) {
			addCriterion("SYSTEM_SOURCE >=", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceLessThan(String value) {
			addCriterion("SYSTEM_SOURCE <", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceLessThanOrEqualTo(String value) {
			addCriterion("SYSTEM_SOURCE <=", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceLike(String value) {
			addCriterion("SYSTEM_SOURCE like", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceNotLike(String value) {
			addCriterion("SYSTEM_SOURCE not like", value, "systemSource");
			return this;
		}

		public Criteria andSystemSourceIn(List values) {
			addCriterion("SYSTEM_SOURCE in", values, "systemSource");
			return this;
		}

		public Criteria andSystemSourceNotIn(List values) {
			addCriterion("SYSTEM_SOURCE not in", values, "systemSource");
			return this;
		}

		public Criteria andSystemSourceBetween(String value1, String value2) {
			addCriterion("SYSTEM_SOURCE between", value1, value2,
					"systemSource");
			return this;
		}

		public Criteria andSystemSourceNotBetween(String value1, String value2) {
			addCriterion("SYSTEM_SOURCE not between", value1, value2,
					"systemSource");
			return this;
		}

		public Criteria andBorrowerTypeIsNull() {
			addCriterion("BORROWER_TYPE is null");
			return this;
		}

		public Criteria andBorrowerTypeIsNotNull() {
			addCriterion("BORROWER_TYPE is not null");
			return this;
		}

		public Criteria andBorrowerTypeEqualTo(String value) {
			addCriterion("BORROWER_TYPE =", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeNotEqualTo(String value) {
			addCriterion("BORROWER_TYPE <>", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeGreaterThan(String value) {
			addCriterion("BORROWER_TYPE >", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeGreaterThanOrEqualTo(String value) {
			addCriterion("BORROWER_TYPE >=", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeLessThan(String value) {
			addCriterion("BORROWER_TYPE <", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeLessThanOrEqualTo(String value) {
			addCriterion("BORROWER_TYPE <=", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeLike(String value) {
			addCriterion("BORROWER_TYPE like", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeNotLike(String value) {
			addCriterion("BORROWER_TYPE not like", value, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeIn(List values) {
			addCriterion("BORROWER_TYPE in", values, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeNotIn(List values) {
			addCriterion("BORROWER_TYPE not in", values, "borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeBetween(String value1, String value2) {
			addCriterion("BORROWER_TYPE between", value1, value2,
					"borrowerType");
			return this;
		}

		public Criteria andBorrowerTypeNotBetween(String value1, String value2) {
			addCriterion("BORROWER_TYPE not between", value1, value2,
					"borrowerType");
			return this;
		}

		public Criteria andMortgagorNameIsNull() {
			addCriterion("MORTGAGOR_NAME is null");
			return this;
		}

		public Criteria andMortgagorNameIsNotNull() {
			addCriterion("MORTGAGOR_NAME is not null");
			return this;
		}

		public Criteria andMortgagorNameEqualTo(String value) {
			addCriterion("MORTGAGOR_NAME =", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameNotEqualTo(String value) {
			addCriterion("MORTGAGOR_NAME <>", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameGreaterThan(String value) {
			addCriterion("MORTGAGOR_NAME >", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameGreaterThanOrEqualTo(String value) {
			addCriterion("MORTGAGOR_NAME >=", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameLessThan(String value) {
			addCriterion("MORTGAGOR_NAME <", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameLessThanOrEqualTo(String value) {
			addCriterion("MORTGAGOR_NAME <=", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameLike(String value) {
			addCriterion("MORTGAGOR_NAME like", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameNotLike(String value) {
			addCriterion("MORTGAGOR_NAME not like", value, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameIn(List values) {
			addCriterion("MORTGAGOR_NAME in", values, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameNotIn(List values) {
			addCriterion("MORTGAGOR_NAME not in", values, "mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameBetween(String value1, String value2) {
			addCriterion("MORTGAGOR_NAME between", value1, value2,
					"mortgagorName");
			return this;
		}

		public Criteria andMortgagorNameNotBetween(String value1, String value2) {
			addCriterion("MORTGAGOR_NAME not between", value1, value2,
					"mortgagorName");
			return this;
		}

		public Criteria andNationIsNull() {
			addCriterion("NATION is null");
			return this;
		}

		public Criteria andNationIsNotNull() {
			addCriterion("NATION is not null");
			return this;
		}

		public Criteria andNationEqualTo(String value) {
			addCriterion("NATION =", value, "nation");
			return this;
		}

		public Criteria andNationNotEqualTo(String value) {
			addCriterion("NATION <>", value, "nation");
			return this;
		}

		public Criteria andNationGreaterThan(String value) {
			addCriterion("NATION >", value, "nation");
			return this;
		}

		public Criteria andNationGreaterThanOrEqualTo(String value) {
			addCriterion("NATION >=", value, "nation");
			return this;
		}

		public Criteria andNationLessThan(String value) {
			addCriterion("NATION <", value, "nation");
			return this;
		}

		public Criteria andNationLessThanOrEqualTo(String value) {
			addCriterion("NATION <=", value, "nation");
			return this;
		}

		public Criteria andNationLike(String value) {
			addCriterion("NATION like", value, "nation");
			return this;
		}

		public Criteria andNationNotLike(String value) {
			addCriterion("NATION not like", value, "nation");
			return this;
		}

		public Criteria andNationIn(List values) {
			addCriterion("NATION in", values, "nation");
			return this;
		}

		public Criteria andNationNotIn(List values) {
			addCriterion("NATION not in", values, "nation");
			return this;
		}

		public Criteria andNationBetween(String value1, String value2) {
			addCriterion("NATION between", value1, value2, "nation");
			return this;
		}

		public Criteria andNationNotBetween(String value1, String value2) {
			addCriterion("NATION not between", value1, value2, "nation");
			return this;
		}

		public Criteria andFormerNameIsNull() {
			addCriterion("FORMER_NAME is null");
			return this;
		}

		public Criteria andFormerNameIsNotNull() {
			addCriterion("FORMER_NAME is not null");
			return this;
		}

		public Criteria andFormerNameEqualTo(String value) {
			addCriterion("FORMER_NAME =", value, "formerName");
			return this;
		}

		public Criteria andFormerNameNotEqualTo(String value) {
			addCriterion("FORMER_NAME <>", value, "formerName");
			return this;
		}

		public Criteria andFormerNameGreaterThan(String value) {
			addCriterion("FORMER_NAME >", value, "formerName");
			return this;
		}

		public Criteria andFormerNameGreaterThanOrEqualTo(String value) {
			addCriterion("FORMER_NAME >=", value, "formerName");
			return this;
		}

		public Criteria andFormerNameLessThan(String value) {
			addCriterion("FORMER_NAME <", value, "formerName");
			return this;
		}

		public Criteria andFormerNameLessThanOrEqualTo(String value) {
			addCriterion("FORMER_NAME <=", value, "formerName");
			return this;
		}

		public Criteria andFormerNameLike(String value) {
			addCriterion("FORMER_NAME like", value, "formerName");
			return this;
		}

		public Criteria andFormerNameNotLike(String value) {
			addCriterion("FORMER_NAME not like", value, "formerName");
			return this;
		}

		public Criteria andFormerNameIn(List values) {
			addCriterion("FORMER_NAME in", values, "formerName");
			return this;
		}

		public Criteria andFormerNameNotIn(List values) {
			addCriterion("FORMER_NAME not in", values, "formerName");
			return this;
		}

		public Criteria andFormerNameBetween(String value1, String value2) {
			addCriterion("FORMER_NAME between", value1, value2, "formerName");
			return this;
		}

		public Criteria andFormerNameNotBetween(String value1, String value2) {
			addCriterion("FORMER_NAME not between", value1, value2,
					"formerName");
			return this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("BIRTHDAY is null");
			return this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("BIRTHDAY is not null");
			return this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterion("BIRTHDAY =", value, "birthday");
			return this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterion("BIRTHDAY <>", value, "birthday");
			return this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterion("BIRTHDAY >", value, "birthday");
			return this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("BIRTHDAY >=", value, "birthday");
			return this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterion("BIRTHDAY <", value, "birthday");
			return this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("BIRTHDAY <=", value, "birthday");
			return this;
		}

		public Criteria andBirthdayIn(List values) {
			addCriterion("BIRTHDAY in", values, "birthday");
			return this;
		}

		public Criteria andBirthdayNotIn(List values) {
			addCriterion("BIRTHDAY not in", values, "birthday");
			return this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterion("BIRTHDAY between", value1, value2, "birthday");
			return this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("BIRTHDAY not between", value1, value2, "birthday");
			return this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("GENDER is null");
			return this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("GENDER is not null");
			return this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("GENDER =", value, "gender");
			return this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("GENDER <>", value, "gender");
			return this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("GENDER >", value, "gender");
			return this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("GENDER >=", value, "gender");
			return this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("GENDER <", value, "gender");
			return this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("GENDER <=", value, "gender");
			return this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("GENDER like", value, "gender");
			return this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("GENDER not like", value, "gender");
			return this;
		}

		public Criteria andGenderIn(List values) {
			addCriterion("GENDER in", values, "gender");
			return this;
		}

		public Criteria andGenderNotIn(List values) {
			addCriterion("GENDER not in", values, "gender");
			return this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("GENDER between", value1, value2, "gender");
			return this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("GENDER not between", value1, value2, "gender");
			return this;
		}

		public Criteria andIdNumberIsNull() {
			addCriterion("ID_NUMBER is null");
			return this;
		}

		public Criteria andIdNumberIsNotNull() {
			addCriterion("ID_NUMBER is not null");
			return this;
		}

		public Criteria andIdNumberEqualTo(String value) {
			addCriterion("ID_NUMBER =", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberNotEqualTo(String value) {
			addCriterion("ID_NUMBER <>", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberGreaterThan(String value) {
			addCriterion("ID_NUMBER >", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
			addCriterion("ID_NUMBER >=", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberLessThan(String value) {
			addCriterion("ID_NUMBER <", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberLessThanOrEqualTo(String value) {
			addCriterion("ID_NUMBER <=", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberLike(String value) {
			addCriterion("ID_NUMBER like", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberNotLike(String value) {
			addCriterion("ID_NUMBER not like", value, "idNumber");
			return this;
		}

		public Criteria andIdNumberIn(List values) {
			addCriterion("ID_NUMBER in", values, "idNumber");
			return this;
		}

		public Criteria andIdNumberNotIn(List values) {
			addCriterion("ID_NUMBER not in", values, "idNumber");
			return this;
		}

		public Criteria andIdNumberBetween(String value1, String value2) {
			addCriterion("ID_NUMBER between", value1, value2, "idNumber");
			return this;
		}

		public Criteria andIdNumberNotBetween(String value1, String value2) {
			addCriterion("ID_NUMBER not between", value1, value2, "idNumber");
			return this;
		}

		public Criteria andIdTypeIsNull() {
			addCriterion("ID_TYPE is null");
			return this;
		}

		public Criteria andIdTypeIsNotNull() {
			addCriterion("ID_TYPE is not null");
			return this;
		}

		public Criteria andIdTypeEqualTo(String value) {
			addCriterion("ID_TYPE =", value, "idType");
			return this;
		}

		public Criteria andIdTypeNotEqualTo(String value) {
			addCriterion("ID_TYPE <>", value, "idType");
			return this;
		}

		public Criteria andIdTypeGreaterThan(String value) {
			addCriterion("ID_TYPE >", value, "idType");
			return this;
		}

		public Criteria andIdTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ID_TYPE >=", value, "idType");
			return this;
		}

		public Criteria andIdTypeLessThan(String value) {
			addCriterion("ID_TYPE <", value, "idType");
			return this;
		}

		public Criteria andIdTypeLessThanOrEqualTo(String value) {
			addCriterion("ID_TYPE <=", value, "idType");
			return this;
		}

		public Criteria andIdTypeLike(String value) {
			addCriterion("ID_TYPE like", value, "idType");
			return this;
		}

		public Criteria andIdTypeNotLike(String value) {
			addCriterion("ID_TYPE not like", value, "idType");
			return this;
		}

		public Criteria andIdTypeIn(List values) {
			addCriterion("ID_TYPE in", values, "idType");
			return this;
		}

		public Criteria andIdTypeNotIn(List values) {
			addCriterion("ID_TYPE not in", values, "idType");
			return this;
		}

		public Criteria andIdTypeBetween(String value1, String value2) {
			addCriterion("ID_TYPE between", value1, value2, "idType");
			return this;
		}

		public Criteria andIdTypeNotBetween(String value1, String value2) {
			addCriterion("ID_TYPE not between", value1, value2, "idType");
			return this;
		}

		public Criteria andIdValidityDateIsNull() {
			addCriterion("ID_VALIDITY_DATE is null");
			return this;
		}

		public Criteria andIdValidityDateIsNotNull() {
			addCriterion("ID_VALIDITY_DATE is not null");
			return this;
		}

		public Criteria andIdValidityDateEqualTo(Date value) {
			addCriterion("ID_VALIDITY_DATE =", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateNotEqualTo(Date value) {
			addCriterion("ID_VALIDITY_DATE <>", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateGreaterThan(Date value) {
			addCriterion("ID_VALIDITY_DATE >", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateGreaterThanOrEqualTo(Date value) {
			addCriterion("ID_VALIDITY_DATE >=", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateLessThan(Date value) {
			addCriterion("ID_VALIDITY_DATE <", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateLessThanOrEqualTo(Date value) {
			addCriterion("ID_VALIDITY_DATE <=", value, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateIn(List values) {
			addCriterion("ID_VALIDITY_DATE in", values, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateNotIn(List values) {
			addCriterion("ID_VALIDITY_DATE not in", values, "idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateBetween(Date value1, Date value2) {
			addCriterion("ID_VALIDITY_DATE between", value1, value2,
					"idValidityDate");
			return this;
		}

		public Criteria andIdValidityDateNotBetween(Date value1, Date value2) {
			addCriterion("ID_VALIDITY_DATE not between", value1, value2,
					"idValidityDate");
			return this;
		}

		public Criteria andCardValideEndDateIsNull() {
			addCriterion("CARD_VALIDE_END_DATE is null");
			return this;
		}

		public Criteria andCardValideEndDateIsNotNull() {
			addCriterion("CARD_VALIDE_END_DATE is not null");
			return this;
		}

		public Criteria andCardValideEndDateEqualTo(Date value) {
			addCriterion("CARD_VALIDE_END_DATE =", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateNotEqualTo(Date value) {
			addCriterion("CARD_VALIDE_END_DATE <>", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateGreaterThan(Date value) {
			addCriterion("CARD_VALIDE_END_DATE >", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CARD_VALIDE_END_DATE >=", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateLessThan(Date value) {
			addCriterion("CARD_VALIDE_END_DATE <", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateLessThanOrEqualTo(Date value) {
			addCriterion("CARD_VALIDE_END_DATE <=", value, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateIn(List values) {
			addCriterion("CARD_VALIDE_END_DATE in", values, "cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateNotIn(List values) {
			addCriterion("CARD_VALIDE_END_DATE not in", values,
					"cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateBetween(Date value1, Date value2) {
			addCriterion("CARD_VALIDE_END_DATE between", value1, value2,
					"cardValideEndDate");
			return this;
		}

		public Criteria andCardValideEndDateNotBetween(Date value1, Date value2) {
			addCriterion("CARD_VALIDE_END_DATE not between", value1, value2,
					"cardValideEndDate");
			return this;
		}

		public Criteria andIsTogetherBorrowerIsNull() {
			addCriterion("IS_TOGETHER_BORROWER is null");
			return this;
		}

		public Criteria andIsTogetherBorrowerIsNotNull() {
			addCriterion("IS_TOGETHER_BORROWER is not null");
			return this;
		}

		public Criteria andIsTogetherBorrowerEqualTo(String value) {
			addCriterion("IS_TOGETHER_BORROWER =", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerNotEqualTo(String value) {
			addCriterion("IS_TOGETHER_BORROWER <>", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerGreaterThan(String value) {
			addCriterion("IS_TOGETHER_BORROWER >", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerGreaterThanOrEqualTo(String value) {
			addCriterion("IS_TOGETHER_BORROWER >=", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerLessThan(String value) {
			addCriterion("IS_TOGETHER_BORROWER <", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerLessThanOrEqualTo(String value) {
			addCriterion("IS_TOGETHER_BORROWER <=", value, "isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerLike(String value) {
			addCriterion("IS_TOGETHER_BORROWER like", value,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerNotLike(String value) {
			addCriterion("IS_TOGETHER_BORROWER not like", value,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerIn(List values) {
			addCriterion("IS_TOGETHER_BORROWER in", values,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerNotIn(List values) {
			addCriterion("IS_TOGETHER_BORROWER not in", values,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerBetween(String value1,
				String value2) {
			addCriterion("IS_TOGETHER_BORROWER between", value1, value2,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andIsTogetherBorrowerNotBetween(String value1,
				String value2) {
			addCriterion("IS_TOGETHER_BORROWER not between", value1, value2,
					"isTogetherBorrower");
			return this;
		}

		public Criteria andHouseHoldTypeIsNull() {
			addCriterion("HOUSE_HOLD_TYPE is null");
			return this;
		}

		public Criteria andHouseHoldTypeIsNotNull() {
			addCriterion("HOUSE_HOLD_TYPE is not null");
			return this;
		}

		public Criteria andHouseHoldTypeEqualTo(String value) {
			addCriterion("HOUSE_HOLD_TYPE =", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeNotEqualTo(String value) {
			addCriterion("HOUSE_HOLD_TYPE <>", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeGreaterThan(String value) {
			addCriterion("HOUSE_HOLD_TYPE >", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeGreaterThanOrEqualTo(String value) {
			addCriterion("HOUSE_HOLD_TYPE >=", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeLessThan(String value) {
			addCriterion("HOUSE_HOLD_TYPE <", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeLessThanOrEqualTo(String value) {
			addCriterion("HOUSE_HOLD_TYPE <=", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeLike(String value) {
			addCriterion("HOUSE_HOLD_TYPE like", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeNotLike(String value) {
			addCriterion("HOUSE_HOLD_TYPE not like", value, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeIn(List values) {
			addCriterion("HOUSE_HOLD_TYPE in", values, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeNotIn(List values) {
			addCriterion("HOUSE_HOLD_TYPE not in", values, "houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeBetween(String value1, String value2) {
			addCriterion("HOUSE_HOLD_TYPE between", value1, value2,
					"houseHoldType");
			return this;
		}

		public Criteria andHouseHoldTypeNotBetween(String value1, String value2) {
			addCriterion("HOUSE_HOLD_TYPE not between", value1, value2,
					"houseHoldType");
			return this;
		}

		public Criteria andMarriageIsNull() {
			addCriterion("MARRIAGE is null");
			return this;
		}

		public Criteria andMarriageIsNotNull() {
			addCriterion("MARRIAGE is not null");
			return this;
		}

		public Criteria andMarriageEqualTo(String value) {
			addCriterion("MARRIAGE =", value, "marriage");
			return this;
		}

		public Criteria andMarriageNotEqualTo(String value) {
			addCriterion("MARRIAGE <>", value, "marriage");
			return this;
		}

		public Criteria andMarriageGreaterThan(String value) {
			addCriterion("MARRIAGE >", value, "marriage");
			return this;
		}

		public Criteria andMarriageGreaterThanOrEqualTo(String value) {
			addCriterion("MARRIAGE >=", value, "marriage");
			return this;
		}

		public Criteria andMarriageLessThan(String value) {
			addCriterion("MARRIAGE <", value, "marriage");
			return this;
		}

		public Criteria andMarriageLessThanOrEqualTo(String value) {
			addCriterion("MARRIAGE <=", value, "marriage");
			return this;
		}

		public Criteria andMarriageLike(String value) {
			addCriterion("MARRIAGE like", value, "marriage");
			return this;
		}

		public Criteria andMarriageNotLike(String value) {
			addCriterion("MARRIAGE not like", value, "marriage");
			return this;
		}

		public Criteria andMarriageIn(List values) {
			addCriterion("MARRIAGE in", values, "marriage");
			return this;
		}

		public Criteria andMarriageNotIn(List values) {
			addCriterion("MARRIAGE not in", values, "marriage");
			return this;
		}

		public Criteria andMarriageBetween(String value1, String value2) {
			addCriterion("MARRIAGE between", value1, value2, "marriage");
			return this;
		}

		public Criteria andMarriageNotBetween(String value1, String value2) {
			addCriterion("MARRIAGE not between", value1, value2, "marriage");
			return this;
		}

		public Criteria andMarriageRemarkIsNull() {
			addCriterion("MARRIAGE_REMARK is null");
			return this;
		}

		public Criteria andMarriageRemarkIsNotNull() {
			addCriterion("MARRIAGE_REMARK is not null");
			return this;
		}

		public Criteria andMarriageRemarkEqualTo(String value) {
			addCriterion("MARRIAGE_REMARK =", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkNotEqualTo(String value) {
			addCriterion("MARRIAGE_REMARK <>", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkGreaterThan(String value) {
			addCriterion("MARRIAGE_REMARK >", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("MARRIAGE_REMARK >=", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkLessThan(String value) {
			addCriterion("MARRIAGE_REMARK <", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkLessThanOrEqualTo(String value) {
			addCriterion("MARRIAGE_REMARK <=", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkLike(String value) {
			addCriterion("MARRIAGE_REMARK like", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkNotLike(String value) {
			addCriterion("MARRIAGE_REMARK not like", value, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkIn(List values) {
			addCriterion("MARRIAGE_REMARK in", values, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkNotIn(List values) {
			addCriterion("MARRIAGE_REMARK not in", values, "marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkBetween(String value1, String value2) {
			addCriterion("MARRIAGE_REMARK between", value1, value2,
					"marriageRemark");
			return this;
		}

		public Criteria andMarriageRemarkNotBetween(String value1, String value2) {
			addCriterion("MARRIAGE_REMARK not between", value1, value2,
					"marriageRemark");
			return this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("AGE is null");
			return this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("AGE is not null");
			return this;
		}

		public Criteria andAgeEqualTo(Short value) {
			addCriterion("AGE =", value, "age");
			return this;
		}

		public Criteria andAgeNotEqualTo(Short value) {
			addCriterion("AGE <>", value, "age");
			return this;
		}

		public Criteria andAgeGreaterThan(Short value) {
			addCriterion("AGE >", value, "age");
			return this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Short value) {
			addCriterion("AGE >=", value, "age");
			return this;
		}

		public Criteria andAgeLessThan(Short value) {
			addCriterion("AGE <", value, "age");
			return this;
		}

		public Criteria andAgeLessThanOrEqualTo(Short value) {
			addCriterion("AGE <=", value, "age");
			return this;
		}

		public Criteria andAgeIn(List values) {
			addCriterion("AGE in", values, "age");
			return this;
		}

		public Criteria andAgeNotIn(List values) {
			addCriterion("AGE not in", values, "age");
			return this;
		}

		public Criteria andAgeBetween(Short value1, Short value2) {
			addCriterion("AGE between", value1, value2, "age");
			return this;
		}

		public Criteria andAgeNotBetween(Short value1, Short value2) {
			addCriterion("AGE not between", value1, value2, "age");
			return this;
		}

		public Criteria andTempCardIsNull() {
			addCriterion("TEMP_CARD is null");
			return this;
		}

		public Criteria andTempCardIsNotNull() {
			addCriterion("TEMP_CARD is not null");
			return this;
		}

		public Criteria andTempCardEqualTo(String value) {
			addCriterion("TEMP_CARD =", value, "tempCard");
			return this;
		}

		public Criteria andTempCardNotEqualTo(String value) {
			addCriterion("TEMP_CARD <>", value, "tempCard");
			return this;
		}

		public Criteria andTempCardGreaterThan(String value) {
			addCriterion("TEMP_CARD >", value, "tempCard");
			return this;
		}

		public Criteria andTempCardGreaterThanOrEqualTo(String value) {
			addCriterion("TEMP_CARD >=", value, "tempCard");
			return this;
		}

		public Criteria andTempCardLessThan(String value) {
			addCriterion("TEMP_CARD <", value, "tempCard");
			return this;
		}

		public Criteria andTempCardLessThanOrEqualTo(String value) {
			addCriterion("TEMP_CARD <=", value, "tempCard");
			return this;
		}

		public Criteria andTempCardLike(String value) {
			addCriterion("TEMP_CARD like", value, "tempCard");
			return this;
		}

		public Criteria andTempCardNotLike(String value) {
			addCriterion("TEMP_CARD not like", value, "tempCard");
			return this;
		}

		public Criteria andTempCardIn(List values) {
			addCriterion("TEMP_CARD in", values, "tempCard");
			return this;
		}

		public Criteria andTempCardNotIn(List values) {
			addCriterion("TEMP_CARD not in", values, "tempCard");
			return this;
		}

		public Criteria andTempCardBetween(String value1, String value2) {
			addCriterion("TEMP_CARD between", value1, value2, "tempCard");
			return this;
		}

		public Criteria andTempCardNotBetween(String value1, String value2) {
			addCriterion("TEMP_CARD not between", value1, value2, "tempCard");
			return this;
		}

		public Criteria andCustomIdentityIsNull() {
			addCriterion("CUSTOM_IDENTITY is null");
			return this;
		}

		public Criteria andCustomIdentityIsNotNull() {
			addCriterion("CUSTOM_IDENTITY is not null");
			return this;
		}

		public Criteria andCustomIdentityEqualTo(String value) {
			addCriterion("CUSTOM_IDENTITY =", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityNotEqualTo(String value) {
			addCriterion("CUSTOM_IDENTITY <>", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityGreaterThan(String value) {
			addCriterion("CUSTOM_IDENTITY >", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityGreaterThanOrEqualTo(String value) {
			addCriterion("CUSTOM_IDENTITY >=", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityLessThan(String value) {
			addCriterion("CUSTOM_IDENTITY <", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityLessThanOrEqualTo(String value) {
			addCriterion("CUSTOM_IDENTITY <=", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityLike(String value) {
			addCriterion("CUSTOM_IDENTITY like", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityNotLike(String value) {
			addCriterion("CUSTOM_IDENTITY not like", value, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityIn(List values) {
			addCriterion("CUSTOM_IDENTITY in", values, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityNotIn(List values) {
			addCriterion("CUSTOM_IDENTITY not in", values, "customIdentity");
			return this;
		}

		public Criteria andCustomIdentityBetween(String value1, String value2) {
			addCriterion("CUSTOM_IDENTITY between", value1, value2,
					"customIdentity");
			return this;
		}

		public Criteria andCustomIdentityNotBetween(String value1, String value2) {
			addCriterion("CUSTOM_IDENTITY not between", value1, value2,
					"customIdentity");
			return this;
		}

		public Criteria andMaxDiplomaIsNull() {
			addCriterion("MAX_DIPLOMA is null");
			return this;
		}

		public Criteria andMaxDiplomaIsNotNull() {
			addCriterion("MAX_DIPLOMA is not null");
			return this;
		}

		public Criteria andMaxDiplomaEqualTo(String value) {
			addCriterion("MAX_DIPLOMA =", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaNotEqualTo(String value) {
			addCriterion("MAX_DIPLOMA <>", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaGreaterThan(String value) {
			addCriterion("MAX_DIPLOMA >", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaGreaterThanOrEqualTo(String value) {
			addCriterion("MAX_DIPLOMA >=", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaLessThan(String value) {
			addCriterion("MAX_DIPLOMA <", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaLessThanOrEqualTo(String value) {
			addCriterion("MAX_DIPLOMA <=", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaLike(String value) {
			addCriterion("MAX_DIPLOMA like", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaNotLike(String value) {
			addCriterion("MAX_DIPLOMA not like", value, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaIn(List values) {
			addCriterion("MAX_DIPLOMA in", values, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaNotIn(List values) {
			addCriterion("MAX_DIPLOMA not in", values, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaBetween(String value1, String value2) {
			addCriterion("MAX_DIPLOMA between", value1, value2, "maxDiploma");
			return this;
		}

		public Criteria andMaxDiplomaNotBetween(String value1, String value2) {
			addCriterion("MAX_DIPLOMA not between", value1, value2,
					"maxDiploma");
			return this;
		}

		public Criteria andDomicileProvinceIsNull() {
			addCriterion("DOMICILE_PROVINCE is null");
			return this;
		}

		public Criteria andDomicileProvinceIsNotNull() {
			addCriterion("DOMICILE_PROVINCE is not null");
			return this;
		}

		public Criteria andDomicileProvinceEqualTo(String value) {
			addCriterion("DOMICILE_PROVINCE =", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceNotEqualTo(String value) {
			addCriterion("DOMICILE_PROVINCE <>", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceGreaterThan(String value) {
			addCriterion("DOMICILE_PROVINCE >", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILE_PROVINCE >=", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceLessThan(String value) {
			addCriterion("DOMICILE_PROVINCE <", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceLessThanOrEqualTo(String value) {
			addCriterion("DOMICILE_PROVINCE <=", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceLike(String value) {
			addCriterion("DOMICILE_PROVINCE like", value, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceNotLike(String value) {
			addCriterion("DOMICILE_PROVINCE not like", value,
					"domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceIn(List values) {
			addCriterion("DOMICILE_PROVINCE in", values, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceNotIn(List values) {
			addCriterion("DOMICILE_PROVINCE not in", values, "domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceBetween(String value1, String value2) {
			addCriterion("DOMICILE_PROVINCE between", value1, value2,
					"domicileProvince");
			return this;
		}

		public Criteria andDomicileProvinceNotBetween(String value1,
				String value2) {
			addCriterion("DOMICILE_PROVINCE not between", value1, value2,
					"domicileProvince");
			return this;
		}

		public Criteria andDomicileCityIsNull() {
			addCriterion("DOMICILE_CITY is null");
			return this;
		}

		public Criteria andDomicileCityIsNotNull() {
			addCriterion("DOMICILE_CITY is not null");
			return this;
		}

		public Criteria andDomicileCityEqualTo(String value) {
			addCriterion("DOMICILE_CITY =", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityNotEqualTo(String value) {
			addCriterion("DOMICILE_CITY <>", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityGreaterThan(String value) {
			addCriterion("DOMICILE_CITY >", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILE_CITY >=", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityLessThan(String value) {
			addCriterion("DOMICILE_CITY <", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityLessThanOrEqualTo(String value) {
			addCriterion("DOMICILE_CITY <=", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityLike(String value) {
			addCriterion("DOMICILE_CITY like", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityNotLike(String value) {
			addCriterion("DOMICILE_CITY not like", value, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityIn(List values) {
			addCriterion("DOMICILE_CITY in", values, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityNotIn(List values) {
			addCriterion("DOMICILE_CITY not in", values, "domicileCity");
			return this;
		}

		public Criteria andDomicileCityBetween(String value1, String value2) {
			addCriterion("DOMICILE_CITY between", value1, value2,
					"domicileCity");
			return this;
		}

		public Criteria andDomicileCityNotBetween(String value1, String value2) {
			addCriterion("DOMICILE_CITY not between", value1, value2,
					"domicileCity");
			return this;
		}

		public Criteria andDomicileDistrictIsNull() {
			addCriterion("DOMICILE_DISTRICT is null");
			return this;
		}

		public Criteria andDomicileDistrictIsNotNull() {
			addCriterion("DOMICILE_DISTRICT is not null");
			return this;
		}

		public Criteria andDomicileDistrictEqualTo(String value) {
			addCriterion("DOMICILE_DISTRICT =", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictNotEqualTo(String value) {
			addCriterion("DOMICILE_DISTRICT <>", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictGreaterThan(String value) {
			addCriterion("DOMICILE_DISTRICT >", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILE_DISTRICT >=", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictLessThan(String value) {
			addCriterion("DOMICILE_DISTRICT <", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictLessThanOrEqualTo(String value) {
			addCriterion("DOMICILE_DISTRICT <=", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictLike(String value) {
			addCriterion("DOMICILE_DISTRICT like", value, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictNotLike(String value) {
			addCriterion("DOMICILE_DISTRICT not like", value,
					"domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictIn(List values) {
			addCriterion("DOMICILE_DISTRICT in", values, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictNotIn(List values) {
			addCriterion("DOMICILE_DISTRICT not in", values, "domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictBetween(String value1, String value2) {
			addCriterion("DOMICILE_DISTRICT between", value1, value2,
					"domicileDistrict");
			return this;
		}

		public Criteria andDomicileDistrictNotBetween(String value1,
				String value2) {
			addCriterion("DOMICILE_DISTRICT not between", value1, value2,
					"domicileDistrict");
			return this;
		}

		public Criteria andDomicileAddrIsNull() {
			addCriterion("DOMICILE_ADDR is null");
			return this;
		}

		public Criteria andDomicileAddrIsNotNull() {
			addCriterion("DOMICILE_ADDR is not null");
			return this;
		}

		public Criteria andDomicileAddrEqualTo(String value) {
			addCriterion("DOMICILE_ADDR =", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrNotEqualTo(String value) {
			addCriterion("DOMICILE_ADDR <>", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrGreaterThan(String value) {
			addCriterion("DOMICILE_ADDR >", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILE_ADDR >=", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrLessThan(String value) {
			addCriterion("DOMICILE_ADDR <", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrLessThanOrEqualTo(String value) {
			addCriterion("DOMICILE_ADDR <=", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrLike(String value) {
			addCriterion("DOMICILE_ADDR like", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrNotLike(String value) {
			addCriterion("DOMICILE_ADDR not like", value, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrIn(List values) {
			addCriterion("DOMICILE_ADDR in", values, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrNotIn(List values) {
			addCriterion("DOMICILE_ADDR not in", values, "domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrBetween(String value1, String value2) {
			addCriterion("DOMICILE_ADDR between", value1, value2,
					"domicileAddr");
			return this;
		}

		public Criteria andDomicileAddrNotBetween(String value1, String value2) {
			addCriterion("DOMICILE_ADDR not between", value1, value2,
					"domicileAddr");
			return this;
		}

		public Criteria andRegisterPostcardIsNull() {
			addCriterion("REGISTER_POSTCARD is null");
			return this;
		}

		public Criteria andRegisterPostcardIsNotNull() {
			addCriterion("REGISTER_POSTCARD is not null");
			return this;
		}

		public Criteria andRegisterPostcardEqualTo(String value) {
			addCriterion("REGISTER_POSTCARD =", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardNotEqualTo(String value) {
			addCriterion("REGISTER_POSTCARD <>", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardGreaterThan(String value) {
			addCriterion("REGISTER_POSTCARD >", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardGreaterThanOrEqualTo(String value) {
			addCriterion("REGISTER_POSTCARD >=", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardLessThan(String value) {
			addCriterion("REGISTER_POSTCARD <", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardLessThanOrEqualTo(String value) {
			addCriterion("REGISTER_POSTCARD <=", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardLike(String value) {
			addCriterion("REGISTER_POSTCARD like", value, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardNotLike(String value) {
			addCriterion("REGISTER_POSTCARD not like", value,
					"registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardIn(List values) {
			addCriterion("REGISTER_POSTCARD in", values, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardNotIn(List values) {
			addCriterion("REGISTER_POSTCARD not in", values, "registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardBetween(String value1, String value2) {
			addCriterion("REGISTER_POSTCARD between", value1, value2,
					"registerPostcard");
			return this;
		}

		public Criteria andRegisterPostcardNotBetween(String value1,
				String value2) {
			addCriterion("REGISTER_POSTCARD not between", value1, value2,
					"registerPostcard");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andOperDateIsNull() {
			addCriterion("OPER_DATE is null");
			return this;
		}

		public Criteria andOperDateIsNotNull() {
			addCriterion("OPER_DATE is not null");
			return this;
		}

		public Criteria andOperDateEqualTo(Date value) {
			addCriterion("OPER_DATE =", value, "operDate");
			return this;
		}

		public Criteria andOperDateNotEqualTo(Date value) {
			addCriterion("OPER_DATE <>", value, "operDate");
			return this;
		}

		public Criteria andOperDateGreaterThan(Date value) {
			addCriterion("OPER_DATE >", value, "operDate");
			return this;
		}

		public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
			addCriterion("OPER_DATE >=", value, "operDate");
			return this;
		}

		public Criteria andOperDateLessThan(Date value) {
			addCriterion("OPER_DATE <", value, "operDate");
			return this;
		}

		public Criteria andOperDateLessThanOrEqualTo(Date value) {
			addCriterion("OPER_DATE <=", value, "operDate");
			return this;
		}

		public Criteria andOperDateIn(List values) {
			addCriterion("OPER_DATE in", values, "operDate");
			return this;
		}

		public Criteria andOperDateNotIn(List values) {
			addCriterion("OPER_DATE not in", values, "operDate");
			return this;
		}

		public Criteria andOperDateBetween(Date value1, Date value2) {
			addCriterion("OPER_DATE between", value1, value2, "operDate");
			return this;
		}

		public Criteria andOperDateNotBetween(Date value1, Date value2) {
			addCriterion("OPER_DATE not between", value1, value2, "operDate");
			return this;
		}

		public Criteria andHasChildrenIsNull() {
			addCriterion("HAS_CHILDREN is null");
			return this;
		}

		public Criteria andHasChildrenIsNotNull() {
			addCriterion("HAS_CHILDREN is not null");
			return this;
		}

		public Criteria andHasChildrenEqualTo(String value) {
			addCriterion("HAS_CHILDREN =", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenNotEqualTo(String value) {
			addCriterion("HAS_CHILDREN <>", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenGreaterThan(String value) {
			addCriterion("HAS_CHILDREN >", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenGreaterThanOrEqualTo(String value) {
			addCriterion("HAS_CHILDREN >=", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenLessThan(String value) {
			addCriterion("HAS_CHILDREN <", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenLessThanOrEqualTo(String value) {
			addCriterion("HAS_CHILDREN <=", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenLike(String value) {
			addCriterion("HAS_CHILDREN like", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenNotLike(String value) {
			addCriterion("HAS_CHILDREN not like", value, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenIn(List values) {
			addCriterion("HAS_CHILDREN in", values, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenNotIn(List values) {
			addCriterion("HAS_CHILDREN not in", values, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenBetween(String value1, String value2) {
			addCriterion("HAS_CHILDREN between", value1, value2, "hasChildren");
			return this;
		}

		public Criteria andHasChildrenNotBetween(String value1, String value2) {
			addCriterion("HAS_CHILDREN not between", value1, value2,
					"hasChildren");
			return this;
		}

		public Criteria andHasHouseIsNull() {
			addCriterion("HAS_HOUSE is null");
			return this;
		}

		public Criteria andHasHouseIsNotNull() {
			addCriterion("HAS_HOUSE is not null");
			return this;
		}

		public Criteria andHasHouseEqualTo(String value) {
			addCriterion("HAS_HOUSE =", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseNotEqualTo(String value) {
			addCriterion("HAS_HOUSE <>", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseGreaterThan(String value) {
			addCriterion("HAS_HOUSE >", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseGreaterThanOrEqualTo(String value) {
			addCriterion("HAS_HOUSE >=", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseLessThan(String value) {
			addCriterion("HAS_HOUSE <", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseLessThanOrEqualTo(String value) {
			addCriterion("HAS_HOUSE <=", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseLike(String value) {
			addCriterion("HAS_HOUSE like", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseNotLike(String value) {
			addCriterion("HAS_HOUSE not like", value, "hasHouse");
			return this;
		}

		public Criteria andHasHouseIn(List values) {
			addCriterion("HAS_HOUSE in", values, "hasHouse");
			return this;
		}

		public Criteria andHasHouseNotIn(List values) {
			addCriterion("HAS_HOUSE not in", values, "hasHouse");
			return this;
		}

		public Criteria andHasHouseBetween(String value1, String value2) {
			addCriterion("HAS_HOUSE between", value1, value2, "hasHouse");
			return this;
		}

		public Criteria andHasHouseNotBetween(String value1, String value2) {
			addCriterion("HAS_HOUSE not between", value1, value2, "hasHouse");
			return this;
		}

		public Criteria andHasCarIsNull() {
			addCriterion("HAS_CAR is null");
			return this;
		}

		public Criteria andHasCarIsNotNull() {
			addCriterion("HAS_CAR is not null");
			return this;
		}

		public Criteria andHasCarEqualTo(String value) {
			addCriterion("HAS_CAR =", value, "hasCar");
			return this;
		}

		public Criteria andHasCarNotEqualTo(String value) {
			addCriterion("HAS_CAR <>", value, "hasCar");
			return this;
		}

		public Criteria andHasCarGreaterThan(String value) {
			addCriterion("HAS_CAR >", value, "hasCar");
			return this;
		}

		public Criteria andHasCarGreaterThanOrEqualTo(String value) {
			addCriterion("HAS_CAR >=", value, "hasCar");
			return this;
		}

		public Criteria andHasCarLessThan(String value) {
			addCriterion("HAS_CAR <", value, "hasCar");
			return this;
		}

		public Criteria andHasCarLessThanOrEqualTo(String value) {
			addCriterion("HAS_CAR <=", value, "hasCar");
			return this;
		}

		public Criteria andHasCarLike(String value) {
			addCriterion("HAS_CAR like", value, "hasCar");
			return this;
		}

		public Criteria andHasCarNotLike(String value) {
			addCriterion("HAS_CAR not like", value, "hasCar");
			return this;
		}

		public Criteria andHasCarIn(List values) {
			addCriterion("HAS_CAR in", values, "hasCar");
			return this;
		}

		public Criteria andHasCarNotIn(List values) {
			addCriterion("HAS_CAR not in", values, "hasCar");
			return this;
		}

		public Criteria andHasCarBetween(String value1, String value2) {
			addCriterion("HAS_CAR between", value1, value2, "hasCar");
			return this;
		}

		public Criteria andHasCarNotBetween(String value1, String value2) {
			addCriterion("HAS_CAR not between", value1, value2, "hasCar");
			return this;
		}

		public Criteria andIsCreditReportIsNull() {
			addCriterion("IS_CREDIT_REPORT is null");
			return this;
		}

		public Criteria andIsCreditReportIsNotNull() {
			addCriterion("IS_CREDIT_REPORT is not null");
			return this;
		}

		public Criteria andIsCreditReportEqualTo(String value) {
			addCriterion("IS_CREDIT_REPORT =", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportNotEqualTo(String value) {
			addCriterion("IS_CREDIT_REPORT <>", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportGreaterThan(String value) {
			addCriterion("IS_CREDIT_REPORT >", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportGreaterThanOrEqualTo(String value) {
			addCriterion("IS_CREDIT_REPORT >=", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportLessThan(String value) {
			addCriterion("IS_CREDIT_REPORT <", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportLessThanOrEqualTo(String value) {
			addCriterion("IS_CREDIT_REPORT <=", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportLike(String value) {
			addCriterion("IS_CREDIT_REPORT like", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportNotLike(String value) {
			addCriterion("IS_CREDIT_REPORT not like", value, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportIn(List values) {
			addCriterion("IS_CREDIT_REPORT in", values, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportNotIn(List values) {
			addCriterion("IS_CREDIT_REPORT not in", values, "isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportBetween(String value1, String value2) {
			addCriterion("IS_CREDIT_REPORT between", value1, value2,
					"isCreditReport");
			return this;
		}

		public Criteria andIsCreditReportNotBetween(String value1, String value2) {
			addCriterion("IS_CREDIT_REPORT not between", value1, value2,
					"isCreditReport");
			return this;
		}

		public Criteria andLoanStateIsNull() {
			addCriterion("LOAN_STATE is null");
			return this;
		}

		public Criteria andLoanStateIsNotNull() {
			addCriterion("LOAN_STATE is not null");
			return this;
		}

		public Criteria andLoanStateEqualTo(String value) {
			addCriterion("LOAN_STATE =", value, "loanState");
			return this;
		}

		public Criteria andLoanStateNotEqualTo(String value) {
			addCriterion("LOAN_STATE <>", value, "loanState");
			return this;
		}

		public Criteria andLoanStateGreaterThan(String value) {
			addCriterion("LOAN_STATE >", value, "loanState");
			return this;
		}

		public Criteria andLoanStateGreaterThanOrEqualTo(String value) {
			addCriterion("LOAN_STATE >=", value, "loanState");
			return this;
		}

		public Criteria andLoanStateLessThan(String value) {
			addCriterion("LOAN_STATE <", value, "loanState");
			return this;
		}

		public Criteria andLoanStateLessThanOrEqualTo(String value) {
			addCriterion("LOAN_STATE <=", value, "loanState");
			return this;
		}

		public Criteria andLoanStateLike(String value) {
			addCriterion("LOAN_STATE like", value, "loanState");
			return this;
		}

		public Criteria andLoanStateNotLike(String value) {
			addCriterion("LOAN_STATE not like", value, "loanState");
			return this;
		}

		public Criteria andLoanStateIn(List values) {
			addCriterion("LOAN_STATE in", values, "loanState");
			return this;
		}

		public Criteria andLoanStateNotIn(List values) {
			addCriterion("LOAN_STATE not in", values, "loanState");
			return this;
		}

		public Criteria andLoanStateBetween(String value1, String value2) {
			addCriterion("LOAN_STATE between", value1, value2, "loanState");
			return this;
		}

		public Criteria andLoanStateNotBetween(String value1, String value2) {
			addCriterion("LOAN_STATE not between", value1, value2, "loanState");
			return this;
		}

		public Criteria andEcifIdIsNull() {
			addCriterion("ECIF_ID is null");
			return this;
		}

		public Criteria andEcifIdIsNotNull() {
			addCriterion("ECIF_ID is not null");
			return this;
		}

		public Criteria andEcifIdEqualTo(String value) {
			addCriterion("ECIF_ID =", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdNotEqualTo(String value) {
			addCriterion("ECIF_ID <>", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdGreaterThan(String value) {
			addCriterion("ECIF_ID >", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdGreaterThanOrEqualTo(String value) {
			addCriterion("ECIF_ID >=", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdLessThan(String value) {
			addCriterion("ECIF_ID <", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdLessThanOrEqualTo(String value) {
			addCriterion("ECIF_ID <=", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdLike(String value) {
			addCriterion("ECIF_ID like", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdNotLike(String value) {
			addCriterion("ECIF_ID not like", value, "ecifId");
			return this;
		}

		public Criteria andEcifIdIn(List values) {
			addCriterion("ECIF_ID in", values, "ecifId");
			return this;
		}

		public Criteria andEcifIdNotIn(List values) {
			addCriterion("ECIF_ID not in", values, "ecifId");
			return this;
		}

		public Criteria andEcifIdBetween(String value1, String value2) {
			addCriterion("ECIF_ID between", value1, value2, "ecifId");
			return this;
		}

		public Criteria andEcifIdNotBetween(String value1, String value2) {
			addCriterion("ECIF_ID not between", value1, value2, "ecifId");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andHistoryFlagIsNull() {
			addCriterion("HISTORY_FLAG is null");
			return this;
		}

		public Criteria andHistoryFlagIsNotNull() {
			addCriterion("HISTORY_FLAG is not null");
			return this;
		}

		public Criteria andHistoryFlagEqualTo(Short value) {
			addCriterion("HISTORY_FLAG =", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagNotEqualTo(Short value) {
			addCriterion("HISTORY_FLAG <>", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagGreaterThan(Short value) {
			addCriterion("HISTORY_FLAG >", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagGreaterThanOrEqualTo(Short value) {
			addCriterion("HISTORY_FLAG >=", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagLessThan(Short value) {
			addCriterion("HISTORY_FLAG <", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagLessThanOrEqualTo(Short value) {
			addCriterion("HISTORY_FLAG <=", value, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagIn(List values) {
			addCriterion("HISTORY_FLAG in", values, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagNotIn(List values) {
			addCriterion("HISTORY_FLAG not in", values, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagBetween(Short value1, Short value2) {
			addCriterion("HISTORY_FLAG between", value1, value2, "historyFlag");
			return this;
		}

		public Criteria andHistoryFlagNotBetween(Short value1, Short value2) {
			addCriterion("HISTORY_FLAG not between", value1, value2,
					"historyFlag");
			return this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("CREATER is null");
			return this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("CREATER is not null");
			return this;
		}

		public Criteria andCreaterEqualTo(Long value) {
			addCriterion("CREATER =", value, "creater");
			return this;
		}

		public Criteria andCreaterNotEqualTo(Long value) {
			addCriterion("CREATER <>", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThan(Long value) {
			addCriterion("CREATER >", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(Long value) {
			addCriterion("CREATER >=", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThan(Long value) {
			addCriterion("CREATER <", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThanOrEqualTo(Long value) {
			addCriterion("CREATER <=", value, "creater");
			return this;
		}

		public Criteria andCreaterIn(List values) {
			addCriterion("CREATER in", values, "creater");
			return this;
		}

		public Criteria andCreaterNotIn(List values) {
			addCriterion("CREATER not in", values, "creater");
			return this;
		}

		public Criteria andCreaterBetween(Long value1, Long value2) {
			addCriterion("CREATER between", value1, value2, "creater");
			return this;
		}

		public Criteria andCreaterNotBetween(Long value1, Long value2) {
			addCriterion("CREATER not between", value1, value2, "creater");
			return this;
		}

		public Criteria andUpdaterPeopleIsNull() {
			addCriterion("UPDATER_PEOPLE is null");
			return this;
		}

		public Criteria andUpdaterPeopleIsNotNull() {
			addCriterion("UPDATER_PEOPLE is not null");
			return this;
		}

		public Criteria andUpdaterPeopleEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE =", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <>", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThan(Long value) {
			addCriterion("UPDATER_PEOPLE >", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE >=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThan(Long value) {
			addCriterion("UPDATER_PEOPLE <", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleIn(List values) {
			addCriterion("UPDATER_PEOPLE in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotIn(List values) {
			addCriterion("UPDATER_PEOPLE not in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE between", value1, value2,
					"updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE not between", value1, value2,
					"updaterPeople");
			return this;
		}
	}
}