package com.creditease.rc.app.sia.vo;

public class BorrowerJobKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_JOB.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	private Long borrowerInfoId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_JOB.JOB_ID
	 * @abatorgenerated
	 */
	private Long jobId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_JOB.BORROWER_INFO_ID
	 * @return  the value of ICP_BORROWER_JOB.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	public Long getBorrowerInfoId() {
		return borrowerInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_JOB.BORROWER_INFO_ID
	 * @param borrowerInfoId  the value for ICP_BORROWER_JOB.BORROWER_INFO_ID
	 * @abatorgenerated
	 */
	public void setBorrowerInfoId(Long borrowerInfoId) {
		this.borrowerInfoId = borrowerInfoId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_JOB.JOB_ID
	 * @return  the value of ICP_BORROWER_JOB.JOB_ID
	 * @abatorgenerated
	 */
	public Long getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_JOB.JOB_ID
	 * @param jobId  the value for ICP_BORROWER_JOB.JOB_ID
	 * @abatorgenerated
	 */
	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}
}