package com.creditease.rc.app.sia.vo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BorrowerLiveinfoExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public BorrowerLiveinfoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	protected BorrowerLiveinfoExample(BorrowerLiveinfoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table ICP_BORROWER_LIVEINFO
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andBorrowerInfoIdIsNull() {
			addCriterion("BORROWER_INFO_ID is null");
			return this;
		}

		public Criteria andBorrowerInfoIdIsNotNull() {
			addCriterion("BORROWER_INFO_ID is not null");
			return this;
		}

		public Criteria andBorrowerInfoIdEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID =", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <>", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThan(Long value) {
			addCriterion("BORROWER_INFO_ID >", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID >=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThan(Long value) {
			addCriterion("BORROWER_INFO_ID <", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdLessThanOrEqualTo(Long value) {
			addCriterion("BORROWER_INFO_ID <=", value, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdIn(List values) {
			addCriterion("BORROWER_INFO_ID in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotIn(List values) {
			addCriterion("BORROWER_INFO_ID not in", values, "borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andBorrowerInfoIdNotBetween(Long value1, Long value2) {
			addCriterion("BORROWER_INFO_ID not between", value1, value2,
					"borrowerInfoId");
			return this;
		}

		public Criteria andLiveIdIsNull() {
			addCriterion("LIVE_ID is null");
			return this;
		}

		public Criteria andLiveIdIsNotNull() {
			addCriterion("LIVE_ID is not null");
			return this;
		}

		public Criteria andLiveIdEqualTo(Long value) {
			addCriterion("LIVE_ID =", value, "liveId");
			return this;
		}

		public Criteria andLiveIdNotEqualTo(Long value) {
			addCriterion("LIVE_ID <>", value, "liveId");
			return this;
		}

		public Criteria andLiveIdGreaterThan(Long value) {
			addCriterion("LIVE_ID >", value, "liveId");
			return this;
		}

		public Criteria andLiveIdGreaterThanOrEqualTo(Long value) {
			addCriterion("LIVE_ID >=", value, "liveId");
			return this;
		}

		public Criteria andLiveIdLessThan(Long value) {
			addCriterion("LIVE_ID <", value, "liveId");
			return this;
		}

		public Criteria andLiveIdLessThanOrEqualTo(Long value) {
			addCriterion("LIVE_ID <=", value, "liveId");
			return this;
		}

		public Criteria andLiveIdIn(List values) {
			addCriterion("LIVE_ID in", values, "liveId");
			return this;
		}

		public Criteria andLiveIdNotIn(List values) {
			addCriterion("LIVE_ID not in", values, "liveId");
			return this;
		}

		public Criteria andLiveIdBetween(Long value1, Long value2) {
			addCriterion("LIVE_ID between", value1, value2, "liveId");
			return this;
		}

		public Criteria andLiveIdNotBetween(Long value1, Long value2) {
			addCriterion("LIVE_ID not between", value1, value2, "liveId");
			return this;
		}

		public Criteria andLiveNatureIsNull() {
			addCriterion("LIVE_NATURE is null");
			return this;
		}

		public Criteria andLiveNatureIsNotNull() {
			addCriterion("LIVE_NATURE is not null");
			return this;
		}

		public Criteria andLiveNatureEqualTo(String value) {
			addCriterion("LIVE_NATURE =", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureNotEqualTo(String value) {
			addCriterion("LIVE_NATURE <>", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureGreaterThan(String value) {
			addCriterion("LIVE_NATURE >", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureGreaterThanOrEqualTo(String value) {
			addCriterion("LIVE_NATURE >=", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureLessThan(String value) {
			addCriterion("LIVE_NATURE <", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureLessThanOrEqualTo(String value) {
			addCriterion("LIVE_NATURE <=", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureLike(String value) {
			addCriterion("LIVE_NATURE like", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureNotLike(String value) {
			addCriterion("LIVE_NATURE not like", value, "liveNature");
			return this;
		}

		public Criteria andLiveNatureIn(List values) {
			addCriterion("LIVE_NATURE in", values, "liveNature");
			return this;
		}

		public Criteria andLiveNatureNotIn(List values) {
			addCriterion("LIVE_NATURE not in", values, "liveNature");
			return this;
		}

		public Criteria andLiveNatureBetween(String value1, String value2) {
			addCriterion("LIVE_NATURE between", value1, value2, "liveNature");
			return this;
		}

		public Criteria andLiveNatureNotBetween(String value1, String value2) {
			addCriterion("LIVE_NATURE not between", value1, value2,
					"liveNature");
			return this;
		}

		public Criteria andLivingStatusIsNull() {
			addCriterion("LIVING_STATUS is null");
			return this;
		}

		public Criteria andLivingStatusIsNotNull() {
			addCriterion("LIVING_STATUS is not null");
			return this;
		}

		public Criteria andLivingStatusEqualTo(String value) {
			addCriterion("LIVING_STATUS =", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusNotEqualTo(String value) {
			addCriterion("LIVING_STATUS <>", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusGreaterThan(String value) {
			addCriterion("LIVING_STATUS >", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusGreaterThanOrEqualTo(String value) {
			addCriterion("LIVING_STATUS >=", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusLessThan(String value) {
			addCriterion("LIVING_STATUS <", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusLessThanOrEqualTo(String value) {
			addCriterion("LIVING_STATUS <=", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusLike(String value) {
			addCriterion("LIVING_STATUS like", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusNotLike(String value) {
			addCriterion("LIVING_STATUS not like", value, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusIn(List values) {
			addCriterion("LIVING_STATUS in", values, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusNotIn(List values) {
			addCriterion("LIVING_STATUS not in", values, "livingStatus");
			return this;
		}

		public Criteria andLivingStatusBetween(String value1, String value2) {
			addCriterion("LIVING_STATUS between", value1, value2,
					"livingStatus");
			return this;
		}

		public Criteria andLivingStatusNotBetween(String value1, String value2) {
			addCriterion("LIVING_STATUS not between", value1, value2,
					"livingStatus");
			return this;
		}

		public Criteria andLivingOtherRemarkIsNull() {
			addCriterion("LIVING_OTHER_REMARK is null");
			return this;
		}

		public Criteria andLivingOtherRemarkIsNotNull() {
			addCriterion("LIVING_OTHER_REMARK is not null");
			return this;
		}

		public Criteria andLivingOtherRemarkEqualTo(String value) {
			addCriterion("LIVING_OTHER_REMARK =", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkNotEqualTo(String value) {
			addCriterion("LIVING_OTHER_REMARK <>", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkGreaterThan(String value) {
			addCriterion("LIVING_OTHER_REMARK >", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("LIVING_OTHER_REMARK >=", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkLessThan(String value) {
			addCriterion("LIVING_OTHER_REMARK <", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkLessThanOrEqualTo(String value) {
			addCriterion("LIVING_OTHER_REMARK <=", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkLike(String value) {
			addCriterion("LIVING_OTHER_REMARK like", value, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkNotLike(String value) {
			addCriterion("LIVING_OTHER_REMARK not like", value,
					"livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkIn(List values) {
			addCriterion("LIVING_OTHER_REMARK in", values, "livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkNotIn(List values) {
			addCriterion("LIVING_OTHER_REMARK not in", values,
					"livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkBetween(String value1, String value2) {
			addCriterion("LIVING_OTHER_REMARK between", value1, value2,
					"livingOtherRemark");
			return this;
		}

		public Criteria andLivingOtherRemarkNotBetween(String value1,
				String value2) {
			addCriterion("LIVING_OTHER_REMARK not between", value1, value2,
					"livingOtherRemark");
			return this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("PROVINCE is null");
			return this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("PROVINCE is not null");
			return this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("PROVINCE =", value, "province");
			return this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("PROVINCE <>", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("PROVINCE >", value, "province");
			return this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("PROVINCE >=", value, "province");
			return this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("PROVINCE <", value, "province");
			return this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("PROVINCE <=", value, "province");
			return this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("PROVINCE like", value, "province");
			return this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("PROVINCE not like", value, "province");
			return this;
		}

		public Criteria andProvinceIn(List values) {
			addCriterion("PROVINCE in", values, "province");
			return this;
		}

		public Criteria andProvinceNotIn(List values) {
			addCriterion("PROVINCE not in", values, "province");
			return this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("PROVINCE between", value1, value2, "province");
			return this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("PROVINCE not between", value1, value2, "province");
			return this;
		}

		public Criteria andCityIsNull() {
			addCriterion("CITY is null");
			return this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("CITY is not null");
			return this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("CITY =", value, "city");
			return this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("CITY <>", value, "city");
			return this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("CITY >", value, "city");
			return this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("CITY >=", value, "city");
			return this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("CITY <", value, "city");
			return this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("CITY <=", value, "city");
			return this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("CITY like", value, "city");
			return this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("CITY not like", value, "city");
			return this;
		}

		public Criteria andCityIn(List values) {
			addCriterion("CITY in", values, "city");
			return this;
		}

		public Criteria andCityNotIn(List values) {
			addCriterion("CITY not in", values, "city");
			return this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("CITY between", value1, value2, "city");
			return this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("CITY not between", value1, value2, "city");
			return this;
		}

		public Criteria andAreaIsNull() {
			addCriterion("AREA is null");
			return this;
		}

		public Criteria andAreaIsNotNull() {
			addCriterion("AREA is not null");
			return this;
		}

		public Criteria andAreaEqualTo(String value) {
			addCriterion("AREA =", value, "area");
			return this;
		}

		public Criteria andAreaNotEqualTo(String value) {
			addCriterion("AREA <>", value, "area");
			return this;
		}

		public Criteria andAreaGreaterThan(String value) {
			addCriterion("AREA >", value, "area");
			return this;
		}

		public Criteria andAreaGreaterThanOrEqualTo(String value) {
			addCriterion("AREA >=", value, "area");
			return this;
		}

		public Criteria andAreaLessThan(String value) {
			addCriterion("AREA <", value, "area");
			return this;
		}

		public Criteria andAreaLessThanOrEqualTo(String value) {
			addCriterion("AREA <=", value, "area");
			return this;
		}

		public Criteria andAreaLike(String value) {
			addCriterion("AREA like", value, "area");
			return this;
		}

		public Criteria andAreaNotLike(String value) {
			addCriterion("AREA not like", value, "area");
			return this;
		}

		public Criteria andAreaIn(List values) {
			addCriterion("AREA in", values, "area");
			return this;
		}

		public Criteria andAreaNotIn(List values) {
			addCriterion("AREA not in", values, "area");
			return this;
		}

		public Criteria andAreaBetween(String value1, String value2) {
			addCriterion("AREA between", value1, value2, "area");
			return this;
		}

		public Criteria andAreaNotBetween(String value1, String value2) {
			addCriterion("AREA not between", value1, value2, "area");
			return this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return this;
		}

		public Criteria andAddressIn(List values) {
			addCriterion("ADDRESS in", values, "address");
			return this;
		}

		public Criteria andAddressNotIn(List values) {
			addCriterion("ADDRESS not in", values, "address");
			return this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return this;
		}

		public Criteria andApplyAddressIsIdentityIsNull() {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY is null");
			return this;
		}

		public Criteria andApplyAddressIsIdentityIsNotNull() {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY is not null");
			return this;
		}

		public Criteria andApplyAddressIsIdentityEqualTo(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY =", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityNotEqualTo(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY <>", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityGreaterThan(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY >", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityGreaterThanOrEqualTo(
				String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY >=", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityLessThan(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY <", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityLessThanOrEqualTo(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY <=", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityLike(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY like", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityNotLike(String value) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY not like", value,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityIn(List values) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY in", values,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityNotIn(List values) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY not in", values,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityBetween(String value1,
				String value2) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY between", value1, value2,
					"applyAddressIsIdentity");
			return this;
		}

		public Criteria andApplyAddressIsIdentityNotBetween(String value1,
				String value2) {
			addCriterion("APPLY_ADDRESS_IS_IDENTITY not between", value1,
					value2, "applyAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityIsNull() {
			addCriterion("NOW_ADDRESS_IS_IDENTITY is null");
			return this;
		}

		public Criteria andNowAddressIsIdentityIsNotNull() {
			addCriterion("NOW_ADDRESS_IS_IDENTITY is not null");
			return this;
		}

		public Criteria andNowAddressIsIdentityEqualTo(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY =", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityNotEqualTo(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY <>", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityGreaterThan(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY >", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityGreaterThanOrEqualTo(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY >=", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityLessThan(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY <", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityLessThanOrEqualTo(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY <=", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityLike(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY like", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityNotLike(String value) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY not like", value,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityIn(List values) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY in", values,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityNotIn(List values) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY not in", values,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityBetween(String value1,
				String value2) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY between", value1, value2,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andNowAddressIsIdentityNotBetween(String value1,
				String value2) {
			addCriterion("NOW_ADDRESS_IS_IDENTITY not between", value1, value2,
					"nowAddressIsIdentity");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andMonthRentIsNull() {
			addCriterion("MONTH_RENT is null");
			return this;
		}

		public Criteria andMonthRentIsNotNull() {
			addCriterion("MONTH_RENT is not null");
			return this;
		}

		public Criteria andMonthRentEqualTo(String value) {
			addCriterion("MONTH_RENT =", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentNotEqualTo(String value) {
			addCriterion("MONTH_RENT <>", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentGreaterThan(String value) {
			addCriterion("MONTH_RENT >", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentGreaterThanOrEqualTo(String value) {
			addCriterion("MONTH_RENT >=", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentLessThan(String value) {
			addCriterion("MONTH_RENT <", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentLessThanOrEqualTo(String value) {
			addCriterion("MONTH_RENT <=", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentLike(String value) {
			addCriterion("MONTH_RENT like", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentNotLike(String value) {
			addCriterion("MONTH_RENT not like", value, "monthRent");
			return this;
		}

		public Criteria andMonthRentIn(List values) {
			addCriterion("MONTH_RENT in", values, "monthRent");
			return this;
		}

		public Criteria andMonthRentNotIn(List values) {
			addCriterion("MONTH_RENT not in", values, "monthRent");
			return this;
		}

		public Criteria andMonthRentBetween(String value1, String value2) {
			addCriterion("MONTH_RENT between", value1, value2, "monthRent");
			return this;
		}

		public Criteria andMonthRentNotBetween(String value1, String value2) {
			addCriterion("MONTH_RENT not between", value1, value2, "monthRent");
			return this;
		}

		public Criteria andStrCustomLngIsNull() {
			addCriterion("STR_CUSTOM_LNG is null");
			return this;
		}

		public Criteria andStrCustomLngIsNotNull() {
			addCriterion("STR_CUSTOM_LNG is not null");
			return this;
		}

		public Criteria andStrCustomLngEqualTo(String value) {
			addCriterion("STR_CUSTOM_LNG =", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngNotEqualTo(String value) {
			addCriterion("STR_CUSTOM_LNG <>", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngGreaterThan(String value) {
			addCriterion("STR_CUSTOM_LNG >", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngGreaterThanOrEqualTo(String value) {
			addCriterion("STR_CUSTOM_LNG >=", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngLessThan(String value) {
			addCriterion("STR_CUSTOM_LNG <", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngLessThanOrEqualTo(String value) {
			addCriterion("STR_CUSTOM_LNG <=", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngLike(String value) {
			addCriterion("STR_CUSTOM_LNG like", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngNotLike(String value) {
			addCriterion("STR_CUSTOM_LNG not like", value, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngIn(List values) {
			addCriterion("STR_CUSTOM_LNG in", values, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngNotIn(List values) {
			addCriterion("STR_CUSTOM_LNG not in", values, "strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngBetween(String value1, String value2) {
			addCriterion("STR_CUSTOM_LNG between", value1, value2,
					"strCustomLng");
			return this;
		}

		public Criteria andStrCustomLngNotBetween(String value1, String value2) {
			addCriterion("STR_CUSTOM_LNG not between", value1, value2,
					"strCustomLng");
			return this;
		}

		public Criteria andStrCustomLatIsNull() {
			addCriterion("STR_CUSTOM_LAT is null");
			return this;
		}

		public Criteria andStrCustomLatIsNotNull() {
			addCriterion("STR_CUSTOM_LAT is not null");
			return this;
		}

		public Criteria andStrCustomLatEqualTo(String value) {
			addCriterion("STR_CUSTOM_LAT =", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatNotEqualTo(String value) {
			addCriterion("STR_CUSTOM_LAT <>", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatGreaterThan(String value) {
			addCriterion("STR_CUSTOM_LAT >", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatGreaterThanOrEqualTo(String value) {
			addCriterion("STR_CUSTOM_LAT >=", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatLessThan(String value) {
			addCriterion("STR_CUSTOM_LAT <", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatLessThanOrEqualTo(String value) {
			addCriterion("STR_CUSTOM_LAT <=", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatLike(String value) {
			addCriterion("STR_CUSTOM_LAT like", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatNotLike(String value) {
			addCriterion("STR_CUSTOM_LAT not like", value, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatIn(List values) {
			addCriterion("STR_CUSTOM_LAT in", values, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatNotIn(List values) {
			addCriterion("STR_CUSTOM_LAT not in", values, "strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatBetween(String value1, String value2) {
			addCriterion("STR_CUSTOM_LAT between", value1, value2,
					"strCustomLat");
			return this;
		}

		public Criteria andStrCustomLatNotBetween(String value1, String value2) {
			addCriterion("STR_CUSTOM_LAT not between", value1, value2,
					"strCustomLat");
			return this;
		}

		public Criteria andRentBeginDateIsNull() {
			addCriterion("RENT_BEGIN_DATE is null");
			return this;
		}

		public Criteria andRentBeginDateIsNotNull() {
			addCriterion("RENT_BEGIN_DATE is not null");
			return this;
		}

		public Criteria andRentBeginDateEqualTo(Date value) {
			addCriterion("RENT_BEGIN_DATE =", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateNotEqualTo(Date value) {
			addCriterion("RENT_BEGIN_DATE <>", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateGreaterThan(Date value) {
			addCriterion("RENT_BEGIN_DATE >", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateGreaterThanOrEqualTo(Date value) {
			addCriterion("RENT_BEGIN_DATE >=", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateLessThan(Date value) {
			addCriterion("RENT_BEGIN_DATE <", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateLessThanOrEqualTo(Date value) {
			addCriterion("RENT_BEGIN_DATE <=", value, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateIn(List values) {
			addCriterion("RENT_BEGIN_DATE in", values, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateNotIn(List values) {
			addCriterion("RENT_BEGIN_DATE not in", values, "rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateBetween(Date value1, Date value2) {
			addCriterion("RENT_BEGIN_DATE between", value1, value2,
					"rentBeginDate");
			return this;
		}

		public Criteria andRentBeginDateNotBetween(Date value1, Date value2) {
			addCriterion("RENT_BEGIN_DATE not between", value1, value2,
					"rentBeginDate");
			return this;
		}

		public Criteria andRentEndDateIsNull() {
			addCriterion("RENT_END_DATE is null");
			return this;
		}

		public Criteria andRentEndDateIsNotNull() {
			addCriterion("RENT_END_DATE is not null");
			return this;
		}

		public Criteria andRentEndDateEqualTo(Date value) {
			addCriterion("RENT_END_DATE =", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateNotEqualTo(Date value) {
			addCriterion("RENT_END_DATE <>", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateGreaterThan(Date value) {
			addCriterion("RENT_END_DATE >", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("RENT_END_DATE >=", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateLessThan(Date value) {
			addCriterion("RENT_END_DATE <", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateLessThanOrEqualTo(Date value) {
			addCriterion("RENT_END_DATE <=", value, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateIn(List values) {
			addCriterion("RENT_END_DATE in", values, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateNotIn(List values) {
			addCriterion("RENT_END_DATE not in", values, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateBetween(Date value1, Date value2) {
			addCriterion("RENT_END_DATE between", value1, value2, "rentEndDate");
			return this;
		}

		public Criteria andRentEndDateNotBetween(Date value1, Date value2) {
			addCriterion("RENT_END_DATE not between", value1, value2,
					"rentEndDate");
			return this;
		}

		public Criteria andAddressTypeIsNull() {
			addCriterion("ADDRESS_TYPE is null");
			return this;
		}

		public Criteria andAddressTypeIsNotNull() {
			addCriterion("ADDRESS_TYPE is not null");
			return this;
		}

		public Criteria andAddressTypeEqualTo(String value) {
			addCriterion("ADDRESS_TYPE =", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeNotEqualTo(String value) {
			addCriterion("ADDRESS_TYPE <>", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeGreaterThan(String value) {
			addCriterion("ADDRESS_TYPE >", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS_TYPE >=", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeLessThan(String value) {
			addCriterion("ADDRESS_TYPE <", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS_TYPE <=", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeLike(String value) {
			addCriterion("ADDRESS_TYPE like", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeNotLike(String value) {
			addCriterion("ADDRESS_TYPE not like", value, "addressType");
			return this;
		}

		public Criteria andAddressTypeIn(List values) {
			addCriterion("ADDRESS_TYPE in", values, "addressType");
			return this;
		}

		public Criteria andAddressTypeNotIn(List values) {
			addCriterion("ADDRESS_TYPE not in", values, "addressType");
			return this;
		}

		public Criteria andAddressTypeBetween(String value1, String value2) {
			addCriterion("ADDRESS_TYPE between", value1, value2, "addressType");
			return this;
		}

		public Criteria andAddressTypeNotBetween(String value1, String value2) {
			addCriterion("ADDRESS_TYPE not between", value1, value2,
					"addressType");
			return this;
		}

		public Criteria andAddressAreaIsNull() {
			addCriterion("ADDRESS_AREA is null");
			return this;
		}

		public Criteria andAddressAreaIsNotNull() {
			addCriterion("ADDRESS_AREA is not null");
			return this;
		}

		public Criteria andAddressAreaEqualTo(Integer value) {
			addCriterion("ADDRESS_AREA =", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaNotEqualTo(Integer value) {
			addCriterion("ADDRESS_AREA <>", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaGreaterThan(Integer value) {
			addCriterion("ADDRESS_AREA >", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ADDRESS_AREA >=", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaLessThan(Integer value) {
			addCriterion("ADDRESS_AREA <", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaLessThanOrEqualTo(Integer value) {
			addCriterion("ADDRESS_AREA <=", value, "addressArea");
			return this;
		}

		public Criteria andAddressAreaIn(List values) {
			addCriterion("ADDRESS_AREA in", values, "addressArea");
			return this;
		}

		public Criteria andAddressAreaNotIn(List values) {
			addCriterion("ADDRESS_AREA not in", values, "addressArea");
			return this;
		}

		public Criteria andAddressAreaBetween(Integer value1, Integer value2) {
			addCriterion("ADDRESS_AREA between", value1, value2, "addressArea");
			return this;
		}

		public Criteria andAddressAreaNotBetween(Integer value1, Integer value2) {
			addCriterion("ADDRESS_AREA not between", value1, value2,
					"addressArea");
			return this;
		}

		public Criteria andLiveYearIsNull() {
			addCriterion("LIVE_YEAR is null");
			return this;
		}

		public Criteria andLiveYearIsNotNull() {
			addCriterion("LIVE_YEAR is not null");
			return this;
		}

		public Criteria andLiveYearEqualTo(BigDecimal value) {
			addCriterion("LIVE_YEAR =", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearNotEqualTo(BigDecimal value) {
			addCriterion("LIVE_YEAR <>", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearGreaterThan(BigDecimal value) {
			addCriterion("LIVE_YEAR >", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LIVE_YEAR >=", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearLessThan(BigDecimal value) {
			addCriterion("LIVE_YEAR <", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LIVE_YEAR <=", value, "liveYear");
			return this;
		}

		public Criteria andLiveYearIn(List values) {
			addCriterion("LIVE_YEAR in", values, "liveYear");
			return this;
		}

		public Criteria andLiveYearNotIn(List values) {
			addCriterion("LIVE_YEAR not in", values, "liveYear");
			return this;
		}

		public Criteria andLiveYearBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LIVE_YEAR between", value1, value2, "liveYear");
			return this;
		}

		public Criteria andLiveYearNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LIVE_YEAR not between", value1, value2, "liveYear");
			return this;
		}

		public Criteria andResidentProvinceIsNull() {
			addCriterion("RESIDENT_PROVINCE is null");
			return this;
		}

		public Criteria andResidentProvinceIsNotNull() {
			addCriterion("RESIDENT_PROVINCE is not null");
			return this;
		}

		public Criteria andResidentProvinceEqualTo(String value) {
			addCriterion("RESIDENT_PROVINCE =", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceNotEqualTo(String value) {
			addCriterion("RESIDENT_PROVINCE <>", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceGreaterThan(String value) {
			addCriterion("RESIDENT_PROVINCE >", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_PROVINCE >=", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceLessThan(String value) {
			addCriterion("RESIDENT_PROVINCE <", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_PROVINCE <=", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceLike(String value) {
			addCriterion("RESIDENT_PROVINCE like", value, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceNotLike(String value) {
			addCriterion("RESIDENT_PROVINCE not like", value,
					"residentProvince");
			return this;
		}

		public Criteria andResidentProvinceIn(List values) {
			addCriterion("RESIDENT_PROVINCE in", values, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceNotIn(List values) {
			addCriterion("RESIDENT_PROVINCE not in", values, "residentProvince");
			return this;
		}

		public Criteria andResidentProvinceBetween(String value1, String value2) {
			addCriterion("RESIDENT_PROVINCE between", value1, value2,
					"residentProvince");
			return this;
		}

		public Criteria andResidentProvinceNotBetween(String value1,
				String value2) {
			addCriterion("RESIDENT_PROVINCE not between", value1, value2,
					"residentProvince");
			return this;
		}

		public Criteria andResidentCityIsNull() {
			addCriterion("RESIDENT_CITY is null");
			return this;
		}

		public Criteria andResidentCityIsNotNull() {
			addCriterion("RESIDENT_CITY is not null");
			return this;
		}

		public Criteria andResidentCityEqualTo(String value) {
			addCriterion("RESIDENT_CITY =", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityNotEqualTo(String value) {
			addCriterion("RESIDENT_CITY <>", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityGreaterThan(String value) {
			addCriterion("RESIDENT_CITY >", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_CITY >=", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityLessThan(String value) {
			addCriterion("RESIDENT_CITY <", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_CITY <=", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityLike(String value) {
			addCriterion("RESIDENT_CITY like", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityNotLike(String value) {
			addCriterion("RESIDENT_CITY not like", value, "residentCity");
			return this;
		}

		public Criteria andResidentCityIn(List values) {
			addCriterion("RESIDENT_CITY in", values, "residentCity");
			return this;
		}

		public Criteria andResidentCityNotIn(List values) {
			addCriterion("RESIDENT_CITY not in", values, "residentCity");
			return this;
		}

		public Criteria andResidentCityBetween(String value1, String value2) {
			addCriterion("RESIDENT_CITY between", value1, value2,
					"residentCity");
			return this;
		}

		public Criteria andResidentCityNotBetween(String value1, String value2) {
			addCriterion("RESIDENT_CITY not between", value1, value2,
					"residentCity");
			return this;
		}

		public Criteria andResidentDistrictIsNull() {
			addCriterion("RESIDENT_DISTRICT is null");
			return this;
		}

		public Criteria andResidentDistrictIsNotNull() {
			addCriterion("RESIDENT_DISTRICT is not null");
			return this;
		}

		public Criteria andResidentDistrictEqualTo(String value) {
			addCriterion("RESIDENT_DISTRICT =", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictNotEqualTo(String value) {
			addCriterion("RESIDENT_DISTRICT <>", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictGreaterThan(String value) {
			addCriterion("RESIDENT_DISTRICT >", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_DISTRICT >=", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictLessThan(String value) {
			addCriterion("RESIDENT_DISTRICT <", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_DISTRICT <=", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictLike(String value) {
			addCriterion("RESIDENT_DISTRICT like", value, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictNotLike(String value) {
			addCriterion("RESIDENT_DISTRICT not like", value,
					"residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictIn(List values) {
			addCriterion("RESIDENT_DISTRICT in", values, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictNotIn(List values) {
			addCriterion("RESIDENT_DISTRICT not in", values, "residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictBetween(String value1, String value2) {
			addCriterion("RESIDENT_DISTRICT between", value1, value2,
					"residentDistrict");
			return this;
		}

		public Criteria andResidentDistrictNotBetween(String value1,
				String value2) {
			addCriterion("RESIDENT_DISTRICT not between", value1, value2,
					"residentDistrict");
			return this;
		}

		public Criteria andFamilyAddressTownIsNull() {
			addCriterion("FAMILY_ADDRESS_TOWN is null");
			return this;
		}

		public Criteria andFamilyAddressTownIsNotNull() {
			addCriterion("FAMILY_ADDRESS_TOWN is not null");
			return this;
		}

		public Criteria andFamilyAddressTownEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN =", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownNotEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN <>", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownGreaterThan(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN >", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownGreaterThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN >=", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownLessThan(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN <", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownLessThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN <=", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownLike(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN like", value, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownNotLike(String value) {
			addCriterion("FAMILY_ADDRESS_TOWN not like", value,
					"familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownIn(List values) {
			addCriterion("FAMILY_ADDRESS_TOWN in", values, "familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownNotIn(List values) {
			addCriterion("FAMILY_ADDRESS_TOWN not in", values,
					"familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownBetween(String value1, String value2) {
			addCriterion("FAMILY_ADDRESS_TOWN between", value1, value2,
					"familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressTownNotBetween(String value1,
				String value2) {
			addCriterion("FAMILY_ADDRESS_TOWN not between", value1, value2,
					"familyAddressTown");
			return this;
		}

		public Criteria andFamilyAddressVillageIsNull() {
			addCriterion("FAMILY_ADDRESS_VILLAGE is null");
			return this;
		}

		public Criteria andFamilyAddressVillageIsNotNull() {
			addCriterion("FAMILY_ADDRESS_VILLAGE is not null");
			return this;
		}

		public Criteria andFamilyAddressVillageEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE =", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageNotEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE <>", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageGreaterThan(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE >", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageGreaterThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE >=", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageLessThan(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE <", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageLessThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE <=", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageLike(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE like", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageNotLike(String value) {
			addCriterion("FAMILY_ADDRESS_VILLAGE not like", value,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageIn(List values) {
			addCriterion("FAMILY_ADDRESS_VILLAGE in", values,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageNotIn(List values) {
			addCriterion("FAMILY_ADDRESS_VILLAGE not in", values,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageBetween(String value1,
				String value2) {
			addCriterion("FAMILY_ADDRESS_VILLAGE between", value1, value2,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressVillageNotBetween(String value1,
				String value2) {
			addCriterion("FAMILY_ADDRESS_VILLAGE not between", value1, value2,
					"familyAddressVillage");
			return this;
		}

		public Criteria andFamilyAddressHousenoIsNull() {
			addCriterion("FAMILY_ADDRESS_HOUSENO is null");
			return this;
		}

		public Criteria andFamilyAddressHousenoIsNotNull() {
			addCriterion("FAMILY_ADDRESS_HOUSENO is not null");
			return this;
		}

		public Criteria andFamilyAddressHousenoEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO =", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoNotEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO <>", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoGreaterThan(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO >", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoGreaterThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO >=", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoLessThan(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO <", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoLessThanOrEqualTo(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO <=", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoLike(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO like", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoNotLike(String value) {
			addCriterion("FAMILY_ADDRESS_HOUSENO not like", value,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoIn(List values) {
			addCriterion("FAMILY_ADDRESS_HOUSENO in", values,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoNotIn(List values) {
			addCriterion("FAMILY_ADDRESS_HOUSENO not in", values,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoBetween(String value1,
				String value2) {
			addCriterion("FAMILY_ADDRESS_HOUSENO between", value1, value2,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andFamilyAddressHousenoNotBetween(String value1,
				String value2) {
			addCriterion("FAMILY_ADDRESS_HOUSENO not between", value1, value2,
					"familyAddressHouseno");
			return this;
		}

		public Criteria andResidentAddrIsNull() {
			addCriterion("RESIDENT_ADDR is null");
			return this;
		}

		public Criteria andResidentAddrIsNotNull() {
			addCriterion("RESIDENT_ADDR is not null");
			return this;
		}

		public Criteria andResidentAddrEqualTo(String value) {
			addCriterion("RESIDENT_ADDR =", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrNotEqualTo(String value) {
			addCriterion("RESIDENT_ADDR <>", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrGreaterThan(String value) {
			addCriterion("RESIDENT_ADDR >", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_ADDR >=", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrLessThan(String value) {
			addCriterion("RESIDENT_ADDR <", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_ADDR <=", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrLike(String value) {
			addCriterion("RESIDENT_ADDR like", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrNotLike(String value) {
			addCriterion("RESIDENT_ADDR not like", value, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrIn(List values) {
			addCriterion("RESIDENT_ADDR in", values, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrNotIn(List values) {
			addCriterion("RESIDENT_ADDR not in", values, "residentAddr");
			return this;
		}

		public Criteria andResidentAddrBetween(String value1, String value2) {
			addCriterion("RESIDENT_ADDR between", value1, value2,
					"residentAddr");
			return this;
		}

		public Criteria andResidentAddrNotBetween(String value1, String value2) {
			addCriterion("RESIDENT_ADDR not between", value1, value2,
					"residentAddr");
			return this;
		}

		public Criteria andResidentTelAreacodeIsNull() {
			addCriterion("RESIDENT_TEL_AREACODE is null");
			return this;
		}

		public Criteria andResidentTelAreacodeIsNotNull() {
			addCriterion("RESIDENT_TEL_AREACODE is not null");
			return this;
		}

		public Criteria andResidentTelAreacodeEqualTo(String value) {
			addCriterion("RESIDENT_TEL_AREACODE =", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeNotEqualTo(String value) {
			addCriterion("RESIDENT_TEL_AREACODE <>", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeGreaterThan(String value) {
			addCriterion("RESIDENT_TEL_AREACODE >", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_TEL_AREACODE >=", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeLessThan(String value) {
			addCriterion("RESIDENT_TEL_AREACODE <", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_TEL_AREACODE <=", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeLike(String value) {
			addCriterion("RESIDENT_TEL_AREACODE like", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeNotLike(String value) {
			addCriterion("RESIDENT_TEL_AREACODE not like", value,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeIn(List values) {
			addCriterion("RESIDENT_TEL_AREACODE in", values,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeNotIn(List values) {
			addCriterion("RESIDENT_TEL_AREACODE not in", values,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeBetween(String value1,
				String value2) {
			addCriterion("RESIDENT_TEL_AREACODE between", value1, value2,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelAreacodeNotBetween(String value1,
				String value2) {
			addCriterion("RESIDENT_TEL_AREACODE not between", value1, value2,
					"residentTelAreacode");
			return this;
		}

		public Criteria andResidentTelNumberIsNull() {
			addCriterion("RESIDENT_TEL_NUMBER is null");
			return this;
		}

		public Criteria andResidentTelNumberIsNotNull() {
			addCriterion("RESIDENT_TEL_NUMBER is not null");
			return this;
		}

		public Criteria andResidentTelNumberEqualTo(String value) {
			addCriterion("RESIDENT_TEL_NUMBER =", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberNotEqualTo(String value) {
			addCriterion("RESIDENT_TEL_NUMBER <>", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberGreaterThan(String value) {
			addCriterion("RESIDENT_TEL_NUMBER >", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberGreaterThanOrEqualTo(String value) {
			addCriterion("RESIDENT_TEL_NUMBER >=", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberLessThan(String value) {
			addCriterion("RESIDENT_TEL_NUMBER <", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberLessThanOrEqualTo(String value) {
			addCriterion("RESIDENT_TEL_NUMBER <=", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberLike(String value) {
			addCriterion("RESIDENT_TEL_NUMBER like", value, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberNotLike(String value) {
			addCriterion("RESIDENT_TEL_NUMBER not like", value,
					"residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberIn(List values) {
			addCriterion("RESIDENT_TEL_NUMBER in", values, "residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberNotIn(List values) {
			addCriterion("RESIDENT_TEL_NUMBER not in", values,
					"residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberBetween(String value1, String value2) {
			addCriterion("RESIDENT_TEL_NUMBER between", value1, value2,
					"residentTelNumber");
			return this;
		}

		public Criteria andResidentTelNumberNotBetween(String value1,
				String value2) {
			addCriterion("RESIDENT_TEL_NUMBER not between", value1, value2,
					"residentTelNumber");
			return this;
		}

		public Criteria andLiveStartDateIsNull() {
			addCriterion("LIVE_START_DATE is null");
			return this;
		}

		public Criteria andLiveStartDateIsNotNull() {
			addCriterion("LIVE_START_DATE is not null");
			return this;
		}

		public Criteria andLiveStartDateEqualTo(Date value) {
			addCriterion("LIVE_START_DATE =", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateNotEqualTo(Date value) {
			addCriterion("LIVE_START_DATE <>", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateGreaterThan(Date value) {
			addCriterion("LIVE_START_DATE >", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateGreaterThanOrEqualTo(Date value) {
			addCriterion("LIVE_START_DATE >=", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateLessThan(Date value) {
			addCriterion("LIVE_START_DATE <", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateLessThanOrEqualTo(Date value) {
			addCriterion("LIVE_START_DATE <=", value, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateIn(List values) {
			addCriterion("LIVE_START_DATE in", values, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateNotIn(List values) {
			addCriterion("LIVE_START_DATE not in", values, "liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateBetween(Date value1, Date value2) {
			addCriterion("LIVE_START_DATE between", value1, value2,
					"liveStartDate");
			return this;
		}

		public Criteria andLiveStartDateNotBetween(Date value1, Date value2) {
			addCriterion("LIVE_START_DATE not between", value1, value2,
					"liveStartDate");
			return this;
		}

		public Criteria andSupportPersonsIsNull() {
			addCriterion("SUPPORT_PERSONS is null");
			return this;
		}

		public Criteria andSupportPersonsIsNotNull() {
			addCriterion("SUPPORT_PERSONS is not null");
			return this;
		}

		public Criteria andSupportPersonsEqualTo(Short value) {
			addCriterion("SUPPORT_PERSONS =", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsNotEqualTo(Short value) {
			addCriterion("SUPPORT_PERSONS <>", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsGreaterThan(Short value) {
			addCriterion("SUPPORT_PERSONS >", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsGreaterThanOrEqualTo(Short value) {
			addCriterion("SUPPORT_PERSONS >=", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsLessThan(Short value) {
			addCriterion("SUPPORT_PERSONS <", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsLessThanOrEqualTo(Short value) {
			addCriterion("SUPPORT_PERSONS <=", value, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsIn(List values) {
			addCriterion("SUPPORT_PERSONS in", values, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsNotIn(List values) {
			addCriterion("SUPPORT_PERSONS not in", values, "supportPersons");
			return this;
		}

		public Criteria andSupportPersonsBetween(Short value1, Short value2) {
			addCriterion("SUPPORT_PERSONS between", value1, value2,
					"supportPersons");
			return this;
		}

		public Criteria andSupportPersonsNotBetween(Short value1, Short value2) {
			addCriterion("SUPPORT_PERSONS not between", value1, value2,
					"supportPersons");
			return this;
		}

		public Criteria andChildNumIsNull() {
			addCriterion("CHILD_NUM is null");
			return this;
		}

		public Criteria andChildNumIsNotNull() {
			addCriterion("CHILD_NUM is not null");
			return this;
		}

		public Criteria andChildNumEqualTo(Short value) {
			addCriterion("CHILD_NUM =", value, "childNum");
			return this;
		}

		public Criteria andChildNumNotEqualTo(Short value) {
			addCriterion("CHILD_NUM <>", value, "childNum");
			return this;
		}

		public Criteria andChildNumGreaterThan(Short value) {
			addCriterion("CHILD_NUM >", value, "childNum");
			return this;
		}

		public Criteria andChildNumGreaterThanOrEqualTo(Short value) {
			addCriterion("CHILD_NUM >=", value, "childNum");
			return this;
		}

		public Criteria andChildNumLessThan(Short value) {
			addCriterion("CHILD_NUM <", value, "childNum");
			return this;
		}

		public Criteria andChildNumLessThanOrEqualTo(Short value) {
			addCriterion("CHILD_NUM <=", value, "childNum");
			return this;
		}

		public Criteria andChildNumIn(List values) {
			addCriterion("CHILD_NUM in", values, "childNum");
			return this;
		}

		public Criteria andChildNumNotIn(List values) {
			addCriterion("CHILD_NUM not in", values, "childNum");
			return this;
		}

		public Criteria andChildNumBetween(Short value1, Short value2) {
			addCriterion("CHILD_NUM between", value1, value2, "childNum");
			return this;
		}

		public Criteria andChildNumNotBetween(Short value1, Short value2) {
			addCriterion("CHILD_NUM not between", value1, value2, "childNum");
			return this;
		}

		public Criteria andTogetherLiverIsNull() {
			addCriterion("TOGETHER_LIVER is null");
			return this;
		}

		public Criteria andTogetherLiverIsNotNull() {
			addCriterion("TOGETHER_LIVER is not null");
			return this;
		}

		public Criteria andTogetherLiverEqualTo(String value) {
			addCriterion("TOGETHER_LIVER =", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverNotEqualTo(String value) {
			addCriterion("TOGETHER_LIVER <>", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverGreaterThan(String value) {
			addCriterion("TOGETHER_LIVER >", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverGreaterThanOrEqualTo(String value) {
			addCriterion("TOGETHER_LIVER >=", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverLessThan(String value) {
			addCriterion("TOGETHER_LIVER <", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverLessThanOrEqualTo(String value) {
			addCriterion("TOGETHER_LIVER <=", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverLike(String value) {
			addCriterion("TOGETHER_LIVER like", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverNotLike(String value) {
			addCriterion("TOGETHER_LIVER not like", value, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverIn(List values) {
			addCriterion("TOGETHER_LIVER in", values, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverNotIn(List values) {
			addCriterion("TOGETHER_LIVER not in", values, "togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverBetween(String value1, String value2) {
			addCriterion("TOGETHER_LIVER between", value1, value2,
					"togetherLiver");
			return this;
		}

		public Criteria andTogetherLiverNotBetween(String value1, String value2) {
			addCriterion("TOGETHER_LIVER not between", value1, value2,
					"togetherLiver");
			return this;
		}

		public Criteria andLiveTimesIsNull() {
			addCriterion("LIVE_TIMES is null");
			return this;
		}

		public Criteria andLiveTimesIsNotNull() {
			addCriterion("LIVE_TIMES is not null");
			return this;
		}

		public Criteria andLiveTimesEqualTo(BigDecimal value) {
			addCriterion("LIVE_TIMES =", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesNotEqualTo(BigDecimal value) {
			addCriterion("LIVE_TIMES <>", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesGreaterThan(BigDecimal value) {
			addCriterion("LIVE_TIMES >", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LIVE_TIMES >=", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesLessThan(BigDecimal value) {
			addCriterion("LIVE_TIMES <", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LIVE_TIMES <=", value, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesIn(List values) {
			addCriterion("LIVE_TIMES in", values, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesNotIn(List values) {
			addCriterion("LIVE_TIMES not in", values, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LIVE_TIMES between", value1, value2, "liveTimes");
			return this;
		}

		public Criteria andLiveTimesNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LIVE_TIMES not between", value1, value2, "liveTimes");
			return this;
		}

		public Criteria andStartYearIsNull() {
			addCriterion("START_YEAR is null");
			return this;
		}

		public Criteria andStartYearIsNotNull() {
			addCriterion("START_YEAR is not null");
			return this;
		}

		public Criteria andStartYearEqualTo(Date value) {
			addCriterion("START_YEAR =", value, "startYear");
			return this;
		}

		public Criteria andStartYearNotEqualTo(Date value) {
			addCriterion("START_YEAR <>", value, "startYear");
			return this;
		}

		public Criteria andStartYearGreaterThan(Date value) {
			addCriterion("START_YEAR >", value, "startYear");
			return this;
		}

		public Criteria andStartYearGreaterThanOrEqualTo(Date value) {
			addCriterion("START_YEAR >=", value, "startYear");
			return this;
		}

		public Criteria andStartYearLessThan(Date value) {
			addCriterion("START_YEAR <", value, "startYear");
			return this;
		}

		public Criteria andStartYearLessThanOrEqualTo(Date value) {
			addCriterion("START_YEAR <=", value, "startYear");
			return this;
		}

		public Criteria andStartYearIn(List values) {
			addCriterion("START_YEAR in", values, "startYear");
			return this;
		}

		public Criteria andStartYearNotIn(List values) {
			addCriterion("START_YEAR not in", values, "startYear");
			return this;
		}

		public Criteria andStartYearBetween(Date value1, Date value2) {
			addCriterion("START_YEAR between", value1, value2, "startYear");
			return this;
		}

		public Criteria andStartYearNotBetween(Date value1, Date value2) {
			addCriterion("START_YEAR not between", value1, value2, "startYear");
			return this;
		}

		public Criteria andValidTimeIsNull() {
			addCriterion("VALID_TIME is null");
			return this;
		}

		public Criteria andValidTimeIsNotNull() {
			addCriterion("VALID_TIME is not null");
			return this;
		}

		public Criteria andValidTimeEqualTo(BigDecimal value) {
			addCriterion("VALID_TIME =", value, "validTime");
			return this;
		}

		public Criteria andValidTimeNotEqualTo(BigDecimal value) {
			addCriterion("VALID_TIME <>", value, "validTime");
			return this;
		}

		public Criteria andValidTimeGreaterThan(BigDecimal value) {
			addCriterion("VALID_TIME >", value, "validTime");
			return this;
		}

		public Criteria andValidTimeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("VALID_TIME >=", value, "validTime");
			return this;
		}

		public Criteria andValidTimeLessThan(BigDecimal value) {
			addCriterion("VALID_TIME <", value, "validTime");
			return this;
		}

		public Criteria andValidTimeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("VALID_TIME <=", value, "validTime");
			return this;
		}

		public Criteria andValidTimeIn(List values) {
			addCriterion("VALID_TIME in", values, "validTime");
			return this;
		}

		public Criteria andValidTimeNotIn(List values) {
			addCriterion("VALID_TIME not in", values, "validTime");
			return this;
		}

		public Criteria andValidTimeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("VALID_TIME between", value1, value2, "validTime");
			return this;
		}

		public Criteria andValidTimeNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("VALID_TIME not between", value1, value2, "validTime");
			return this;
		}

		public Criteria andValidLimitTimeIsNull() {
			addCriterion("VALID_LIMIT_TIME is null");
			return this;
		}

		public Criteria andValidLimitTimeIsNotNull() {
			addCriterion("VALID_LIMIT_TIME is not null");
			return this;
		}

		public Criteria andValidLimitTimeEqualTo(Date value) {
			addCriterion("VALID_LIMIT_TIME =", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeNotEqualTo(Date value) {
			addCriterion("VALID_LIMIT_TIME <>", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeGreaterThan(Date value) {
			addCriterion("VALID_LIMIT_TIME >", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("VALID_LIMIT_TIME >=", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeLessThan(Date value) {
			addCriterion("VALID_LIMIT_TIME <", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeLessThanOrEqualTo(Date value) {
			addCriterion("VALID_LIMIT_TIME <=", value, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeIn(List values) {
			addCriterion("VALID_LIMIT_TIME in", values, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeNotIn(List values) {
			addCriterion("VALID_LIMIT_TIME not in", values, "validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeBetween(Date value1, Date value2) {
			addCriterion("VALID_LIMIT_TIME between", value1, value2,
					"validLimitTime");
			return this;
		}

		public Criteria andValidLimitTimeNotBetween(Date value1, Date value2) {
			addCriterion("VALID_LIMIT_TIME not between", value1, value2,
					"validLimitTime");
			return this;
		}

		public Criteria andLiveAddressPostCardIsNull() {
			addCriterion("LIVE_ADDRESS_POST_CARD is null");
			return this;
		}

		public Criteria andLiveAddressPostCardIsNotNull() {
			addCriterion("LIVE_ADDRESS_POST_CARD is not null");
			return this;
		}

		public Criteria andLiveAddressPostCardEqualTo(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD =", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardNotEqualTo(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD <>", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardGreaterThan(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD >", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardGreaterThanOrEqualTo(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD >=", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardLessThan(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD <", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardLessThanOrEqualTo(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD <=", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardLike(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD like", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardNotLike(String value) {
			addCriterion("LIVE_ADDRESS_POST_CARD not like", value,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardIn(List values) {
			addCriterion("LIVE_ADDRESS_POST_CARD in", values,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardNotIn(List values) {
			addCriterion("LIVE_ADDRESS_POST_CARD not in", values,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardBetween(String value1,
				String value2) {
			addCriterion("LIVE_ADDRESS_POST_CARD between", value1, value2,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andLiveAddressPostCardNotBetween(String value1,
				String value2) {
			addCriterion("LIVE_ADDRESS_POST_CARD not between", value1, value2,
					"liveAddressPostCard");
			return this;
		}

		public Criteria andPostCd2IsNull() {
			addCriterion("POST_CD_2 is null");
			return this;
		}

		public Criteria andPostCd2IsNotNull() {
			addCriterion("POST_CD_2 is not null");
			return this;
		}

		public Criteria andPostCd2EqualTo(String value) {
			addCriterion("POST_CD_2 =", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2NotEqualTo(String value) {
			addCriterion("POST_CD_2 <>", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2GreaterThan(String value) {
			addCriterion("POST_CD_2 >", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2GreaterThanOrEqualTo(String value) {
			addCriterion("POST_CD_2 >=", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2LessThan(String value) {
			addCriterion("POST_CD_2 <", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2LessThanOrEqualTo(String value) {
			addCriterion("POST_CD_2 <=", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2Like(String value) {
			addCriterion("POST_CD_2 like", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2NotLike(String value) {
			addCriterion("POST_CD_2 not like", value, "postCd2");
			return this;
		}

		public Criteria andPostCd2In(List values) {
			addCriterion("POST_CD_2 in", values, "postCd2");
			return this;
		}

		public Criteria andPostCd2NotIn(List values) {
			addCriterion("POST_CD_2 not in", values, "postCd2");
			return this;
		}

		public Criteria andPostCd2Between(String value1, String value2) {
			addCriterion("POST_CD_2 between", value1, value2, "postCd2");
			return this;
		}

		public Criteria andPostCd2NotBetween(String value1, String value2) {
			addCriterion("POST_CD_2 not between", value1, value2, "postCd2");
			return this;
		}

		public Criteria andPostCd1IsNull() {
			addCriterion("POST_CD_1 is null");
			return this;
		}

		public Criteria andPostCd1IsNotNull() {
			addCriterion("POST_CD_1 is not null");
			return this;
		}

		public Criteria andPostCd1EqualTo(String value) {
			addCriterion("POST_CD_1 =", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1NotEqualTo(String value) {
			addCriterion("POST_CD_1 <>", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1GreaterThan(String value) {
			addCriterion("POST_CD_1 >", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1GreaterThanOrEqualTo(String value) {
			addCriterion("POST_CD_1 >=", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1LessThan(String value) {
			addCriterion("POST_CD_1 <", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1LessThanOrEqualTo(String value) {
			addCriterion("POST_CD_1 <=", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1Like(String value) {
			addCriterion("POST_CD_1 like", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1NotLike(String value) {
			addCriterion("POST_CD_1 not like", value, "postCd1");
			return this;
		}

		public Criteria andPostCd1In(List values) {
			addCriterion("POST_CD_1 in", values, "postCd1");
			return this;
		}

		public Criteria andPostCd1NotIn(List values) {
			addCriterion("POST_CD_1 not in", values, "postCd1");
			return this;
		}

		public Criteria andPostCd1Between(String value1, String value2) {
			addCriterion("POST_CD_1 between", value1, value2, "postCd1");
			return this;
		}

		public Criteria andPostCd1NotBetween(String value1, String value2) {
			addCriterion("POST_CD_1 not between", value1, value2, "postCd1");
			return this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("CREATER is null");
			return this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("CREATER is not null");
			return this;
		}

		public Criteria andCreaterEqualTo(Long value) {
			addCriterion("CREATER =", value, "creater");
			return this;
		}

		public Criteria andCreaterNotEqualTo(Long value) {
			addCriterion("CREATER <>", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThan(Long value) {
			addCriterion("CREATER >", value, "creater");
			return this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(Long value) {
			addCriterion("CREATER >=", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThan(Long value) {
			addCriterion("CREATER <", value, "creater");
			return this;
		}

		public Criteria andCreaterLessThanOrEqualTo(Long value) {
			addCriterion("CREATER <=", value, "creater");
			return this;
		}

		public Criteria andCreaterIn(List values) {
			addCriterion("CREATER in", values, "creater");
			return this;
		}

		public Criteria andCreaterNotIn(List values) {
			addCriterion("CREATER not in", values, "creater");
			return this;
		}

		public Criteria andCreaterBetween(Long value1, Long value2) {
			addCriterion("CREATER between", value1, value2, "creater");
			return this;
		}

		public Criteria andCreaterNotBetween(Long value1, Long value2) {
			addCriterion("CREATER not between", value1, value2, "creater");
			return this;
		}

		public Criteria andUpdaterPeopleIsNull() {
			addCriterion("UPDATER_PEOPLE is null");
			return this;
		}

		public Criteria andUpdaterPeopleIsNotNull() {
			addCriterion("UPDATER_PEOPLE is not null");
			return this;
		}

		public Criteria andUpdaterPeopleEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE =", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <>", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThan(Long value) {
			addCriterion("UPDATER_PEOPLE >", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleGreaterThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE >=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThan(Long value) {
			addCriterion("UPDATER_PEOPLE <", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleLessThanOrEqualTo(Long value) {
			addCriterion("UPDATER_PEOPLE <=", value, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleIn(List values) {
			addCriterion("UPDATER_PEOPLE in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotIn(List values) {
			addCriterion("UPDATER_PEOPLE not in", values, "updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE between", value1, value2,
					"updaterPeople");
			return this;
		}

		public Criteria andUpdaterPeopleNotBetween(Long value1, Long value2) {
			addCriterion("UPDATER_PEOPLE not between", value1, value2,
					"updaterPeople");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}
	}
}