package com.creditease.rc.app.sia.vo;

import java.math.BigDecimal;
import java.util.Date;

public class BorrowerHouse extends BorrowerHouseKey {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RELATION
	 * @abatorgenerated
	 */
	private String relation;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.MATE_HAS_HOUSE
	 * @abatorgenerated
	 */
	private String mateHasHouse;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.MONTH_REPAYMENT
	 * @abatorgenerated
	 */
	private BigDecimal monthRepayment;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.BORROW_SORT
	 * @abatorgenerated
	 */
	private String borrowSort;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HAS_HOUSING_LOAN
	 * @abatorgenerated
	 */
	private String hasHousingLoan;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.BUY_DATE
	 * @abatorgenerated
	 */
	private Date buyDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.LIVE_SITUATION
	 * @abatorgenerated
	 */
	private String liveSituation;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.STATE
	 * @abatorgenerated
	 */
	private String state;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE
	 * @abatorgenerated
	 */
	private String houseOwnerType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE_DESC
	 * @abatorgenerated
	 */
	private String houseOwnerTypeDesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_APPLAY
	 * @abatorgenerated
	 */
	private String isSameWithApplay;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_LIVE
	 * @abatorgenerated
	 */
	private String isSameWithLive;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.LIVE_CASE
	 * @abatorgenerated
	 */
	private String liveCase;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RENTAL_FEE
	 * @abatorgenerated
	 */
	private BigDecimal rentalFee;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_NAME
	 * @abatorgenerated
	 */
	private String houseName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_CASE
	 * @abatorgenerated
	 */
	private BigDecimal houseCase;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_STATE
	 * @abatorgenerated
	 */
	private String houseState;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_NATURE
	 * @abatorgenerated
	 */
	private String houseNature;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_PURPOSE
	 * @abatorgenerated
	 */
	private String housePurpose;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.NATURE
	 * @abatorgenerated
	 */
	private String nature;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.ROOM_NUM
	 * @abatorgenerated
	 */
	private Long roomNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.ROOM_NUM1
	 * @abatorgenerated
	 */
	private Long roomNum1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.THE_FLOOR
	 * @abatorgenerated
	 */
	private Short theFloor;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.TOTAL_FLOOR
	 * @abatorgenerated
	 */
	private Short totalFloor;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.COHABIT_RELA
	 * @abatorgenerated
	 */
	private String cohabitRela;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RELATIONSHIP
	 * @abatorgenerated
	 */
	private String relationship;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.OTHER_HOUSE_OWNER_TYPEDESC
	 * @abatorgenerated
	 */
	private String otherHouseOwnerTypedesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.TYPE
	 * @abatorgenerated
	 */
	private String type;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.MONTH_PAY
	 * @abatorgenerated
	 */
	private BigDecimal monthPay;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_AREA
	 * @abatorgenerated
	 */
	private BigDecimal houseArea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.PROVINCE
	 * @abatorgenerated
	 */
	private String province;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.CITY
	 * @abatorgenerated
	 */
	private String city;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.AREA
	 * @abatorgenerated
	 */
	private String area;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.ADDRESS
	 * @abatorgenerated
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.PROVINCE2
	 * @abatorgenerated
	 */
	private String province2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.CITY2
	 * @abatorgenerated
	 */
	private String city2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.AREA2
	 * @abatorgenerated
	 */
	private String area2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.ZIP_CODE
	 * @abatorgenerated
	 */
	private String zipCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.HOUSE_TYPE_DESC
	 * @abatorgenerated
	 */
	private String houseTypeDesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.ADDRESS2
	 * @abatorgenerated
	 */
	private String address2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.STRUCTURE
	 * @abatorgenerated
	 */
	private String structure;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.COMPLETE_YEAR
	 * @abatorgenerated
	 */
	private String completeYear;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO
	 * @abatorgenerated
	 */
	private String righterCertno;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO2
	 * @abatorgenerated
	 */
	private String righterCertno2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.BANK_LOAN_CASE
	 * @abatorgenerated
	 */
	private String bankLoanCase;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.LOAN_BANK
	 * @abatorgenerated
	 */
	private String loanBank;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.LOAN_AMOUNT
	 * @abatorgenerated
	 */
	private BigDecimal loanAmount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.PLEDGE_CASE
	 * @abatorgenerated
	 */
	private String pledgeCase;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RIGHTER
	 * @abatorgenerated
	 */
	private String righter;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.RIGHTER_NUM
	 * @abatorgenerated
	 */
	private Short righterNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.VALID_NUM
	 * @abatorgenerated
	 */
	private Short validNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.LIVE_NATURE
	 * @abatorgenerated
	 */
	private String liveNature;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.MEMO
	 * @abatorgenerated
	 */
	private String memo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.CREATER
	 * @abatorgenerated
	 */
	private Long creater;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	private Long updaterPeople;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.CREATE_TIME
	 * @abatorgenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ICP_BORROWER_HOUSE.UPDATE_TIME
	 * @abatorgenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RELATION
	 * @return  the value of ICP_BORROWER_HOUSE.RELATION
	 * @abatorgenerated
	 */
	public String getRelation() {
		return relation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RELATION
	 * @param relation  the value for ICP_BORROWER_HOUSE.RELATION
	 * @abatorgenerated
	 */
	public void setRelation(String relation) {
		this.relation = relation == null ? null : relation.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.MATE_HAS_HOUSE
	 * @return  the value of ICP_BORROWER_HOUSE.MATE_HAS_HOUSE
	 * @abatorgenerated
	 */
	public String getMateHasHouse() {
		return mateHasHouse;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.MATE_HAS_HOUSE
	 * @param mateHasHouse  the value for ICP_BORROWER_HOUSE.MATE_HAS_HOUSE
	 * @abatorgenerated
	 */
	public void setMateHasHouse(String mateHasHouse) {
		this.mateHasHouse = mateHasHouse == null ? null : mateHasHouse.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.MONTH_REPAYMENT
	 * @return  the value of ICP_BORROWER_HOUSE.MONTH_REPAYMENT
	 * @abatorgenerated
	 */
	public BigDecimal getMonthRepayment() {
		return monthRepayment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.MONTH_REPAYMENT
	 * @param monthRepayment  the value for ICP_BORROWER_HOUSE.MONTH_REPAYMENT
	 * @abatorgenerated
	 */
	public void setMonthRepayment(BigDecimal monthRepayment) {
		this.monthRepayment = monthRepayment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.BORROW_SORT
	 * @return  the value of ICP_BORROWER_HOUSE.BORROW_SORT
	 * @abatorgenerated
	 */
	public String getBorrowSort() {
		return borrowSort;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.BORROW_SORT
	 * @param borrowSort  the value for ICP_BORROWER_HOUSE.BORROW_SORT
	 * @abatorgenerated
	 */
	public void setBorrowSort(String borrowSort) {
		this.borrowSort = borrowSort == null ? null : borrowSort.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HAS_HOUSING_LOAN
	 * @return  the value of ICP_BORROWER_HOUSE.HAS_HOUSING_LOAN
	 * @abatorgenerated
	 */
	public String getHasHousingLoan() {
		return hasHousingLoan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HAS_HOUSING_LOAN
	 * @param hasHousingLoan  the value for ICP_BORROWER_HOUSE.HAS_HOUSING_LOAN
	 * @abatorgenerated
	 */
	public void setHasHousingLoan(String hasHousingLoan) {
		this.hasHousingLoan = hasHousingLoan == null ? null : hasHousingLoan
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.BUY_DATE
	 * @return  the value of ICP_BORROWER_HOUSE.BUY_DATE
	 * @abatorgenerated
	 */
	public Date getBuyDate() {
		return buyDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.BUY_DATE
	 * @param buyDate  the value for ICP_BORROWER_HOUSE.BUY_DATE
	 * @abatorgenerated
	 */
	public void setBuyDate(Date buyDate) {
		this.buyDate = buyDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.LIVE_SITUATION
	 * @return  the value of ICP_BORROWER_HOUSE.LIVE_SITUATION
	 * @abatorgenerated
	 */
	public String getLiveSituation() {
		return liveSituation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.LIVE_SITUATION
	 * @param liveSituation  the value for ICP_BORROWER_HOUSE.LIVE_SITUATION
	 * @abatorgenerated
	 */
	public void setLiveSituation(String liveSituation) {
		this.liveSituation = liveSituation == null ? null : liveSituation
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.STATE
	 * @return  the value of ICP_BORROWER_HOUSE.STATE
	 * @abatorgenerated
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.STATE
	 * @param state  the value for ICP_BORROWER_HOUSE.STATE
	 * @abatorgenerated
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE
	 * @abatorgenerated
	 */
	public String getHouseOwnerType() {
		return houseOwnerType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE
	 * @param houseOwnerType  the value for ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE
	 * @abatorgenerated
	 */
	public void setHouseOwnerType(String houseOwnerType) {
		this.houseOwnerType = houseOwnerType == null ? null : houseOwnerType
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE_DESC
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE_DESC
	 * @abatorgenerated
	 */
	public String getHouseOwnerTypeDesc() {
		return houseOwnerTypeDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE_DESC
	 * @param houseOwnerTypeDesc  the value for ICP_BORROWER_HOUSE.HOUSE_OWNER_TYPE_DESC
	 * @abatorgenerated
	 */
	public void setHouseOwnerTypeDesc(String houseOwnerTypeDesc) {
		this.houseOwnerTypeDesc = houseOwnerTypeDesc == null ? null
				: houseOwnerTypeDesc.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_APPLAY
	 * @return  the value of ICP_BORROWER_HOUSE.IS_SAME_WITH_APPLAY
	 * @abatorgenerated
	 */
	public String getIsSameWithApplay() {
		return isSameWithApplay;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_APPLAY
	 * @param isSameWithApplay  the value for ICP_BORROWER_HOUSE.IS_SAME_WITH_APPLAY
	 * @abatorgenerated
	 */
	public void setIsSameWithApplay(String isSameWithApplay) {
		this.isSameWithApplay = isSameWithApplay == null ? null
				: isSameWithApplay.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_LIVE
	 * @return  the value of ICP_BORROWER_HOUSE.IS_SAME_WITH_LIVE
	 * @abatorgenerated
	 */
	public String getIsSameWithLive() {
		return isSameWithLive;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.IS_SAME_WITH_LIVE
	 * @param isSameWithLive  the value for ICP_BORROWER_HOUSE.IS_SAME_WITH_LIVE
	 * @abatorgenerated
	 */
	public void setIsSameWithLive(String isSameWithLive) {
		this.isSameWithLive = isSameWithLive == null ? null : isSameWithLive
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.LIVE_CASE
	 * @return  the value of ICP_BORROWER_HOUSE.LIVE_CASE
	 * @abatorgenerated
	 */
	public String getLiveCase() {
		return liveCase;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.LIVE_CASE
	 * @param liveCase  the value for ICP_BORROWER_HOUSE.LIVE_CASE
	 * @abatorgenerated
	 */
	public void setLiveCase(String liveCase) {
		this.liveCase = liveCase == null ? null : liveCase.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RENTAL_FEE
	 * @return  the value of ICP_BORROWER_HOUSE.RENTAL_FEE
	 * @abatorgenerated
	 */
	public BigDecimal getRentalFee() {
		return rentalFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RENTAL_FEE
	 * @param rentalFee  the value for ICP_BORROWER_HOUSE.RENTAL_FEE
	 * @abatorgenerated
	 */
	public void setRentalFee(BigDecimal rentalFee) {
		this.rentalFee = rentalFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_NAME
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_NAME
	 * @abatorgenerated
	 */
	public String getHouseName() {
		return houseName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_NAME
	 * @param houseName  the value for ICP_BORROWER_HOUSE.HOUSE_NAME
	 * @abatorgenerated
	 */
	public void setHouseName(String houseName) {
		this.houseName = houseName == null ? null : houseName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_CASE
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_CASE
	 * @abatorgenerated
	 */
	public BigDecimal getHouseCase() {
		return houseCase;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_CASE
	 * @param houseCase  the value for ICP_BORROWER_HOUSE.HOUSE_CASE
	 * @abatorgenerated
	 */
	public void setHouseCase(BigDecimal houseCase) {
		this.houseCase = houseCase;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_STATE
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_STATE
	 * @abatorgenerated
	 */
	public String getHouseState() {
		return houseState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_STATE
	 * @param houseState  the value for ICP_BORROWER_HOUSE.HOUSE_STATE
	 * @abatorgenerated
	 */
	public void setHouseState(String houseState) {
		this.houseState = houseState == null ? null : houseState.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_NATURE
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_NATURE
	 * @abatorgenerated
	 */
	public String getHouseNature() {
		return houseNature;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_NATURE
	 * @param houseNature  the value for ICP_BORROWER_HOUSE.HOUSE_NATURE
	 * @abatorgenerated
	 */
	public void setHouseNature(String houseNature) {
		this.houseNature = houseNature == null ? null : houseNature.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_PURPOSE
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_PURPOSE
	 * @abatorgenerated
	 */
	public String getHousePurpose() {
		return housePurpose;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_PURPOSE
	 * @param housePurpose  the value for ICP_BORROWER_HOUSE.HOUSE_PURPOSE
	 * @abatorgenerated
	 */
	public void setHousePurpose(String housePurpose) {
		this.housePurpose = housePurpose == null ? null : housePurpose.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.NATURE
	 * @return  the value of ICP_BORROWER_HOUSE.NATURE
	 * @abatorgenerated
	 */
	public String getNature() {
		return nature;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.NATURE
	 * @param nature  the value for ICP_BORROWER_HOUSE.NATURE
	 * @abatorgenerated
	 */
	public void setNature(String nature) {
		this.nature = nature == null ? null : nature.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.ROOM_NUM
	 * @return  the value of ICP_BORROWER_HOUSE.ROOM_NUM
	 * @abatorgenerated
	 */
	public Long getRoomNum() {
		return roomNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.ROOM_NUM
	 * @param roomNum  the value for ICP_BORROWER_HOUSE.ROOM_NUM
	 * @abatorgenerated
	 */
	public void setRoomNum(Long roomNum) {
		this.roomNum = roomNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.ROOM_NUM1
	 * @return  the value of ICP_BORROWER_HOUSE.ROOM_NUM1
	 * @abatorgenerated
	 */
	public Long getRoomNum1() {
		return roomNum1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.ROOM_NUM1
	 * @param roomNum1  the value for ICP_BORROWER_HOUSE.ROOM_NUM1
	 * @abatorgenerated
	 */
	public void setRoomNum1(Long roomNum1) {
		this.roomNum1 = roomNum1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.THE_FLOOR
	 * @return  the value of ICP_BORROWER_HOUSE.THE_FLOOR
	 * @abatorgenerated
	 */
	public Short getTheFloor() {
		return theFloor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.THE_FLOOR
	 * @param theFloor  the value for ICP_BORROWER_HOUSE.THE_FLOOR
	 * @abatorgenerated
	 */
	public void setTheFloor(Short theFloor) {
		this.theFloor = theFloor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.TOTAL_FLOOR
	 * @return  the value of ICP_BORROWER_HOUSE.TOTAL_FLOOR
	 * @abatorgenerated
	 */
	public Short getTotalFloor() {
		return totalFloor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.TOTAL_FLOOR
	 * @param totalFloor  the value for ICP_BORROWER_HOUSE.TOTAL_FLOOR
	 * @abatorgenerated
	 */
	public void setTotalFloor(Short totalFloor) {
		this.totalFloor = totalFloor;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.COHABIT_RELA
	 * @return  the value of ICP_BORROWER_HOUSE.COHABIT_RELA
	 * @abatorgenerated
	 */
	public String getCohabitRela() {
		return cohabitRela;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.COHABIT_RELA
	 * @param cohabitRela  the value for ICP_BORROWER_HOUSE.COHABIT_RELA
	 * @abatorgenerated
	 */
	public void setCohabitRela(String cohabitRela) {
		this.cohabitRela = cohabitRela == null ? null : cohabitRela.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RELATIONSHIP
	 * @return  the value of ICP_BORROWER_HOUSE.RELATIONSHIP
	 * @abatorgenerated
	 */
	public String getRelationship() {
		return relationship;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RELATIONSHIP
	 * @param relationship  the value for ICP_BORROWER_HOUSE.RELATIONSHIP
	 * @abatorgenerated
	 */
	public void setRelationship(String relationship) {
		this.relationship = relationship == null ? null : relationship.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.OTHER_HOUSE_OWNER_TYPEDESC
	 * @return  the value of ICP_BORROWER_HOUSE.OTHER_HOUSE_OWNER_TYPEDESC
	 * @abatorgenerated
	 */
	public String getOtherHouseOwnerTypedesc() {
		return otherHouseOwnerTypedesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.OTHER_HOUSE_OWNER_TYPEDESC
	 * @param otherHouseOwnerTypedesc  the value for ICP_BORROWER_HOUSE.OTHER_HOUSE_OWNER_TYPEDESC
	 * @abatorgenerated
	 */
	public void setOtherHouseOwnerTypedesc(String otherHouseOwnerTypedesc) {
		this.otherHouseOwnerTypedesc = otherHouseOwnerTypedesc == null ? null
				: otherHouseOwnerTypedesc.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.TYPE
	 * @return  the value of ICP_BORROWER_HOUSE.TYPE
	 * @abatorgenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.TYPE
	 * @param type  the value for ICP_BORROWER_HOUSE.TYPE
	 * @abatorgenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.MONTH_PAY
	 * @return  the value of ICP_BORROWER_HOUSE.MONTH_PAY
	 * @abatorgenerated
	 */
	public BigDecimal getMonthPay() {
		return monthPay;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.MONTH_PAY
	 * @param monthPay  the value for ICP_BORROWER_HOUSE.MONTH_PAY
	 * @abatorgenerated
	 */
	public void setMonthPay(BigDecimal monthPay) {
		this.monthPay = monthPay;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_AREA
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_AREA
	 * @abatorgenerated
	 */
	public BigDecimal getHouseArea() {
		return houseArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_AREA
	 * @param houseArea  the value for ICP_BORROWER_HOUSE.HOUSE_AREA
	 * @abatorgenerated
	 */
	public void setHouseArea(BigDecimal houseArea) {
		this.houseArea = houseArea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.PROVINCE
	 * @return  the value of ICP_BORROWER_HOUSE.PROVINCE
	 * @abatorgenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.PROVINCE
	 * @param province  the value for ICP_BORROWER_HOUSE.PROVINCE
	 * @abatorgenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.CITY
	 * @return  the value of ICP_BORROWER_HOUSE.CITY
	 * @abatorgenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.CITY
	 * @param city  the value for ICP_BORROWER_HOUSE.CITY
	 * @abatorgenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.AREA
	 * @return  the value of ICP_BORROWER_HOUSE.AREA
	 * @abatorgenerated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.AREA
	 * @param area  the value for ICP_BORROWER_HOUSE.AREA
	 * @abatorgenerated
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.ADDRESS
	 * @return  the value of ICP_BORROWER_HOUSE.ADDRESS
	 * @abatorgenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.ADDRESS
	 * @param address  the value for ICP_BORROWER_HOUSE.ADDRESS
	 * @abatorgenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.PROVINCE2
	 * @return  the value of ICP_BORROWER_HOUSE.PROVINCE2
	 * @abatorgenerated
	 */
	public String getProvince2() {
		return province2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.PROVINCE2
	 * @param province2  the value for ICP_BORROWER_HOUSE.PROVINCE2
	 * @abatorgenerated
	 */
	public void setProvince2(String province2) {
		this.province2 = province2 == null ? null : province2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.CITY2
	 * @return  the value of ICP_BORROWER_HOUSE.CITY2
	 * @abatorgenerated
	 */
	public String getCity2() {
		return city2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.CITY2
	 * @param city2  the value for ICP_BORROWER_HOUSE.CITY2
	 * @abatorgenerated
	 */
	public void setCity2(String city2) {
		this.city2 = city2 == null ? null : city2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.AREA2
	 * @return  the value of ICP_BORROWER_HOUSE.AREA2
	 * @abatorgenerated
	 */
	public String getArea2() {
		return area2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.AREA2
	 * @param area2  the value for ICP_BORROWER_HOUSE.AREA2
	 * @abatorgenerated
	 */
	public void setArea2(String area2) {
		this.area2 = area2 == null ? null : area2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.ZIP_CODE
	 * @return  the value of ICP_BORROWER_HOUSE.ZIP_CODE
	 * @abatorgenerated
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.ZIP_CODE
	 * @param zipCode  the value for ICP_BORROWER_HOUSE.ZIP_CODE
	 * @abatorgenerated
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode == null ? null : zipCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.HOUSE_TYPE_DESC
	 * @return  the value of ICP_BORROWER_HOUSE.HOUSE_TYPE_DESC
	 * @abatorgenerated
	 */
	public String getHouseTypeDesc() {
		return houseTypeDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.HOUSE_TYPE_DESC
	 * @param houseTypeDesc  the value for ICP_BORROWER_HOUSE.HOUSE_TYPE_DESC
	 * @abatorgenerated
	 */
	public void setHouseTypeDesc(String houseTypeDesc) {
		this.houseTypeDesc = houseTypeDesc == null ? null : houseTypeDesc
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.ADDRESS2
	 * @return  the value of ICP_BORROWER_HOUSE.ADDRESS2
	 * @abatorgenerated
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.ADDRESS2
	 * @param address2  the value for ICP_BORROWER_HOUSE.ADDRESS2
	 * @abatorgenerated
	 */
	public void setAddress2(String address2) {
		this.address2 = address2 == null ? null : address2.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.STRUCTURE
	 * @return  the value of ICP_BORROWER_HOUSE.STRUCTURE
	 * @abatorgenerated
	 */
	public String getStructure() {
		return structure;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.STRUCTURE
	 * @param structure  the value for ICP_BORROWER_HOUSE.STRUCTURE
	 * @abatorgenerated
	 */
	public void setStructure(String structure) {
		this.structure = structure == null ? null : structure.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.COMPLETE_YEAR
	 * @return  the value of ICP_BORROWER_HOUSE.COMPLETE_YEAR
	 * @abatorgenerated
	 */
	public String getCompleteYear() {
		return completeYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.COMPLETE_YEAR
	 * @param completeYear  the value for ICP_BORROWER_HOUSE.COMPLETE_YEAR
	 * @abatorgenerated
	 */
	public void setCompleteYear(String completeYear) {
		this.completeYear = completeYear == null ? null : completeYear.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO
	 * @return  the value of ICP_BORROWER_HOUSE.RIGHTER_CERTNO
	 * @abatorgenerated
	 */
	public String getRighterCertno() {
		return righterCertno;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO
	 * @param righterCertno  the value for ICP_BORROWER_HOUSE.RIGHTER_CERTNO
	 * @abatorgenerated
	 */
	public void setRighterCertno(String righterCertno) {
		this.righterCertno = righterCertno == null ? null : righterCertno
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO2
	 * @return  the value of ICP_BORROWER_HOUSE.RIGHTER_CERTNO2
	 * @abatorgenerated
	 */
	public String getRighterCertno2() {
		return righterCertno2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RIGHTER_CERTNO2
	 * @param righterCertno2  the value for ICP_BORROWER_HOUSE.RIGHTER_CERTNO2
	 * @abatorgenerated
	 */
	public void setRighterCertno2(String righterCertno2) {
		this.righterCertno2 = righterCertno2 == null ? null : righterCertno2
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.BANK_LOAN_CASE
	 * @return  the value of ICP_BORROWER_HOUSE.BANK_LOAN_CASE
	 * @abatorgenerated
	 */
	public String getBankLoanCase() {
		return bankLoanCase;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.BANK_LOAN_CASE
	 * @param bankLoanCase  the value for ICP_BORROWER_HOUSE.BANK_LOAN_CASE
	 * @abatorgenerated
	 */
	public void setBankLoanCase(String bankLoanCase) {
		this.bankLoanCase = bankLoanCase == null ? null : bankLoanCase.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.LOAN_BANK
	 * @return  the value of ICP_BORROWER_HOUSE.LOAN_BANK
	 * @abatorgenerated
	 */
	public String getLoanBank() {
		return loanBank;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.LOAN_BANK
	 * @param loanBank  the value for ICP_BORROWER_HOUSE.LOAN_BANK
	 * @abatorgenerated
	 */
	public void setLoanBank(String loanBank) {
		this.loanBank = loanBank == null ? null : loanBank.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.LOAN_AMOUNT
	 * @return  the value of ICP_BORROWER_HOUSE.LOAN_AMOUNT
	 * @abatorgenerated
	 */
	public BigDecimal getLoanAmount() {
		return loanAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.LOAN_AMOUNT
	 * @param loanAmount  the value for ICP_BORROWER_HOUSE.LOAN_AMOUNT
	 * @abatorgenerated
	 */
	public void setLoanAmount(BigDecimal loanAmount) {
		this.loanAmount = loanAmount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.PLEDGE_CASE
	 * @return  the value of ICP_BORROWER_HOUSE.PLEDGE_CASE
	 * @abatorgenerated
	 */
	public String getPledgeCase() {
		return pledgeCase;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.PLEDGE_CASE
	 * @param pledgeCase  the value for ICP_BORROWER_HOUSE.PLEDGE_CASE
	 * @abatorgenerated
	 */
	public void setPledgeCase(String pledgeCase) {
		this.pledgeCase = pledgeCase == null ? null : pledgeCase.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RIGHTER
	 * @return  the value of ICP_BORROWER_HOUSE.RIGHTER
	 * @abatorgenerated
	 */
	public String getRighter() {
		return righter;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RIGHTER
	 * @param righter  the value for ICP_BORROWER_HOUSE.RIGHTER
	 * @abatorgenerated
	 */
	public void setRighter(String righter) {
		this.righter = righter == null ? null : righter.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.RIGHTER_NUM
	 * @return  the value of ICP_BORROWER_HOUSE.RIGHTER_NUM
	 * @abatorgenerated
	 */
	public Short getRighterNum() {
		return righterNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.RIGHTER_NUM
	 * @param righterNum  the value for ICP_BORROWER_HOUSE.RIGHTER_NUM
	 * @abatorgenerated
	 */
	public void setRighterNum(Short righterNum) {
		this.righterNum = righterNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.VALID_NUM
	 * @return  the value of ICP_BORROWER_HOUSE.VALID_NUM
	 * @abatorgenerated
	 */
	public Short getValidNum() {
		return validNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.VALID_NUM
	 * @param validNum  the value for ICP_BORROWER_HOUSE.VALID_NUM
	 * @abatorgenerated
	 */
	public void setValidNum(Short validNum) {
		this.validNum = validNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.LIVE_NATURE
	 * @return  the value of ICP_BORROWER_HOUSE.LIVE_NATURE
	 * @abatorgenerated
	 */
	public String getLiveNature() {
		return liveNature;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.LIVE_NATURE
	 * @param liveNature  the value for ICP_BORROWER_HOUSE.LIVE_NATURE
	 * @abatorgenerated
	 */
	public void setLiveNature(String liveNature) {
		this.liveNature = liveNature == null ? null : liveNature.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.MEMO
	 * @return  the value of ICP_BORROWER_HOUSE.MEMO
	 * @abatorgenerated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.MEMO
	 * @param memo  the value for ICP_BORROWER_HOUSE.MEMO
	 * @abatorgenerated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.CREATER
	 * @return  the value of ICP_BORROWER_HOUSE.CREATER
	 * @abatorgenerated
	 */
	public Long getCreater() {
		return creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.CREATER
	 * @param creater  the value for ICP_BORROWER_HOUSE.CREATER
	 * @abatorgenerated
	 */
	public void setCreater(Long creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.UPDATER_PEOPLE
	 * @return  the value of ICP_BORROWER_HOUSE.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	public Long getUpdaterPeople() {
		return updaterPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.UPDATER_PEOPLE
	 * @param updaterPeople  the value for ICP_BORROWER_HOUSE.UPDATER_PEOPLE
	 * @abatorgenerated
	 */
	public void setUpdaterPeople(Long updaterPeople) {
		this.updaterPeople = updaterPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.CREATE_TIME
	 * @return  the value of ICP_BORROWER_HOUSE.CREATE_TIME
	 * @abatorgenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.CREATE_TIME
	 * @param createTime  the value for ICP_BORROWER_HOUSE.CREATE_TIME
	 * @abatorgenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ICP_BORROWER_HOUSE.UPDATE_TIME
	 * @return  the value of ICP_BORROWER_HOUSE.UPDATE_TIME
	 * @abatorgenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ICP_BORROWER_HOUSE.UPDATE_TIME
	 * @param updateTime  the value for ICP_BORROWER_HOUSE.UPDATE_TIME
	 * @abatorgenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}