package com.creditease.rc.app.sia.vo;

import java.util.ArrayList;
import java.util.Date;

public class EnterpriseCustomer {
	private ArrayList<EnterpriseProduct> mappingList;
    public ArrayList<EnterpriseProduct> getMappingList() {
		return mappingList;
	}

	public void setMappingList(ArrayList<EnterpriseProduct> mappingList) {
		this.mappingList = mappingList;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.HIS_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long hisId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.PARENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long parentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CUS_CODE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String cusCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CUS_NAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String cusName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.PRODUCT_LINE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long productLine;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.SIGN_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Date signTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.ORPERATION_BEGINDATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Date orperationBegindate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CORPERATION_ENDTIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Date corperationEndtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.SALERNAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String salername;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.SALEPHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String salephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String contactperson;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON_PHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String contactpersonPhone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String legalRepresentative;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE_IDCARD
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String legalRepresentativeIdcard;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.IS_ENTERPRISE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String isEnterprise;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.AREA_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long areaDepartmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CITY_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long cityDepartmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.AREA_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long areaId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.DEALER_LEVEL
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String dealerLevel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.STATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private String state;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.OPERATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long operateId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.OPERATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Date operateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CREATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Long createId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column TC_ENTERPRISE_CUSTOMER.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    private Date createTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.ID
     *
     * @param id the value for TC_ENTERPRISE_CUSTOMER.ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.HIS_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.HIS_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getHisId() {
        return hisId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.HIS_ID
     *
     * @param hisId the value for TC_ENTERPRISE_CUSTOMER.HIS_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setHisId(Long hisId) {
        this.hisId = hisId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.PARENT_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.PARENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.PARENT_ID
     *
     * @param parentId the value for TC_ENTERPRISE_CUSTOMER.PARENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CUS_CODE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CUS_CODE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getCusCode() {
        return cusCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CUS_CODE
     *
     * @param cusCode the value for TC_ENTERPRISE_CUSTOMER.CUS_CODE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCusCode(String cusCode) {
        this.cusCode = cusCode == null ? null : cusCode.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CUS_NAME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CUS_NAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getCusName() {
        return cusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CUS_NAME
     *
     * @param cusName the value for TC_ENTERPRISE_CUSTOMER.CUS_NAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCusName(String cusName) {
        this.cusName = cusName == null ? null : cusName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.PRODUCT_LINE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.PRODUCT_LINE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.PRODUCT_LINE
     *
     * @param productLine the value for TC_ENTERPRISE_CUSTOMER.PRODUCT_LINE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setProductLine(Long productLine) {
        this.productLine = productLine;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.SIGN_TIME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.SIGN_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.SIGN_TIME
     *
     * @param signTime the value for TC_ENTERPRISE_CUSTOMER.SIGN_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.ORPERATION_BEGINDATE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.ORPERATION_BEGINDATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Date getOrperationBegindate() {
        return orperationBegindate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.ORPERATION_BEGINDATE
     *
     * @param orperationBegindate the value for TC_ENTERPRISE_CUSTOMER.ORPERATION_BEGINDATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setOrperationBegindate(Date orperationBegindate) {
        this.orperationBegindate = orperationBegindate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CORPERATION_ENDTIME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CORPERATION_ENDTIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Date getCorperationEndtime() {
        return corperationEndtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CORPERATION_ENDTIME
     *
     * @param corperationEndtime the value for TC_ENTERPRISE_CUSTOMER.CORPERATION_ENDTIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCorperationEndtime(Date corperationEndtime) {
        this.corperationEndtime = corperationEndtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.SALERNAME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.SALERNAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getSalername() {
        return salername;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.SALERNAME
     *
     * @param salername the value for TC_ENTERPRISE_CUSTOMER.SALERNAME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setSalername(String salername) {
        this.salername = salername == null ? null : salername.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.SALEPHONE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.SALEPHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getSalephone() {
        return salephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.SALEPHONE
     *
     * @param salephone the value for TC_ENTERPRISE_CUSTOMER.SALEPHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setSalephone(String salephone) {
        this.salephone = salephone == null ? null : salephone.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CONTACTPERSON
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON
     *
     * @param contactperson the value for TC_ENTERPRISE_CUSTOMER.CONTACTPERSON
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON_PHONE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CONTACTPERSON_PHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getContactpersonPhone() {
        return contactpersonPhone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CONTACTPERSON_PHONE
     *
     * @param contactpersonPhone the value for TC_ENTERPRISE_CUSTOMER.CONTACTPERSON_PHONE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setContactpersonPhone(String contactpersonPhone) {
        this.contactpersonPhone = contactpersonPhone == null ? null : contactpersonPhone.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE
     *
     * @param legalRepresentative the value for TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative == null ? null : legalRepresentative.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE_IDCARD
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE_IDCARD
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getLegalRepresentativeIdcard() {
        return legalRepresentativeIdcard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE_IDCARD
     *
     * @param legalRepresentativeIdcard the value for TC_ENTERPRISE_CUSTOMER.LEGAL_REPRESENTATIVE_IDCARD
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setLegalRepresentativeIdcard(String legalRepresentativeIdcard) {
        this.legalRepresentativeIdcard = legalRepresentativeIdcard == null ? null : legalRepresentativeIdcard.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.IS_ENTERPRISE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.IS_ENTERPRISE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.IS_ENTERPRISE
     *
     * @param isEnterprise the value for TC_ENTERPRISE_CUSTOMER.IS_ENTERPRISE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setIsEnterprise(String isEnterprise) {
        this.isEnterprise = isEnterprise == null ? null : isEnterprise.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.AREA_DEPARTMENT_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.AREA_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getAreaDepartmentId() {
        return areaDepartmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.AREA_DEPARTMENT_ID
     *
     * @param areaDepartmentId the value for TC_ENTERPRISE_CUSTOMER.AREA_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setAreaDepartmentId(Long areaDepartmentId) {
        this.areaDepartmentId = areaDepartmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CITY_DEPARTMENT_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CITY_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getCityDepartmentId() {
        return cityDepartmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CITY_DEPARTMENT_ID
     *
     * @param cityDepartmentId the value for TC_ENTERPRISE_CUSTOMER.CITY_DEPARTMENT_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCityDepartmentId(Long cityDepartmentId) {
        this.cityDepartmentId = cityDepartmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.AREA_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.AREA_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.AREA_ID
     *
     * @param areaId the value for TC_ENTERPRISE_CUSTOMER.AREA_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.DEALER_LEVEL
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.DEALER_LEVEL
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getDealerLevel() {
        return dealerLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.DEALER_LEVEL
     *
     * @param dealerLevel the value for TC_ENTERPRISE_CUSTOMER.DEALER_LEVEL
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setDealerLevel(String dealerLevel) {
        this.dealerLevel = dealerLevel == null ? null : dealerLevel.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.STATE
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.STATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.STATE
     *
     * @param state the value for TC_ENTERPRISE_CUSTOMER.STATE
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.OPERATE_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.OPERATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.OPERATE_ID
     *
     * @param operateId the value for TC_ENTERPRISE_CUSTOMER.OPERATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setOperateId(Long operateId) {
        this.operateId = operateId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.OPERATE_TIME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.OPERATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.OPERATE_TIME
     *
     * @param operateTime the value for TC_ENTERPRISE_CUSTOMER.OPERATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CREATE_ID
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CREATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CREATE_ID
     *
     * @param createId the value for TC_ENTERPRISE_CUSTOMER.CREATE_ID
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column TC_ENTERPRISE_CUSTOMER.CREATE_TIME
     *
     * @return the value of TC_ENTERPRISE_CUSTOMER.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column TC_ENTERPRISE_CUSTOMER.CREATE_TIME
     *
     * @param createTime the value for TC_ENTERPRISE_CUSTOMER.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 15 11:39:18 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}