package com.creditease.rc.framework.dao.impl;

import java.util.Map;

import org.springframework.stereotype.Repository;

import com.creditease.rc.dao.SpaceDAO;
import com.creditease.rc.domain.Space;
import com.creditease.rc.framework.pager.Pagination;

@Repository
public class SpaceDAOImpl extends BaseDao implements SpaceDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public SpaceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public Long insert(Space record) {
        Object newKey = getSqlMapClientTemplate().insert("RL_SPACE.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKey(Space record) {
        int rows = getSqlMapClientTemplate().update("RL_SPACE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(Space record) {
        int rows = getSqlMapClientTemplate().update("RL_SPACE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public Space selectByPrimaryKey(Long spaceid) {
        Space key = new Space();
        key.setSpaceid(spaceid);
        Space record = (Space) getSqlMapClientTemplate().queryForObject("RL_SPACE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_SPACE
     *
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long spaceid) {
        Space key = new Space();
        key.setSpaceid(spaceid);
        int rows = getSqlMapClientTemplate().delete("RL_SPACE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public Pagination selectSpaceList(Map<String, Object> map,Pagination pagination) {
		return queryForPaginatedList("RL_SPACE.selectSpaceList", "RL_SPACE.selectSpaceListCount", map,pagination.getStartResult(), pagination.getPageSize());
	}

	@Override
	public int updateSpaceStud(String value) {
		return update("RL_SPACE.updateSpaceStud", value);
	}

	@Override
	public int saveExecuteSpace(Space space) {
		// TODO Auto-generated method stub
		return update("RL_SPACE.abatorgenerated_updateByPrimaryKeySelective", space);
	}

	@Override
	public Pagination downloadExcel(Map<String, Object> map,
			Pagination pagination) {
		
		return queryForPaginatedList("RL_SPACE.downloadExcelList", "RL_SPACE.downloadExcelListCount", map,pagination.getStartResult(), pagination.getPageSize());
	}
}