package com.creditease.rc.dao.impl;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

import com.creditease.rc.dao.ICreditHistoryDAO;
import com.creditease.rc.domain.CreditHistory;
import com.creditease.rc.framework.dao.IBaseDao;
import com.creditease.rc.framework.dao.impl.BaseDao;

/**
 * 
 * @author haoqiang
 * 
 */
@Repository
public class CreditHistoryDAOImpl extends BaseDao implements ICreditHistoryDAO {

	@Resource
	private IBaseDao baseDao;

	public IBaseDao getBaseDao() {
		return baseDao;
	}

	public void setBaseDao(IBaseDao baseDao) {
		this.baseDao = baseDao;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method corresponds to the database table RL_CREDIT_HISTORY
	 * 
	 * @abatorgenerated
	 */
	public CreditHistoryDAOImpl() {
		super();
	}

	/**
	 * 
	 * @param record CreditHistory对象
	 */
	public void insert(CreditHistory record) {
		baseDao.insert("RL_CREDIT_HISTORY.abatorgenerated_insert", record);
	}

	/**
	 * 
	 * @param record CreditHistory对象
	 * @return 更新的条数
	 */
	public int updateByPrimaryKey(CreditHistory record) {
		int rows = baseDao.update("RL_CREDIT_HISTORY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * 
	 * @param record CreditHistory对象
	 * @return 更新的条数
	 */
	public int updateByPrimaryKeySelective(CreditHistory record) {
		int rows = baseDao.update("RL_CREDIT_HISTORY.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * 
	 * @param creditHistoryId 主键
	 * @return CreditHistory对象
	 */
	public CreditHistory selectByPrimaryKey(Long creditHistoryId) {
		CreditHistory key = new CreditHistory();
		key.setCreditHistoryId(creditHistoryId);
		CreditHistory record = (CreditHistory) baseDao.queryUnique(
				"RL_CREDIT_HISTORY.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * 
	 * @param creditHistoryId 主键
	 * @return 删除的条数
	 */
	public int deleteByPrimaryKey(Long creditHistoryId) {
		CreditHistory key = new CreditHistory();
		key.setCreditHistoryId(creditHistoryId);
		int rows = baseDao.delete("RL_CREDIT_HISTORY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

}