package com.creditease.rc.dao.impl;

import java.util.List;
import java.util.Map;


import org.springframework.stereotype.Repository;

import com.creditease.rc.dao.EmployeeDAO;
import com.creditease.rc.domain.Employee;
import com.creditease.rc.framework.dao.impl.BaseDao;
import com.creditease.rc.framework.pager.Pagination;
@Repository
public class EmployeeDAOImpl extends BaseDao implements EmployeeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public EmployeeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public Long insert(Employee record) {
        Object newKey = getSqlMapClientTemplate().insert("RL_EMPLOYEE.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKey(Employee record) {
        int rows = getSqlMapClientTemplate().update("RL_EMPLOYEE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(Employee record) {
        int rows = getSqlMapClientTemplate().update("RL_EMPLOYEE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public Employee selectByPrimaryKey(Long employeeId) {
        Employee key = new Employee();
        key.setEmployeeId(employeeId);
        Employee record = (Employee) getSqlMapClientTemplate().queryForObject("RL_EMPLOYEE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE
     *
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long employeeId) {
        Employee key = new Employee();
        key.setEmployeeId(employeeId);
        int rows = getSqlMapClientTemplate().delete("RL_EMPLOYEE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public Pagination selectAllCollection(Pagination pagination,
			Map<String, Object> map) {
		return queryForPaginatedList("RL_EMPLOYEE.selectAll", "RL_EMPLOYEE.selectAllCount", map, pagination.getStartResult(), pagination.getPageSize());
	}

	@Override
	public List<Employee> selectEmployeeList() {
		return (List<Employee>) queryList("RL_EMPLOYEE.selectEmployeeList");
	}

	@Override
	public void bachInsert(List<Employee> list) {
		this.batchInsert("RL_EMPLOYEE.abatorgenerated_insert", list);
	}

	@Override
	public List<Integer> selectEmployeeId() {
		return (List<Integer>) queryList("RL_EMPLOYEE.selectEmployeeId");
	}

	@Override
	public void updateEmployee(Employee employee) {

		update("RL_EMPLOYEE.updateEmployee", employee);
	}

	@Override
	public void deleteByComempno(Integer comempid) {

		this.delete("RL_EMPLOYEE.deleteByComempno", comempid);
	}

	@Override
	public Pagination downloadExcel(Pagination pagination,
			Map<String, Object> map) {
		return queryForPaginatedList("RL_EMPLOYEE.selectAll", "RL_EMPLOYEE.selectAllCount", map, 0, 0);
	}

	@Override
	public void updatebyComempno(List<Employee> list) {
		this.batchUpdate("RL_EMPLOYEE.updatebyComempno", list);
	}
}