package com.creditease.rc.dao.impl;

import java.util.List;

import com.creditease.rc.dao.EmployeeChangeDAO;
import com.creditease.rc.domain.EmployeeChange;
import com.creditease.rc.framework.dao.impl.BaseDao;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;
@Repository
public class EmployeeChangeDAOImpl extends BaseDao implements EmployeeChangeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public EmployeeChangeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public Long insert(EmployeeChange record) {
        Object newKey = getSqlMapClientTemplate().insert("RL_EMPLOYEE_CHANGE.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKey(EmployeeChange record) {
        int rows = getSqlMapClientTemplate().update("RL_EMPLOYEE_CHANGE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(EmployeeChange record) {
        int rows = getSqlMapClientTemplate().update("RL_EMPLOYEE_CHANGE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public EmployeeChange selectByPrimaryKey(Long employeeChangeId) {
        EmployeeChange key = new EmployeeChange();
        key.setEmployeeChangeId(employeeChangeId);
        EmployeeChange record = (EmployeeChange) getSqlMapClientTemplate().queryForObject("RL_EMPLOYEE_CHANGE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_EMPLOYEE_CHANGE
     *
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long employeeChangeId) {
        EmployeeChange key = new EmployeeChange();
        key.setEmployeeChangeId(employeeChangeId);
        int rows = getSqlMapClientTemplate().delete("RL_EMPLOYEE_CHANGE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public int selectHistoryCount(Integer comEmpId) {
		return (Integer) queryUnique("RL_EMPLOYEE_CHANGE.selectHistoryCount", comEmpId);
	}

	@Override
	public List<EmployeeChange> queryHistoryChange(Integer comEmpId) {
		return (List<EmployeeChange>) queryList("RL_EMPLOYEE_CHANGE.queryHistoryChange", comEmpId);
	}
}