package com.creditease.rc.dao.impl;

import java.util.List;

import com.creditease.rc.dao.TradeDealFormDAO;
import com.creditease.rc.domain.TradeDealForm;
import com.creditease.rc.framework.dao.impl.BaseDao;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class TradeDealFormDAOImpl extends BaseDao implements TradeDealFormDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public TradeDealFormDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public Long insert(TradeDealForm record) {
        Object newKey = getSqlMapClientTemplate().insert("RL_TRADE_DEAL_FORM.abatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKey(TradeDealForm record) {
        int rows = getSqlMapClientTemplate().update("RL_TRADE_DEAL_FORM.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public int updateByPrimaryKeySelective(TradeDealForm record) {
        int rows = getSqlMapClientTemplate().update("RL_TRADE_DEAL_FORM.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public TradeDealForm selectByPrimaryKey(Long tradedealformid) {
        TradeDealForm key = new TradeDealForm();
        key.setTradedealformid(tradedealformid);
        TradeDealForm record = (TradeDealForm) getSqlMapClientTemplate().queryForObject("RL_TRADE_DEAL_FORM.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_TRADE_DEAL_FORM
     *
     * @abatorgenerated
     */
    public int deleteByPrimaryKey(Long tradedealformid) {
        TradeDealForm key = new TradeDealForm();
        key.setTradedealformid(tradedealformid);
        int rows = getSqlMapClientTemplate().delete("RL_TRADE_DEAL_FORM.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public void bachInsert(List<TradeDealForm> tradeDealForms) {
		this.batchInsert("RL_TRADE_DEAL_FORM.abatorgenerated_insert", tradeDealForms);
	}

	@Override
	public List<TradeDealForm> selectTradeDealFormResultByCaId(
			Long creditapplicationId) {
		return (List<TradeDealForm>) queryList("RL_TRADE_DEAL_FORM.selectTradeDealFormResultByCaId", creditapplicationId);
	}
}