package com.creditease.rc.dao;

import com.creditease.rc.domain.CodeTable;
import com.creditease.rc.domain.CustomerConsultPool;
import com.creditease.rc.domain.CustomerConsultPoolLog;
import com.creditease.rc.framework.dao.IBaseDao;
import com.creditease.rc.framework.pager.Pagination;
import com.creditease.rc.vo.CustomerConsultPoolLogVo;
import com.creditease.rc.vo.CustomerConsultPoolVo;
import com.creditease.rc.vo.DataDictionaryVo;
import com.creditease.rc.vo.OperateLogVO;

import java.util.List;
import java.util.Map;
import java.util.Set;

public interface ICustomerConsultPoolLogDao extends IBaseDao {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MFC_OPT_LOG
     *
     * @abatorgenerated
     */
    void insert(CustomerConsultPoolLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MFC_OPT_LOG
     *
     * @abatorgenerated
     */
    int updateByPrimaryKey(CustomerConsultPoolLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MFC_OPT_LOG
     *
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(CustomerConsultPoolLog record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MFC_OPT_LOG
     *
     * @abatorgenerated
     */
    CustomerConsultPoolLog selectByPrimaryKey(Long optLogId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MFC_OPT_LOG
     *
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long optLogId);

    /**
     *
     * @author 韩大年
     * @Description:  日志查询-分页
     * @param operateLogVO
     * @param pagination
     * @return
     * @version v1.0
     * 2013-3-12
     */
    public Pagination selectOperateLogByPagination(OperateLogVO operateLogVO,Pagination pagination);

    /**
     * 新增日志
     * @param record
     * @return
     */
    // ----- 下面方法  用于咨询的日志
    public Long insertOpt(CustomerConsultPoolLog record);
    /**
     * 修改
     * @param record
     * @return
     */
    public int updateOpt(CustomerConsultPoolLog record);

    /**
     * 查询
     * @param operateLogVO
     * @return
     */
    public List<CustomerConsultPoolLogVo> selectOpt(CustomerConsultPoolLogVo operateLogVO);

    /**
     * 分页查询
     * @param map
     * @param pagination
     * @return
     */
    Pagination selectPagination(Map<String, Object> map, Pagination pagination);

    /**
     *
     * @param cunsultLogVo
     * @param pagination
     * @return
     */
    Pagination queryCunsult(CustomerConsultPoolLogVo cunsultLogVo, Pagination pagination);
}
