package com.creditease.rc.dao;

import java.util.List;

import com.creditease.rc.domain.ProtocolMapping;
import com.creditease.rc.framework.pager.Pagination;
import com.creditease.rc.vo.ProtocolVO;
/**
 * 
 * cs
 * Title:IProtocolMappingDAO.java
 * Description: 宜农贷2.0系统开发
 * Copyright:Copyright (c) 2013
 * Company:普信恒业科技发展（北京）有限公司
 * 2013-6-6上午10:22:57
 * @author wyf
 * @version v2.0
 */
public interface IProtocolMappingDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_PROTOCOL_MAPPING
     *
     * @abatorgenerated
     */
    void insert(ProtocolMapping record);
    
    public Long insertObject(ProtocolMapping record) ;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_PROTOCOL_MAPPING
     *
     * @abatorgenerated
     */
    int updateByPrimaryKey(ProtocolMapping record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_PROTOCOL_MAPPING
     *
     * @abatorgenerated
     */
    int updateByPrimaryKeySelective(ProtocolMapping record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_PROTOCOL_MAPPING
     *
     * @abatorgenerated
     */
    ProtocolMapping selectByPrimaryKey(Long mappingId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_PROTOCOL_MAPPING
     *
     * @abatorgenerated
     */
    int deleteByPrimaryKey(Long mappingId);
    
    /**
     * 
     * @author 韩大年  
     * @Description:  分页查询
     * @param operateLogVO
     * @param pagination
     * @return 
     * @version v1.0 
     * 2013-3-18
     */
     public Pagination selectProtocolMappingByPagination(ProtocolVO protocolVO,Pagination pagination);
     
     /**
      * 
      * @author 韩大年  
      * @Description:  查询ProtocolMappingList列表
      * @param protocolMapping
      * @return 
      * @version v1.0 
      * 2013-3-25
      */
     public List<ProtocolMapping> selectProtocolMappingListSelective(ProtocolMapping protocolMapping);
    
     /**
      * @author 罗红杰  
      * 根据creditapplicationId查询合同编号
      * 
      */
     public ProtocolMapping selectProtocolNumber(Long creditapplicationId);
     
     /**
      * 根据分公司id查询合同前缀
      * @param branchofficeId
      * @return
      */
     public String quPrefixNumber(String branchofficeId);
     /**
      * 根据申请id删除
      * @param creditapplicationId
      */
     int deleteIcp(String creditapplicationId);
}