package com.creditease.rc.dao;

import java.util.List;

import com.creditease.rc.domain.ReturnVisit;
import com.creditease.rc.domain.ReturnVisitExample;
import com.creditease.rc.framework.dao.IBaseDao;
import com.creditease.rc.framework.pager.Pagination;
import com.creditease.rc.vo.ReturnVisitVo;
/**
 * 
 * cs
 * Title:IReturnVisitDAO.java
 * Description: 宜农贷2.0系统开发
 * Copyright:Copyright (c) 2013
 * Company:普信恒业科技发展（北京）有限公司
 * 2013-6-6上午10:24:34
 * @author wyf
 * @version v2.0
 */
public interface IReturnVisitDAO extends IBaseDao{
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    void insert(ReturnVisit record);
    
    /**
     * 
     * @param record 对象 
     * @return id
     */
    long insertObject(ReturnVisit record);
    /**
     * 列表
     * @param returnVisit 对象
     * @param pagination 分页
     * @return list
     */
    public Pagination selectReturnVisitList(ReturnVisitVo returnVisit,Pagination pagination ); 
    /**
     * 模糊列表
     * @param fuzzyValue 条件
     * @param pagination 分页
     * @return list
     */
    public Pagination selectReturnVisitListFuzzy(String  fuzzyValue,Pagination pagination);


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int updateByPrimaryKey(ReturnVisit record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int updateByPrimaryKeySelective(ReturnVisit record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    List selectByExample(ReturnVisitExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    ReturnVisit selectByPrimaryKey(Long returnvisitId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int deleteByExample(ReturnVisitExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int deleteByPrimaryKey(Long returnvisitId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int countByExample(ReturnVisitExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int updateByExampleSelective(ReturnVisit record, ReturnVisitExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_RETURN_VISIT
     *
     * @abatorgenerated Wed Apr 17 14:42:51 CST 2013
     */
    int updateByExample(ReturnVisit record, ReturnVisitExample example);
}