package com.creditease.rc.dao;

import java.util.Map;

import com.creditease.rc.domain.LendingConfiguration;
import com.creditease.rc.framework.pager.Pagination;

public interface LendingConfigurationDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table RL_LENDING_CONFIGURATION
     *
     * @abatorgenerated
     */
    Long insert(LendingConfiguration record);
    /**
     * 查询所有配置
     */
    public Pagination selectAll(Pagination pagination,Map<String, Object> map);
    
  //根据id删除一条配置
    public int removeLendingConfiguration(Long lendingConfigurationId);
    //根据主键id更新一条配置
    public int updateLendingConfiguration(LendingConfiguration record);
    //根据部门id更新一条配置
    public int updateLendingConfigurationByareaDepartmentId(LendingConfiguration record);
    /**
     * 查询是否存在改条信息
     * @param record
     */
    int selectIsExist(LendingConfiguration record);
    
}