
package com.creditease.rc.app.icp;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 12 11:34:12 CST 2015
 * Generated source version: 2.2.9
 * 
 */

public final class OverdueServiceWS_OverdueServiceWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.ws.icp.creditease.com/", "OverdueServiceWSService");

    private OverdueServiceWS_OverdueServiceWSPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OverdueServiceWSService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OverdueServiceWSService ss = new OverdueServiceWSService(wsdlURL, SERVICE_NAME);
        OverdueServiceWS port = ss.getOverdueServiceWSPort();  
        
        {
        System.out.println("Invoking getOverdueInfo...");
        com.creditease.rc.app.icp.OverdueMicroInfoReq _getOverdueInfo_arg0 = null;
        com.creditease.rc.app.icp.OverdueMicroInfoRes _getOverdueInfo__return = port.getOverdueInfo(_getOverdueInfo_arg0);
        System.out.println("getOverdueInfo.result=" + _getOverdueInfo__return);


        }

        System.exit(0);
    }

}
