package com.creditease.rc.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.creditease.rc.common.JsonYMDHmsDateSerializer;

public class BalanceAccountApply {
    private Long balanceAccountApplyId; //对账申请ID
    private Long creditapplicationId;	//信贷申请单ID外键
    private String applyName;			//申请人姓名
    private Long applyId;				//申请人ID
    private Date applyTime;				//申请时间
    private Date saveMoneyTime;			//存款时间
    private BigDecimal saveMoney;		//存款金额
    private String remitMoneyName;		//汇款人姓名
    private String cashReceiptsReason;	//现金收款原因
    private String earlyRepayment;		//是否提前还款
    private Long auditorId;				//审批人ID
    private String auditorName;			//审批人姓名
    private Date auditTime;				//审批时间
    private String auditResult;			//审批结果
    private String historyFlag;			//历史标识
    private String borrRemark;			//备注
    private Long balanceDay;             //当前日
    
	public Long getBalanceDay() {
		return balanceDay;
	}

	public void setBalanceDay(Long balanceDay) {
		this.balanceDay = balanceDay;
	}

	public String getBorrRemark() {
		return borrRemark;
	}

	public void setBorrRemark(String borrRemark) {
		this.borrRemark = borrRemark;
	}

	public Long getBalanceAccountApplyId() {
        return balanceAccountApplyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.BALANCE_ACCOUNT_APPLY_ID
     *
     * @param balanceAccountApplyId the value for RL_BALANCE_ACCOUNT_APPLY.BALANCE_ACCOUNT_APPLY_ID
     *
     * @abatorgenerated
     */
    public void setBalanceAccountApplyId(Long balanceAccountApplyId) {
        this.balanceAccountApplyId = balanceAccountApplyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.CREDITAPPLICATION_ID
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.CREDITAPPLICATION_ID
     *
     * @abatorgenerated
     */
    public Long getCreditapplicationId() {
        return creditapplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.CREDITAPPLICATION_ID
     *
     * @param creditapplicationId the value for RL_BALANCE_ACCOUNT_APPLY.CREDITAPPLICATION_ID
     *
     * @abatorgenerated
     */
    public void setCreditapplicationId(Long creditapplicationId) {
        this.creditapplicationId = creditapplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_NAME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.APPLY_NAME
     *
     * @abatorgenerated
     */
    public String getApplyName() {
        return applyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_NAME
     *
     * @param applyName the value for RL_BALANCE_ACCOUNT_APPLY.APPLY_NAME
     *
     * @abatorgenerated
     */
    public void setApplyName(String applyName) {
        this.applyName = applyName == null ? null : applyName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_ID
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.APPLY_ID
     *
     * @abatorgenerated
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_ID
     *
     * @param applyId the value for RL_BALANCE_ACCOUNT_APPLY.APPLY_ID
     *
     * @abatorgenerated
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_TIME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.APPLY_TIME
     *
     * @abatorgenerated
     */
    @JsonSerialize(using = JsonYMDHmsDateSerializer.class)
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.APPLY_TIME
     *
     * @param applyTime the value for RL_BALANCE_ACCOUNT_APPLY.APPLY_TIME
     *
     * @abatorgenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY_TIME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY_TIME
     *
     * @abatorgenerated
     */
    @JsonSerialize(using = JsonYMDHmsDateSerializer.class)
    public Date getSaveMoneyTime() {
        return saveMoneyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY_TIME
     *
     * @param saveMoneyTime the value for RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY_TIME
     *
     * @abatorgenerated
     */
    public void setSaveMoneyTime(Date saveMoneyTime) {
        this.saveMoneyTime = saveMoneyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY
     *
     * @abatorgenerated
     */
    public BigDecimal getSaveMoney() {
        return saveMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY
     *
     * @param saveMoney the value for RL_BALANCE_ACCOUNT_APPLY.SAVE_MONEY
     *
     * @abatorgenerated
     */
    public void setSaveMoney(BigDecimal saveMoney) {
        this.saveMoney = saveMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.REMIT_MONEY_NAME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.REMIT_MONEY_NAME
     *
     * @abatorgenerated
     */
    public String getRemitMoneyName() {
        return remitMoneyName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.REMIT_MONEY_NAME
     *
     * @param remitMoneyName the value for RL_BALANCE_ACCOUNT_APPLY.REMIT_MONEY_NAME
     *
     * @abatorgenerated
     */
    public void setRemitMoneyName(String remitMoneyName) {
        this.remitMoneyName = remitMoneyName == null ? null : remitMoneyName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.CASH_RECEIPTS_REASON
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.CASH_RECEIPTS_REASON
     *
     * @abatorgenerated
     */
    public String getCashReceiptsReason() {
        return cashReceiptsReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.CASH_RECEIPTS_REASON
     *
     * @param cashReceiptsReason the value for RL_BALANCE_ACCOUNT_APPLY.CASH_RECEIPTS_REASON
     *
     * @abatorgenerated
     */
    public void setCashReceiptsReason(String cashReceiptsReason) {
        this.cashReceiptsReason = cashReceiptsReason == null ? null : cashReceiptsReason.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.EARLY REPAYMENT
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.EARLY REPAYMENT
     *
     * @abatorgenerated
     */
    public String getEarlyRepayment() {
        return earlyRepayment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.EARLY REPAYMENT
     *
     * @param earlyRepayment the value for RL_BALANCE_ACCOUNT_APPLY.EARLY REPAYMENT
     *
     * @abatorgenerated
     */
    public void setEarlyRepayment(String earlyRepayment) {
        this.earlyRepayment = earlyRepayment == null ? null : earlyRepayment.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDITOR_ID
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.AUDITOR_ID
     *
     * @abatorgenerated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDITOR_ID
     *
     * @param auditorId the value for RL_BALANCE_ACCOUNT_APPLY.AUDITOR_ID
     *
     * @abatorgenerated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDITOR_NAME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.AUDITOR_NAME
     *
     * @abatorgenerated
     */
    public String getAuditorName() {
        return auditorName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDITOR_NAME
     *
     * @param auditorName the value for RL_BALANCE_ACCOUNT_APPLY.AUDITOR_NAME
     *
     * @abatorgenerated
     */
    public void setAuditorName(String auditorName) {
        this.auditorName = auditorName == null ? null : auditorName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDIT_TIME
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.AUDIT_TIME
     *
     * @abatorgenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDIT_TIME
     *
     * @param auditTime the value for RL_BALANCE_ACCOUNT_APPLY.AUDIT_TIME
     *
     * @abatorgenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDIT_RESULT
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.AUDIT_RESULT
     *
     * @abatorgenerated
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.AUDIT_RESULT
     *
     * @param auditResult the value for RL_BALANCE_ACCOUNT_APPLY.AUDIT_RESULT
     *
     * @abatorgenerated
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult == null ? null : auditResult.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_BALANCE_ACCOUNT_APPLY.HISTORY_FLAG
     *
     * @return the value of RL_BALANCE_ACCOUNT_APPLY.HISTORY_FLAG
     *
     * @abatorgenerated
     */
    public String getHistoryFlag() {
        return historyFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_BALANCE_ACCOUNT_APPLY.HISTORY_FLAG
     *
     * @param historyFlag the value for RL_BALANCE_ACCOUNT_APPLY.HISTORY_FLAG
     *
     * @abatorgenerated
     */
    public void setHistoryFlag(String historyFlag) {
        this.historyFlag = historyFlag == null ? null : historyFlag.trim();
    }
}