package com.creditease.rc.domain;

import java.math.BigDecimal;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.creditease.rc.common.JsonYMDDateSerializer;
import com.creditease.rc.common.JsonYMDHMDDateSerializer;

/**
 * 
 * @author zhangman
 * Copyright: Copyright (c) 2012
 * Company: 普信恒业科技发展（北京）有限公司
 */
public class BorrowerService {
	private String hourseholdAddress; //户籍地址
	private Long borrowerServiceAppId;
	
	private String borrowerServiceAppDESId;//ID加密

	private Long creditapplicationId;

	private Long customerBasicId;

	private String name;

	private String leader;

	private String former;

	private String gender;

	private String homeAddress;

	private Short age;

	private String residenceAddress;

	private String credentialsNumber;

	private String credentialsType;

	private String borrRemark;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_BORROWER_SERVICE_APP.APPLY_DATE
	 * 
	 * @abatorgenerated
	 */
	private Date applyDate;

	private String mobilephone;

	private String paymentSource;

	private BigDecimal applyLimit;

	private BigDecimal maxMonthlyPayment;

	private String detailsLoansUse;

	private String detailsLoansUseType;

	private String livingCommercial;

	private String livingSelf;

	private String livingRent;

	private String livingRelative;

	private String livingOther;

	private Date livingDate;

	private String livingArea;

	private String creditContract;

	private BigDecimal familyIncome;

	private String auditStatus;

	private Long countyId;

	private Long townId;

	private Long villageId;

	private String consulteSource;

	private String detailsConsulteSource;

	private String firstFlag;

	private String secondFlag;

	private String thirdFlag;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_BORROWER_SERVICE_APP.VALID_STATE
	 * 
	 * @abatorgenerated
	 */
	private String validState = "1";

	private String nationality;

	private Double  livingYear;

	private String businessCommercial;

	private String businessSelf;

	private String businessRent;

	private String businessRelative;

	private String businessOther;

	private Date businessDate;

	private String businessArea;

	private Double businessYear;

	private String officePhone;

	private String maritalStatus;

	private String jobStatus;

	private String birthday;

	private String bondsmanBorrower;

	private String businessNumber;
	
	private String nationalityText;

	public String getBusinessNumber() {
		return businessNumber;
	}

	public void setBusinessNumber(String businessNumber) {
		this.businessNumber = businessNumber;
	}

	public Long getBorrowerServiceAppId() {
		return borrowerServiceAppId;
	}

	public void setBorrowerServiceAppId(Long borrowerServiceAppId) {
		this.borrowerServiceAppId = borrowerServiceAppId;
	}

	public Long getCreditapplicationId() {
		return creditapplicationId;
	}

	public void setCreditapplicationId(Long creditapplicationId) {
		this.creditapplicationId = creditapplicationId;
	}

	public Long getCustomerBasicId() {
		return customerBasicId;
	}

	public void setCustomerBasicId(Long customerBasicId) {
		this.customerBasicId = customerBasicId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLeader() {
		return leader;
	}

	public void setLeader(String leader) {
		this.leader = leader;
	}

	public String getFormer() {
		return former;
	}

	public void setFormer(String former) {
		this.former = former;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getHomeAddress() {
		return homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	public Short getAge() {
		return age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	public String getResidenceAddress() {
		return residenceAddress;
	}

	public void setResidenceAddress(String residenceAddress) {
		this.residenceAddress = residenceAddress;
	}

	public String getCredentialsNumber() {
		return credentialsNumber;
	}

	//身份证号一致 转为大写
	public void setCredentialsNumber(String credentialsNumber) {
		if(credentialsNumber != null){
			this.credentialsNumber = credentialsNumber.toUpperCase();
		}else{
			this.credentialsNumber = credentialsNumber;
		}
	}

	public String getCredentialsType() {
		return credentialsType;
	}

	public void setCredentialsType(String credentialsType) {
		this.credentialsType = credentialsType;
	}

	public String getBorrRemark() {
		return borrRemark;
	}

	public void setBorrRemark(String borrRemark) {
		this.borrRemark = borrRemark;
	}

	@JsonSerialize(using = JsonYMDHMDDateSerializer.class)
	public Date getApplyDate() {
		return applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getMobilephone() {
		return mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getPaymentSource() {
		return paymentSource;
	}

	public void setPaymentSource(String paymentSource) {
		this.paymentSource = paymentSource;
	}

	public BigDecimal getApplyLimit() {
		return applyLimit;
	}

	public void setApplyLimit(BigDecimal applyLimit) {
		this.applyLimit = applyLimit;
	}

	public BigDecimal getMaxMonthlyPayment() {
		return maxMonthlyPayment;
	}

	public void setMaxMonthlyPayment(BigDecimal maxMonthlyPayment) {
		this.maxMonthlyPayment = maxMonthlyPayment;
	}

	public String getDetailsLoansUse() {
		return detailsLoansUse;
	}

	public void setDetailsLoansUse(String detailsLoansUse) {
		this.detailsLoansUse = detailsLoansUse;
	}

	public String getDetailsLoansUseType() {
		return detailsLoansUseType;
	}

	public void setDetailsLoansUseType(String detailsLoansUseType) {
		this.detailsLoansUseType = detailsLoansUseType;
	}

	public String getLivingCommercial() {
		return livingCommercial;
	}

	public void setLivingCommercial(String livingCommercial) {
		this.livingCommercial = livingCommercial;
	}

	public String getLivingSelf() {
		return livingSelf;
	}

	public void setLivingSelf(String livingSelf) {
		this.livingSelf = livingSelf;
	}

	public String getLivingRent() {
		return livingRent;
	}

	public void setLivingRent(String livingRent) {
		this.livingRent = livingRent;
	}

	public String getLivingRelative() {
		return livingRelative;
	}

	public void setLivingRelative(String livingRelative) {
		this.livingRelative = livingRelative;
	}

	public String getLivingOther() {
		return livingOther;
	}

	public void setLivingOther(String livingOther) {
		this.livingOther = livingOther;
	}

	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getLivingDate() {
		return livingDate;
	}

	public void setLivingDate(Date livingDate) {
		this.livingDate = livingDate;
	}

	public String getLivingArea() {
		return livingArea;
	}

	public void setLivingArea(String livingArea) {
		this.livingArea = livingArea;
	}

	public String getCreditContract() {
		return creditContract;
	}

	public void setCreditContract(String creditContract) {
		this.creditContract = creditContract;
	}

	public BigDecimal getFamilyIncome() {
		return familyIncome;
	}

	public void setFamilyIncome(BigDecimal familyIncome) {
		this.familyIncome = familyIncome;
	}

	public String getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}

	public Long getCountyId() {
		return countyId;
	}

	public void setCountyId(Long countyId) {
		this.countyId = countyId;
	}

	public Long getTownId() {
		return townId;
	}

	public void setTownId(Long townId) {
		this.townId = townId;
	}

	public Long getVillageId() {
		return villageId;
	}

	public void setVillageId(Long villageId) {
		this.villageId = villageId;
	}

	public String getConsulteSource() {
		return consulteSource;
	}

	public void setConsulteSource(String consulteSource) {
		this.consulteSource = consulteSource;
	}

	public String getDetailsConsulteSource() {
		return detailsConsulteSource;
	}

	public void setDetailsConsulteSource(String detailsConsulteSource) {
		this.detailsConsulteSource = detailsConsulteSource;
	}

	public String getFirstFlag() {
		return firstFlag;
	}

	public void setFirstFlag(String firstFlag) {
		this.firstFlag = firstFlag;
	}

	public String getSecondFlag() {
		return secondFlag;
	}

	public void setSecondFlag(String secondFlag) {
		this.secondFlag = secondFlag;
	}

	public String getThirdFlag() {
		return thirdFlag;
	}

	public void setThirdFlag(String thirdFlag) {
		this.thirdFlag = thirdFlag;
	}

	public String getValidState() {
		return validState;
	}

	public void setValidState(String validState) {
		this.validState = validState;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}



	public String getBusinessCommercial() {
		return businessCommercial;
	}

	public void setBusinessCommercial(String businessCommercial) {
		this.businessCommercial = businessCommercial;
	}

	public String getBusinessSelf() {
		return businessSelf;
	}

	public void setBusinessSelf(String businessSelf) {
		this.businessSelf = businessSelf;
	}

	public String getBusinessRent() {
		return businessRent;
	}

	public void setBusinessRent(String businessRent) {
		this.businessRent = businessRent;
	}

	public String getBusinessRelative() {
		return businessRelative;
	}

	public void setBusinessRelative(String businessRelative) {
		this.businessRelative = businessRelative;
	}

	public String getBusinessOther() {
		return businessOther;
	}

	public void setBusinessOther(String businessOther) {
		this.businessOther = businessOther;
	}

	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getBusinessDate() {
		return businessDate;
	}

	public void setBusinessDate(Date businessDate) {
		this.businessDate = businessDate;
	}

	public String getBusinessArea() {
		return businessArea;
	}

	public void setBusinessArea(String businessArea) {
		this.businessArea = businessArea;
	}


	public Double getLivingYear() {
		return livingYear;
	}

	public void setLivingYear(Double livingYear) {
		this.livingYear = livingYear;
	}

	public Double getBusinessYear() {
		return businessYear;
	}

	public void setBusinessYear(Double businessYear) {
		this.businessYear = businessYear;
	}

	public String getOfficePhone() {
		return officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getMaritalStatus() {
		return maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getJobStatus() {
		return jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getBondsmanBorrower() {
		return bondsmanBorrower;
	}

	public void setBondsmanBorrower(String bondsmanBorrower) {
		this.bondsmanBorrower = bondsmanBorrower;
	}

	public String getNationalityText() {
		return nationalityText;
	}

	public void setNationalityText(String nationalityText) {
		this.nationalityText = nationalityText;
	}

	public String getHourseholdAddress() {
		return hourseholdAddress;
	}

	public void setHourseholdAddress(String hourseholdAddress) {
		this.hourseholdAddress = hourseholdAddress;
	}

	public String getBorrowerServiceAppDESId() {
		return borrowerServiceAppDESId;
	}

	public void setBorrowerServiceAppDESId(String borrowerServiceAppDESId) {
		this.borrowerServiceAppDESId = borrowerServiceAppDESId;
	}

}