package com.creditease.rc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.creditease.rc.common.JsonYMDDateSerializer;
/**
 * 
 * @author haoqiang
 *
 */
public class CreditInvestigation {
	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.CREDIT_INVESTIGATIO_ID
	 * 
	 * @abatorgenerated
	 */
	private Long creditInvestigatioId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.CREDITAPPLICATION_ID
	 * 
	 * @abatorgenerated
	 */
	private Long creditapplicationId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.NAME
	 * 
	 * @abatorgenerated
	 */
	private String name;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.SPOUSE_NAME
	 * 
	 * @abatorgenerated
	 */
	private String spouseName;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.RESULT
	 * 
	 * @abatorgenerated
	 */
	private String result;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_NAME
	 * 
	 * @abatorgenerated
	 */
	private String riskManagerName;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_ID
	 * 
	 * @abatorgenerated
	 */
	private String riskManagerId;

	/**
	 * This field was generated by Abator for iBATIS.
	 * This field corresponds to the database column RL_CREDIT_INVESTIGATIO.INVESTIGATION_DATE
	 * 
	 * @abatorgenerated
	 */
	private Date investigationDate;

	private String isValid;

	private String isSubmit;

	private List<CreditHistory> creditHistoryList = new ArrayList<CreditHistory>();
	private List<LinkmanInvestigation> linkmanInvestigationList = new ArrayList<LinkmanInvestigation>();
	private AppelleeRecord appelleeRecord;

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.CREDIT_INVESTIGATIO_ID
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.CREDIT_INVESTIGATIO_ID
	 * 
	 * @abatorgenerated
	 */

	public String getIsSubmit() {
		return isSubmit;
	}

	public void setIsSubmit(String isSubmit) {
		this.isSubmit = isSubmit;
	}

	public Long getCreditInvestigatioId() {
		return creditInvestigatioId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.CREDIT_INVESTIGATIO_ID
	 * 
	 * @param creditInvestigatioId the value for RL_CREDIT_INVESTIGATIO.CREDIT_INVESTIGATIO_ID
	 * 
	 * @abatorgenerated
	 */
	public void setCreditInvestigatioId(Long creditInvestigatioId) {
		this.creditInvestigatioId = creditInvestigatioId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.CREDITAPPLICATION_ID
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.CREDITAPPLICATION_ID
	 * 
	 * @abatorgenerated
	 */
	public Long getCreditapplicationId() {
		return creditapplicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.CREDITAPPLICATION_ID
	 * 
	 * @param creditapplicationId the value for RL_CREDIT_INVESTIGATIO.CREDITAPPLICATION_ID
	 * 
	 * @abatorgenerated
	 */
	public void setCreditapplicationId(Long creditapplicationId) {
		this.creditapplicationId = creditapplicationId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.NAME
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.NAME
	 * 
	 * @abatorgenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.NAME
	 * 
	 * @param name the value for RL_CREDIT_INVESTIGATIO.NAME
	 * 
	 * @abatorgenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.SPOUSE_NAME
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.SPOUSE_NAME
	 * 
	 * @abatorgenerated
	 */
	public String getSpouseName() {
		return spouseName;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.SPOUSE_NAME
	 * 
	 * @param spouseName the value for RL_CREDIT_INVESTIGATIO.SPOUSE_NAME
	 * 
	 * @abatorgenerated
	 */
	public void setSpouseName(String spouseName) {
		this.spouseName = spouseName == null ? null : spouseName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.RESULT
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.RESULT
	 * 
	 * @abatorgenerated
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.RESULT
	 * 
	 * @param result the value for RL_CREDIT_INVESTIGATIO.RESULT
	 * 
	 * @abatorgenerated
	 */
	public void setResult(String result) {
		this.result = result == null ? null : result.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_NAME
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.RISK_MANAGER_NAME
	 * 
	 * @abatorgenerated
	 */
	public String getRiskManagerName() {
		return riskManagerName;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_NAME
	 * 
	 * @param riskManagerName the value for RL_CREDIT_INVESTIGATIO.RISK_MANAGER_NAME
	 * 
	 * @abatorgenerated
	 */
	public void setRiskManagerName(String riskManagerName) {
		this.riskManagerName = riskManagerName == null ? null : riskManagerName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_ID
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.RISK_MANAGER_ID
	 * 
	 * @abatorgenerated
	 */
	public String getRiskManagerId() {
		return riskManagerId;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.RISK_MANAGER_ID
	 * 
	 * @param riskManagerId the value for RL_CREDIT_INVESTIGATIO.RISK_MANAGER_ID
	 * 
	 * @abatorgenerated
	 */
	public void setRiskManagerId(String riskManagerId) {
		this.riskManagerId = riskManagerId == null ? null : riskManagerId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method returns the value of the database column RL_CREDIT_INVESTIGATIO.INVESTIGATION_DATE
	 * 
	 * @return the value of RL_CREDIT_INVESTIGATIO.INVESTIGATION_DATE
	 * 
	 * @abatorgenerated
	 */
	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getInvestigationDate() {
		return investigationDate;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_CREDIT_INVESTIGATIO.INVESTIGATION_DATE
	 * 
	 * @param investigationDate the value for RL_CREDIT_INVESTIGATIO.INVESTIGATION_DATE
	 * 
	 * @abatorgenerated
	 */
	public void setInvestigationDate(Date investigationDate) {
		this.investigationDate = investigationDate;
	}

	public String getIsValid() {
		return isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}

	public List<CreditHistory> getCreditHistoryList() {
		return creditHistoryList;
	}

	public void setCreditHistoryList(List<CreditHistory> creditHistoryList) {
		this.creditHistoryList = creditHistoryList;
	}

	public List<LinkmanInvestigation> getLinkmanInvestigationList() {
		return linkmanInvestigationList;
	}

	public void setLinkmanInvestigationList(List<LinkmanInvestigation> linkmanInvestigationList) {
		this.linkmanInvestigationList = linkmanInvestigationList;
	}

	public AppelleeRecord getAppelleeRecord() {
		return appelleeRecord;
	}

	public void setAppelleeRecord(AppelleeRecord appelleeRecord) {
		this.appelleeRecord = appelleeRecord;
	}

}