package com.creditease.rc.domain;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.creditease.rc.common.JsonYMDDateSerializer;

/**
 * 
 * cs
 * Title:DataBestowalDetail.java
 * Description: 宜农贷2.0系统开发
 * Copyright:Copyright (c) 2013
 * Company:普信恒业科技发展（北京）有限公司
 * 2013-6-6上午10:07:52
 * @author wyf
 * @version v2.0
 */
public class DataBestowalDetail {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_DETAIL_ID
     *
     * @abatorgenerated
     */
    private Long dataBestowalDetailId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_ID
     *
     * @abatorgenerated
     */
    private Long dataBestowalId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_DATA_BESTOWAL_DETAIL.CREDIT_APPLICATION_ID
     *
     * @abatorgenerated
     */
    private Long creditApplicationId;
    
    private String auditStatus;
    
    private String isOverdue;
    
    private Date signagreementDate;
    

    public String getIsOverdue() {
		return isOverdue;
	}

	public void setIsOverdue(String isOverdue) {
		this.isOverdue = isOverdue;
	}


	
	@JsonSerialize(using = JsonYMDDateSerializer.class)
	public Date getSignagreementDate() {
		return signagreementDate;
	}

	public void setSignagreementDate(Date signagreementDate) {
		this.signagreementDate = signagreementDate;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_DETAIL_ID
     *
     * @return the value of RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_DETAIL_ID
     *
     * @abatorgenerated
     */
    public Long getDataBestowalDetailId() {
        return dataBestowalDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_DETAIL_ID
     *
     * @param dataBestowalDetailId the value for RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_DETAIL_ID
     *
     * @abatorgenerated
     */
    public void setDataBestowalDetailId(Long dataBestowalDetailId) {
        this.dataBestowalDetailId = dataBestowalDetailId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_ID
     *
     * @return the value of RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_ID
     *
     * @abatorgenerated
     */
    public Long getDataBestowalId() {
        return dataBestowalId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_ID
     *
     * @param dataBestowalId the value for RL_DATA_BESTOWAL_DETAIL.DATA_BESTOWAL_ID
     *
     * @abatorgenerated
     */
    public void setDataBestowalId(Long dataBestowalId) {
        this.dataBestowalId = dataBestowalId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_DATA_BESTOWAL_DETAIL.CREDIT_APPLICATION_ID
     *
     * @return the value of RL_DATA_BESTOWAL_DETAIL.CREDIT_APPLICATION_ID
     *
     * @abatorgenerated
     */
    public Long getCreditApplicationId() {
        return creditApplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_DATA_BESTOWAL_DETAIL.CREDIT_APPLICATION_ID
     *
     * @param creditApplicationId the value for RL_DATA_BESTOWAL_DETAIL.CREDIT_APPLICATION_ID
     *
     * @abatorgenerated
     */
    public void setCreditApplicationId(Long creditApplicationId) {
        this.creditApplicationId = creditApplicationId;
    }

	public String getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}
    
}