package com.creditease.rc.domain;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.omg.CORBA.PRIVATE_MEMBER;

import com.creditease.rc.common.JsonYMDDateSerializer;

/**
 * 
 * @author zhangman
 * 
 */
public class JobInfo implements Serializable {

	private Long jobInfoId;

	private Long borrowerServiceAppId;

	private String workunitAddress;

	private String workunitTelephone;

	private Date enterTime;

	private String department;

	private String post;

	private Object company;

	private Double years;

	private String contantPerson;

	private String contanTelephone;

	private Double income;

	
	private String seq;

	public String getSeq() {
		return seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}
	public Double getIncome() {
		return income;
	}

	public void setIncome(Double income) {
		this.income = income;
	}

	public Long getJobInfoId() {
		return jobInfoId;
	}

	public void setJobInfoId(Long jobInfoId) {
		this.jobInfoId = jobInfoId;
	}

	public Long getBorrowerServiceAppId() {
		return borrowerServiceAppId;
	}

	public void setBorrowerServiceAppId(Long borrowerServiceAppId) {
		this.borrowerServiceAppId = borrowerServiceAppId;
	}

	public String getWorkunitAddress() {
		return workunitAddress;
	}

	public void setWorkunitAddress(String workunitAddress) {
		this.workunitAddress = workunitAddress == null ? null : workunitAddress.trim();
	}

	public String getWorkunitTelephone() {
		return workunitTelephone;
	}

	public void setWorkunitTelephone(String workunitTelephone) {
		this.workunitTelephone = workunitTelephone == null ? null : workunitTelephone.trim();
	}

	public Date getEnterTime() {
		return enterTime;
	}

	public void setEnterTime(Date enterTime) {
		this.enterTime = enterTime;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department == null ? null : department.trim();
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post == null ? null : post.trim();
	}

	public Object getCompany() {
		return company;
	}

	public void setCompany(Object company) {
		this.company = company;
	}

	public Double getYears() {
		return years;
	}

	public void setYears(Double years) {
		this.years = years;
	}

	public String getContantPerson() {
		return contantPerson;
	}

	public void setContantPerson(String contantPerson) {
		this.contantPerson = contantPerson == null ? null : contantPerson.trim();
	}

	public String getContanTelephone() {
		return contanTelephone;
	}

	/**
	 * This method was generated by Abator for iBATIS.
	 * This method sets the value of the database column RL_JOB_INFO.CONTAN_TELEPHONE
	 * 
	 * @param contanTelephone the value for RL_JOB_INFO.CONTAN_TELEPHONE
	 * 
	 * @abatorgenerated
	 */
	public void setContanTelephone(String contanTelephone) {
		this.contanTelephone = contanTelephone == null ? null : contanTelephone.trim();
	}
}
