package com.creditease.rc.domain;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 
 * @author Administrator
 *
 */
public class PaymentRecord {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.PAYMENT_RECORD_ID
     *
     * @abatorgenerated
     */
    private Integer paymentRecordId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.CREDITAPPLICATION_ID
     *
     * @abatorgenerated
     */
    private Integer creditapplicationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.PAY_AMOUNT
     *
     * @abatorgenerated
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.PAY_STATUS
     *
     * @abatorgenerated
     */
    private String payStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.OPERATOR_ID
     *
     * @abatorgenerated
     */
    private String operatorId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.OPERATOR_NAME
     *
     * @abatorgenerated
     */
    private String operatorName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.OPERATE_DATE
     *
     * @abatorgenerated
     */
    private Date operateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.REMARK
     *
     * @abatorgenerated
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column RL_PAYMENT_RECORD.HISTORY_FLAG
     *
     * @abatorgenerated
     */
    private String historyFlag;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.PAYMENT_RECORD_ID
     *
     * @return the value of RL_PAYMENT_RECORD.PAYMENT_RECORD_ID
     *
     * @abatorgenerated
     */
    public Integer getPaymentRecordId() {
        return paymentRecordId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.PAYMENT_RECORD_ID
     *
     * @param paymentRecordId the value for RL_PAYMENT_RECORD.PAYMENT_RECORD_ID
     *
     * @abatorgenerated
     */
    public void setPaymentRecordId(Integer paymentRecordId) {
        this.paymentRecordId = paymentRecordId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.CREDITAPPLICATION_ID
     *
     * @return the value of RL_PAYMENT_RECORD.CREDITAPPLICATION_ID
     *
     * @abatorgenerated
     */
    public Integer getCreditapplicationId() {
        return creditapplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.CREDITAPPLICATION_ID
     *
     * @param creditapplicationId the value for RL_PAYMENT_RECORD.CREDITAPPLICATION_ID
     *
     * @abatorgenerated
     */
    public void setCreditapplicationId(Integer creditapplicationId) {
        this.creditapplicationId = creditapplicationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.PAY_AMOUNT
     *
     * @return the value of RL_PAYMENT_RECORD.PAY_AMOUNT
     *
     * @abatorgenerated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.PAY_AMOUNT
     *
     * @param payAmount the value for RL_PAYMENT_RECORD.PAY_AMOUNT
     *
     * @abatorgenerated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.PAY_STATUS
     *
     * @return the value of RL_PAYMENT_RECORD.PAY_STATUS
     *
     * @abatorgenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.PAY_STATUS
     *
     * @param payStatus the value for RL_PAYMENT_RECORD.PAY_STATUS
     *
     * @abatorgenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.OPERATOR_ID
     *
     * @return the value of RL_PAYMENT_RECORD.OPERATOR_ID
     *
     * @abatorgenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.OPERATOR_ID
     *
     * @param operatorId the value for RL_PAYMENT_RECORD.OPERATOR_ID
     *
     * @abatorgenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.OPERATOR_NAME
     *
     * @return the value of RL_PAYMENT_RECORD.OPERATOR_NAME
     *
     * @abatorgenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.OPERATOR_NAME
     *
     * @param operatorName the value for RL_PAYMENT_RECORD.OPERATOR_NAME
     *
     * @abatorgenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.OPERATE_DATE
     *
     * @return the value of RL_PAYMENT_RECORD.OPERATE_DATE
     *
     * @abatorgenerated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.OPERATE_DATE
     *
     * @param operateDate the value for RL_PAYMENT_RECORD.OPERATE_DATE
     *
     * @abatorgenerated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.REMARK
     *
     * @return the value of RL_PAYMENT_RECORD.REMARK
     *
     * @abatorgenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.REMARK
     *
     * @param remark the value for RL_PAYMENT_RECORD.REMARK
     *
     * @abatorgenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column RL_PAYMENT_RECORD.HISTORY_FLAG
     *
     * @return the value of RL_PAYMENT_RECORD.HISTORY_FLAG
     *
     * @abatorgenerated
     */
    public String getHistoryFlag() {
        return historyFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column RL_PAYMENT_RECORD.HISTORY_FLAG
     *
     * @param historyFlag the value for RL_PAYMENT_RECORD.HISTORY_FLAG
     *
     * @abatorgenerated
     */
    public void setHistoryFlag(String historyFlag) {
        this.historyFlag = historyFlag == null ? null : historyFlag.trim();
    }
}